import "dotenv/config";
import { seedCategory, type WordData } from "./seed-helpers";

// ─── 1. Countries & Travel ─────────────────────────────────────────────────

const countriesTravel: WordData[] = [
  {
    farsiWord: "ایران",
    phonetic: "iran",
    englishTranslation: "Iran",
    exampleFarsi: "ایران کشور زیبایی است",
    examplePhonetic: "iran keshvare zibaayi ast",
    exampleEnglish: "Iran is a beautiful country",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آمریکا",
    phonetic: "amrika",
    englishTranslation: "America",
    exampleFarsi: "برادرم در آمریکا زندگی می‌کند",
    examplePhonetic: "baradaram dar amrika zendegi mikonad",
    exampleEnglish: "My brother lives in America",
    difficultyLevel: 3,
  },
  {
    farsiWord: "انگلیس",
    phonetic: "engelestan",
    englishTranslation: "England",
    exampleFarsi: "می‌خواهم در انگلیس درس بخوانم",
    examplePhonetic: "mikhaham dar engelestan dars bekhaanam",
    exampleEnglish: "I want to study in England",
    difficultyLevel: 3,
  },
  {
    farsiWord: "فرانسه",
    phonetic: "faransah",
    englishTranslation: "France",
    exampleFarsi: "فرانسه به خاطر غذاهایش معروف است",
    examplePhonetic: "faransah be khatere ghazahayash maroof ast",
    exampleEnglish: "France is famous for its food",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آلمان",
    phonetic: "alman",
    englishTranslation: "Germany",
    exampleFarsi: "آلمان صنعت قوی دارد",
    examplePhonetic: "alman san'ate ghavi darad",
    exampleEnglish: "Germany has a strong industry",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ترکیه",
    phonetic: "torkiyeh",
    englishTranslation: "Turkey",
    exampleFarsi: "تابستان به ترکیه سفر کردیم",
    examplePhonetic: "tabestan be torkiyeh safar kardim",
    exampleEnglish: "We traveled to Turkey in summer",
    difficultyLevel: 3,
  },
  {
    farsiWord: "چین",
    phonetic: "chin",
    englishTranslation: "China",
    exampleFarsi: "چین جمعیت زیادی دارد",
    examplePhonetic: "chin jam'iyate ziyadi darad",
    exampleEnglish: "China has a large population",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ژاپن",
    phonetic: "zhaapon",
    englishTranslation: "Japan",
    exampleFarsi: "ژاپن تکنولوژی پیشرفته‌ای دارد",
    examplePhonetic: "zhaapon teknolozhi-ye pishrafte-i darad",
    exampleEnglish: "Japan has advanced technology",
    difficultyLevel: 3,
  },
  {
    farsiWord: "هند",
    phonetic: "hend",
    englishTranslation: "India",
    exampleFarsi: "غذاهای هندی خیلی تند هستند",
    examplePhonetic: "ghazahaye hendi kheyli tond hastand",
    exampleEnglish: "Indian foods are very spicy",
    difficultyLevel: 3,
  },
  {
    farsiWord: "روسیه",
    phonetic: "roosiyeh",
    englishTranslation: "Russia",
    exampleFarsi: "روسیه بزرگ‌ترین کشور دنیاست",
    examplePhonetic: "roosiyeh bozorgtarin keshvare donyast",
    exampleEnglish: "Russia is the largest country in the world",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ایرانی",
    phonetic: "irani",
    englishTranslation: "Iranian",
    exampleFarsi: "من ایرانی هستم",
    examplePhonetic: "man irani hastam",
    exampleEnglish: "I am Iranian",
    difficultyLevel: 3,
  },
  {
    farsiWord: "فرودگاه",
    phonetic: "foroodgah",
    englishTranslation: "Airport",
    exampleFarsi: "ساعت شش باید در فرودگاه باشیم",
    examplePhonetic: "sa'ate shesh bayad dar foroodgah bashim",
    exampleEnglish: "We need to be at the airport at six o'clock",
    difficultyLevel: 3,
  },
  {
    farsiWord: "هتل",
    phonetic: "hotel",
    englishTranslation: "Hotel",
    exampleFarsi: "هتل ما نزدیک ساحل بود",
    examplePhonetic: "hotele ma nazdike sahel bood",
    exampleEnglish: "Our hotel was near the beach",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پاسپورت",
    phonetic: "pasport",
    englishTranslation: "Passport",
    exampleFarsi: "پاسپورتت را فراموش نکن",
    examplePhonetic: "pasportet ra faramoosh nakon",
    exampleEnglish: "Don't forget your passport",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بلیت",
    phonetic: "belit",
    englishTranslation: "Ticket",
    exampleFarsi: "بلیت هواپیما خیلی گران بود",
    examplePhonetic: "belite havapeyma kheyli geran bood",
    exampleEnglish: "The plane ticket was very expensive",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سفر",
    phonetic: "safar",
    englishTranslation: "Trip",
    exampleFarsi: "سفر خوبی داشتیم",
    examplePhonetic: "safare khoobi dashtim",
    exampleEnglish: "We had a good trip",
    difficultyLevel: 3,
  },
  {
    farsiWord: "چمدان",
    phonetic: "chamedan",
    englishTranslation: "Suitcase",
    exampleFarsi: "چمدانم خیلی سنگین است",
    examplePhonetic: "chamedanam kheyli sangin ast",
    exampleEnglish: "My suitcase is very heavy",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نقشه",
    phonetic: "naghsheh",
    englishTranslation: "Map",
    exampleFarsi: "نقشه شهر را داری؟",
    examplePhonetic: "naghshe-ye shahr ra dari?",
    exampleEnglish: "Do you have the city map?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ویزا",
    phonetic: "viza",
    englishTranslation: "Visa",
    exampleFarsi: "برای سفر به اروپا ویزا لازم دارید",
    examplePhonetic: "baraye safar be orupa viza lazem darid",
    exampleEnglish: "You need a visa for traveling to Europe",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تاکسی",
    phonetic: "taksi",
    englishTranslation: "Taxi",
    exampleFarsi: "با تاکسی به هتل رفتیم",
    examplePhonetic: "ba taksi be hotel raftim",
    exampleEnglish: "We went to the hotel by taxi",
    difficultyLevel: 3,
  },
];

// ─── 2. Phrasal Verbs Part 1 ───────────────────────────────────────────────

const phrasalVerbs: WordData[] = [
  {
    farsiWord: "صبر کردن",
    phonetic: "sabr kardan",
    englishTranslation: "To wait",
    exampleFarsi: "لطفاً کمی صبر کنید",
    examplePhonetic: "lotfan kami sabr konid",
    exampleEnglish: "Please wait a little",
    difficultyLevel: 3,
  },
  {
    farsiWord: "فکر کردن",
    phonetic: "fekr kardan",
    englishTranslation: "To think",
    exampleFarsi: "باید درباره‌اش فکر کنم",
    examplePhonetic: "bayad darbare-ash fekr konam",
    exampleEnglish: "I need to think about it",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تلاش کردن",
    phonetic: "talash kardan",
    englishTranslation: "To try",
    exampleFarsi: "تلاش می‌کنم بهتر باشم",
    examplePhonetic: "talash mikonam behtar basham",
    exampleEnglish: "I try to be better",
    difficultyLevel: 3,
  },
  {
    farsiWord: "موافقت کردن",
    phonetic: "movafeghat kardan",
    englishTranslation: "To agree",
    exampleFarsi: "آنها با پیشنهاد ما موافقت کردند",
    examplePhonetic: "anha ba pishnahade ma movafeghat kardand",
    exampleEnglish: "They agreed with our suggestion",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شرکت کردن",
    phonetic: "sherkat kardan",
    englishTranslation: "To participate",
    exampleFarsi: "در مسابقه شرکت کردم",
    examplePhonetic: "dar mosabeghe sherkat kardam",
    exampleEnglish: "I participated in the competition",
    difficultyLevel: 3,
  },
  {
    farsiWord: "استفاده کردن",
    phonetic: "estefade kardan",
    englishTranslation: "To use",
    exampleFarsi: "از این برنامه زیاد استفاده می‌کنم",
    examplePhonetic: "az in barname ziyad estefade mikonam",
    exampleEnglish: "I use this app a lot",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تماس گرفتن",
    phonetic: "tamas gereftan",
    englishTranslation: "To call/phone",
    exampleFarsi: "فردا با شما تماس می‌گیرم",
    examplePhonetic: "farda ba shoma tamas migiram",
    exampleEnglish: "I will call you tomorrow",
    difficultyLevel: 3,
  },
  {
    farsiWord: "قبول کردن",
    phonetic: "ghabool kardan",
    englishTranslation: "To accept",
    exampleFarsi: "دعوتش را قبول کردم",
    examplePhonetic: "da'vatash ra ghabool kardam",
    exampleEnglish: "I accepted his invitation",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رد کردن",
    phonetic: "rad kardan",
    englishTranslation: "To reject",
    exampleFarsi: "پیشنهاد را رد کرد",
    examplePhonetic: "pishnahad ra rad kard",
    exampleEnglish: "He rejected the offer",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تصمیم گرفتن",
    phonetic: "tasmim gereftan",
    englishTranslation: "To decide",
    exampleFarsi: "تصمیم گرفتم فارسی یاد بگیرم",
    examplePhonetic: "tasmim gereftam farsi yad begiram",
    exampleEnglish: "I decided to learn Farsi",
    difficultyLevel: 3,
  },
  {
    farsiWord: "اجازه دادن",
    phonetic: "ejaze dadan",
    englishTranslation: "To allow",
    exampleFarsi: "مادرم اجازه نداد بیرون بروم",
    examplePhonetic: "madaram ejaze nadad biroon beravam",
    exampleEnglish: "My mother didn't allow me to go outside",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دعوت کردن",
    phonetic: "da'vat kardan",
    englishTranslation: "To invite",
    exampleFarsi: "دوستانم را به خانه دعوت کردم",
    examplePhonetic: "dostanam ra be khane da'vat kardam",
    exampleEnglish: "I invited my friends to my house",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جستجو کردن",
    phonetic: "jostejoo kardan",
    englishTranslation: "To search",
    exampleFarsi: "در اینترنت جستجو کردم ولی پیدا نکردم",
    examplePhonetic: "dar internet jostejoo kardam vali peyda nakardam",
    exampleEnglish: "I searched on the internet but didn't find it",
    difficultyLevel: 3,
  },
  {
    farsiWord: "امتحان کردن",
    phonetic: "emtehan kardan",
    englishTranslation: "To test/try",
    exampleFarsi: "این غذا را امتحان کن، خوشمزه است",
    examplePhonetic: "in ghaza ra emtehan kon, khoshmazeh ast",
    exampleEnglish: "Try this food, it's delicious",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تعریف کردن",
    phonetic: "ta'rif kardan",
    englishTranslation: "To compliment/describe",
    exampleFarsi: "معلم از کار دانش‌آموز تعریف کرد",
    examplePhonetic: "mo'alem az kare danesh-amooz ta'rif kard",
    exampleEnglish: "The teacher complimented the student's work",
    difficultyLevel: 3,
  },
];

// ─── 3. Phrasal Verbs Part 2 ───────────────────────────────────────────────

const phrasalVerbs2: WordData[] = [
  {
    farsiWord: "عادت کردن",
    phonetic: "adat kardan",
    englishTranslation: "To get used to",
    exampleFarsi: "به هوای سرد عادت کردم",
    examplePhonetic: "be havaye sard adat kardam",
    exampleEnglish: "I got used to the cold weather",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خسته شدن",
    phonetic: "khaste shodan",
    englishTranslation: "To get tired",
    exampleFarsi: "بعد از کار خیلی خسته شدم",
    examplePhonetic: "ba'd az kar kheyli khaste shodam",
    exampleEnglish: "I got very tired after work",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عصبانی شدن",
    phonetic: "asabani shodan",
    englishTranslation: "To get angry",
    exampleFarsi: "از دست او عصبانی شدم",
    examplePhonetic: "az daste oo asabani shodam",
    exampleEnglish: "I got angry at him",
    difficultyLevel: 3,
  },
  {
    farsiWord: "گم شدن",
    phonetic: "gom shodan",
    englishTranslation: "To get lost",
    exampleFarsi: "در شهر گم شدیم",
    examplePhonetic: "dar shahr gom shodim",
    exampleEnglish: "We got lost in the city",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بیدار شدن",
    phonetic: "bidaar shodan",
    englishTranslation: "To wake up",
    exampleFarsi: "هر روز ساعت شش بیدار می‌شوم",
    examplePhonetic: "har rooz sa'ate shesh bidaar misham",
    exampleEnglish: "I wake up at six every day",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آماده شدن",
    phonetic: "amade shodan",
    englishTranslation: "To get ready",
    exampleFarsi: "سریع آماده شو، دیر شده",
    examplePhonetic: "sari' amade sho, dir shode",
    exampleEnglish: "Get ready quickly, it's getting late",
    difficultyLevel: 3,
  },
  {
    farsiWord: "متوجه شدن",
    phonetic: "motavajeh shodan",
    englishTranslation: "To notice/realize",
    exampleFarsi: "متوجه اشتباهم شدم",
    examplePhonetic: "motavajeha eshtebaaham shodam",
    exampleEnglish: "I realized my mistake",
    difficultyLevel: 3,
  },
  {
    farsiWord: "راضی شدن",
    phonetic: "razi shodan",
    englishTranslation: "To be satisfied",
    exampleFarsi: "بالاخره از نتیجه راضی شد",
    examplePhonetic: "belakhare az natijeh razi shod",
    exampleEnglish: "He was finally satisfied with the result",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نزدیک شدن",
    phonetic: "nazdik shodan",
    englishTranslation: "To approach",
    exampleFarsi: "به مقصد نزدیک می‌شویم",
    examplePhonetic: "be maghsad nazdik mishavim",
    exampleEnglish: "We are approaching the destination",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دور شدن",
    phonetic: "door shodan",
    englishTranslation: "To go away",
    exampleFarsi: "از آن مکان دور شو",
    examplePhonetic: "az an makan door sho",
    exampleEnglish: "Get away from that place",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سوار شدن",
    phonetic: "savar shodan",
    englishTranslation: "To get on/board",
    exampleFarsi: "سوار اتوبوس شدیم",
    examplePhonetic: "savare otobus shodim",
    exampleEnglish: "We got on the bus",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پیاده شدن",
    phonetic: "piade shodan",
    englishTranslation: "To get off",
    exampleFarsi: "ایستگاه بعدی باید پیاده شوید",
    examplePhonetic: "istgahe ba'di bayad piade shavid",
    exampleEnglish: "You should get off at the next station",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عوض شدن",
    phonetic: "avaz shodan",
    englishTranslation: "To change (intransitive)",
    exampleFarsi: "هوا عوض شده است",
    examplePhonetic: "hava avaz shode ast",
    exampleEnglish: "The weather has changed",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کم شدن",
    phonetic: "kam shodan",
    englishTranslation: "To decrease",
    exampleFarsi: "آب رودخانه کم شده است",
    examplePhonetic: "abe roodkhaneh kam shode ast",
    exampleEnglish: "The river water has decreased",
    difficultyLevel: 3,
  },
  {
    farsiWord: "زیاد شدن",
    phonetic: "ziad shodan",
    englishTranslation: "To increase",
    exampleFarsi: "قیمت‌ها زیاد شده‌اند",
    examplePhonetic: "gheymat-ha ziad shode-and",
    exampleEnglish: "Prices have increased",
    difficultyLevel: 3,
  },
];

// ─── 4. Abstract Concepts ──────────────────────────────────────────────────

const abstractConcepts: WordData[] = [
  {
    farsiWord: "زندگی",
    phonetic: "zendegi",
    englishTranslation: "Life",
    exampleFarsi: "زندگی خیلی کوتاه است",
    examplePhonetic: "zendegi kheyli kootah ast",
    exampleEnglish: "Life is very short",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مرگ",
    phonetic: "marg",
    englishTranslation: "Death",
    exampleFarsi: "مرگ بخشی از زندگی است",
    examplePhonetic: "marg bakhshi az zendegi ast",
    exampleEnglish: "Death is a part of life",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عشق",
    phonetic: "eshgh",
    englishTranslation: "Love",
    exampleFarsi: "عشق قدرتمندترین احساس است",
    examplePhonetic: "eshgh ghodratmandtarin ehsas ast",
    exampleEnglish: "Love is the most powerful feeling",
    difficultyLevel: 3,
  },
  {
    farsiWord: "امید",
    phonetic: "omid",
    englishTranslation: "Hope",
    exampleFarsi: "هیچوقت امیدت را از دست نده",
    examplePhonetic: "hichvaght omidet ra az dast nade",
    exampleEnglish: "Never lose your hope",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ترس",
    phonetic: "tars",
    englishTranslation: "Fear",
    exampleFarsi: "ترس مانع پیشرفت می‌شود",
    examplePhonetic: "tars mane'e pishraft mishavad",
    exampleEnglish: "Fear prevents progress",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آزادی",
    phonetic: "azadi",
    englishTranslation: "Freedom",
    exampleFarsi: "آزادی حق هر انسانی است",
    examplePhonetic: "azadi haghe har ensani ast",
    exampleEnglish: "Freedom is every human's right",
    difficultyLevel: 3,
  },
  {
    farsiWord: "صلح",
    phonetic: "solh",
    englishTranslation: "Peace",
    exampleFarsi: "همه مردم دنیا صلح می‌خواهند",
    examplePhonetic: "hame mardome donya solh mikhaahand",
    exampleEnglish: "All people of the world want peace",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جنگ",
    phonetic: "jang",
    englishTranslation: "War",
    exampleFarsi: "جنگ همه چیز را ویران می‌کند",
    examplePhonetic: "jang hame chiz ra viran mikonad",
    exampleEnglish: "War destroys everything",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دوستی",
    phonetic: "doosti",
    englishTranslation: "Friendship",
    exampleFarsi: "دوستی ما خیلی قدیمی است",
    examplePhonetic: "doostiye ma kheyli ghadimi ast",
    exampleEnglish: "Our friendship is very old",
    difficultyLevel: 3,
  },
  {
    farsiWord: "حقیقت",
    phonetic: "haghighat",
    englishTranslation: "Truth",
    exampleFarsi: "حقیقت همیشه آشکار می‌شود",
    examplePhonetic: "haghighat hamisheh ashkar mishavad",
    exampleEnglish: "The truth always comes out",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دروغ",
    phonetic: "dorough",
    englishTranslation: "Lie",
    exampleFarsi: "دروغ گفتن کار بدی است",
    examplePhonetic: "dorough goftan kare badi ast",
    exampleEnglish: "Lying is a bad thing",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خاطره",
    phonetic: "khatereh",
    englishTranslation: "Memory",
    exampleFarsi: "خاطرات خوبی از سفرمان دارم",
    examplePhonetic: "khateraate khoobi az safaremaan daram",
    exampleEnglish: "I have good memories from our trip",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رویا",
    phonetic: "roya",
    englishTranslation: "Dream",
    exampleFarsi: "رویاهایت را دنبال کن",
    examplePhonetic: "royahayet ra donbal kon",
    exampleEnglish: "Follow your dreams",
    difficultyLevel: 3,
  },
  {
    farsiWord: "قدرت",
    phonetic: "ghodrat",
    englishTranslation: "Power",
    exampleFarsi: "دانش قدرت است",
    examplePhonetic: "danesh ghodrat ast",
    exampleEnglish: "Knowledge is power",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سعادت",
    phonetic: "sa'adat",
    englishTranslation: "Happiness/Prosperity",
    exampleFarsi: "سعادت واقعی در چیست؟",
    examplePhonetic: "sa'adate vaghei dar chist?",
    exampleEnglish: "What is true happiness?",
    difficultyLevel: 3,
  },
];

// ─── 5. Education & Learning ───────────────────────────────────────────────

const education: WordData[] = [
  {
    farsiWord: "دانشگاه",
    phonetic: "daneshgah",
    englishTranslation: "University",
    exampleFarsi: "در دانشگاه تهران درس می‌خوانم",
    examplePhonetic: "dar daneshgahe tehran dars mikhanam",
    exampleEnglish: "I study at Tehran University",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مدرک",
    phonetic: "madrak",
    englishTranslation: "Degree/Certificate",
    exampleFarsi: "مدرک لیسانس دارم",
    examplePhonetic: "madrake lisans daram",
    exampleEnglish: "I have a bachelor's degree",
    difficultyLevel: 3,
  },
  {
    farsiWord: "امتحان",
    phonetic: "emtehan",
    englishTranslation: "Exam",
    exampleFarsi: "فردا امتحان ریاضی داریم",
    examplePhonetic: "farda emtehane riazi darim",
    exampleEnglish: "We have a math exam tomorrow",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نمره",
    phonetic: "nomreh",
    englishTranslation: "Grade",
    exampleFarsi: "نمره خوبی گرفتم",
    examplePhonetic: "nomreye khoobi gereftam",
    exampleEnglish: "I got a good grade",
    difficultyLevel: 3,
  },
  {
    farsiWord: "استاد",
    phonetic: "ostad",
    englishTranslation: "Professor",
    exampleFarsi: "استاد ما خیلی باتجربه است",
    examplePhonetic: "ostad-e ma kheyli ba-tajrobe ast",
    exampleEnglish: "Our professor is very experienced",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تحقیق",
    phonetic: "tahghigh",
    englishTranslation: "Research",
    exampleFarsi: "درباره این موضوع تحقیق کردم",
    examplePhonetic: "darbare in mozoo' tahghigh kardam",
    exampleEnglish: "I did research on this topic",
    difficultyLevel: 3,
  },
  {
    farsiWord: "درس",
    phonetic: "dars",
    englishTranslation: "Lesson",
    exampleFarsi: "درس امروز خیلی مهم بود",
    examplePhonetic: "darse emrooz kheyli mohem bood",
    exampleEnglish: "Today's lesson was very important",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تکلیف",
    phonetic: "taklif",
    englishTranslation: "Homework",
    exampleFarsi: "تکلیف‌هایت را انجام دادی؟",
    examplePhonetic: "taklifhayat ra anjam dadi?",
    exampleEnglish: "Did you do your homework?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رشته",
    phonetic: "reshte",
    englishTranslation: "Major/Field",
    exampleFarsi: "رشته تحصیلی من مهندسی است",
    examplePhonetic: "reshteye tahsiliye man mohandesi ast",
    exampleEnglish: "My major is engineering",
    difficultyLevel: 3,
  },
  {
    farsiWord: "علم",
    phonetic: "elm",
    englishTranslation: "Science",
    exampleFarsi: "علم کلید پیشرفت است",
    examplePhonetic: "elm kelide pishraft ast",
    exampleEnglish: "Science is the key to progress",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ریاضی",
    phonetic: "riazi",
    englishTranslation: "Mathematics",
    exampleFarsi: "ریاضی درس مورد علاقه من است",
    examplePhonetic: "riazi darse mored-e alaghe-ye man ast",
    exampleEnglish: "Mathematics is my favorite subject",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تاریخ",
    phonetic: "tarikh",
    englishTranslation: "History",
    exampleFarsi: "تاریخ ایران خیلی غنی است",
    examplePhonetic: "tarikhe iran kheyli ghani ast",
    exampleEnglish: "Iran's history is very rich",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کلاس",
    phonetic: "kelas",
    englishTranslation: "Class",
    exampleFarsi: "کلاس ساعت هشت شروع می‌شود",
    examplePhonetic: "kelas sa'ate hasht shoroo mishavad",
    exampleEnglish: "Class starts at eight o'clock",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دانش‌آموز",
    phonetic: "danesh-amooz",
    englishTranslation: "Student (school)",
    exampleFarsi: "دانش‌آموزان در حیاط بازی می‌کنند",
    examplePhonetic: "danesh-amoozan dar hayat bazi mikonand",
    exampleEnglish: "The students are playing in the yard",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دفتر",
    phonetic: "daftar",
    englishTranslation: "Notebook",
    exampleFarsi: "یادداشت‌هایم را در دفتر نوشتم",
    examplePhonetic: "yaddashthayam ra dar daftar neveshtam",
    exampleEnglish: "I wrote my notes in the notebook",
    difficultyLevel: 3,
  },
];

// ─── 6. Health & Body ──────────────────────────────────────────────────────

const health: WordData[] = [
  {
    farsiWord: "مریض",
    phonetic: "mariz",
    englishTranslation: "Sick",
    exampleFarsi: "دیروز مریض بودم و نرفتم سر کار",
    examplePhonetic: "dirooz mariz boodam va naraftam sare kar",
    exampleEnglish: "Yesterday I was sick and didn't go to work",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دارو",
    phonetic: "daru",
    englishTranslation: "Medicine",
    exampleFarsi: "باید داروهایت را سر وقت بخوری",
    examplePhonetic: "bayad daruhayat ra sare vaght bekhori",
    exampleEnglish: "You should take your medicine on time",
    difficultyLevel: 3,
  },
  {
    farsiWord: "درد",
    phonetic: "dard",
    englishTranslation: "Pain",
    exampleFarsi: "پایم خیلی درد می‌کند",
    examplePhonetic: "payam kheyli dard mikonad",
    exampleEnglish: "My foot hurts a lot",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تب",
    phonetic: "tab",
    englishTranslation: "Fever",
    exampleFarsi: "بچه تب دارد",
    examplePhonetic: "bachche tab darad",
    exampleEnglish: "The child has a fever",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سالم",
    phonetic: "salem",
    englishTranslation: "Healthy",
    exampleFarsi: "غذای سالم بخورید",
    examplePhonetic: "ghazaye salem bekhorid",
    exampleEnglish: "Eat healthy food",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سرفه",
    phonetic: "sorfe",
    englishTranslation: "Cough",
    exampleFarsi: "سرفه‌ام بند نمی‌آید",
    examplePhonetic: "sorfe-am band nemiyaad",
    exampleEnglish: "My cough won't stop",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سردرد",
    phonetic: "sardard",
    englishTranslation: "Headache",
    exampleFarsi: "سردرد شدیدی دارم",
    examplePhonetic: "sardarde shadidi daram",
    exampleEnglish: "I have a severe headache",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شکم",
    phonetic: "shekam",
    englishTranslation: "Stomach",
    exampleFarsi: "شکمم درد می‌کند",
    examplePhonetic: "shekamam dard mikonad",
    exampleEnglish: "My stomach hurts",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خون",
    phonetic: "khoon",
    englishTranslation: "Blood",
    exampleFarsi: "باید آزمایش خون بدهید",
    examplePhonetic: "bayad azmayeshe khoon bedahid",
    exampleEnglish: "You need to get a blood test",
    difficultyLevel: 3,
  },
  {
    farsiWord: "واکسن",
    phonetic: "vaksan",
    englishTranslation: "Vaccine",
    exampleFarsi: "واکسن آنفولانزا زدم",
    examplePhonetic: "vaksane anfolanza zadam",
    exampleEnglish: "I got the flu vaccine",
    difficultyLevel: 3,
  },
  {
    farsiWord: "حساسیت",
    phonetic: "hasasiyat",
    englishTranslation: "Allergy",
    exampleFarsi: "به گرد و غبار حساسیت دارم",
    examplePhonetic: "be gard o ghobar hasasiyat daram",
    exampleEnglish: "I'm allergic to dust",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ویزیت",
    phonetic: "vizit",
    englishTranslation: "Doctor's visit",
    exampleFarsi: "هزینه ویزیت دکتر چقدر است؟",
    examplePhonetic: "hazineye vizite doktor cheghadr ast?",
    exampleEnglish: "How much is the doctor's visit fee?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سرماخوردگی",
    phonetic: "sarmakhordeji",
    englishTranslation: "Cold (illness)",
    exampleFarsi: "سرماخوردگی بدی گرفته‌ام",
    examplePhonetic: "sarmakhordegiye badi gerefte-am",
    exampleEnglish: "I've caught a bad cold",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بیمارستان",
    phonetic: "bimarestan",
    englishTranslation: "Hospital",
    exampleFarsi: "او را به بیمارستان بردند",
    examplePhonetic: "oo ra be bimarestan bordand",
    exampleEnglish: "They took him to the hospital",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آمبولانس",
    phonetic: "ambolans",
    englishTranslation: "Ambulance",
    exampleFarsi: "آمبولانس خیلی سریع رسید",
    examplePhonetic: "ambolans kheyli sari' resid",
    exampleEnglish: "The ambulance arrived very quickly",
    difficultyLevel: 3,
  },
];

// ─── 7. At the Restaurant ──────────────────────────────────────────────────

const restaurant: WordData[] = [
  {
    farsiWord: "منو",
    phonetic: "menoo",
    englishTranslation: "Menu",
    exampleFarsi: "لطفاً منو را بیاورید",
    examplePhonetic: "lotfan menoo ra biyavarid",
    exampleEnglish: "Please bring the menu",
    difficultyLevel: 3,
  },
  {
    farsiWord: "گارسون",
    phonetic: "garson",
    englishTranslation: "Waiter",
    exampleFarsi: "گارسون، صورتحساب لطفاً",
    examplePhonetic: "garson, soorthesab lotfan",
    exampleEnglish: "Waiter, the bill please",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سفارش",
    phonetic: "sefaresh",
    englishTranslation: "Order",
    exampleFarsi: "سفارش شما چیست؟",
    examplePhonetic: "sefareshe shoma chist?",
    exampleEnglish: "What is your order?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "صورتحساب",
    phonetic: "soorthesab",
    englishTranslation: "Bill",
    exampleFarsi: "صورتحساب را بیاورید لطفاً",
    examplePhonetic: "soorthesab ra biyavarid lotfan",
    exampleEnglish: "Please bring the bill",
    difficultyLevel: 3,
  },
  {
    farsiWord: "انعام",
    phonetic: "enaam",
    englishTranslation: "Tip",
    exampleFarsi: "انعام گارسون را فراموش نکن",
    examplePhonetic: "enaame garson ra faramoosh nakon",
    exampleEnglish: "Don't forget the waiter's tip",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پیش‌غذا",
    phonetic: "pishghaza",
    englishTranslation: "Appetizer",
    exampleFarsi: "برای پیش‌غذا سالاد می‌خواهم",
    examplePhonetic: "baraye pishghaza salad mikhaaham",
    exampleEnglish: "I want salad for the appetizer",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دسر",
    phonetic: "desser",
    englishTranslation: "Dessert",
    exampleFarsi: "دسر امروز بستنی است",
    examplePhonetic: "desere emrooz bastani ast",
    exampleEnglish: "Today's dessert is ice cream",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رزرو",
    phonetic: "rezerv",
    englishTranslation: "Reservation",
    exampleFarsi: "میز رزرو کرده‌ایم",
    examplePhonetic: "miz rezerv karde-im",
    exampleEnglish: "We have made a reservation",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تند",
    phonetic: "tond",
    englishTranslation: "Spicy",
    exampleFarsi: "این غذا خیلی تند است",
    examplePhonetic: "in ghaza kheyli tond ast",
    exampleEnglish: "This food is very spicy",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خوشمزه",
    phonetic: "khoshmazeh",
    englishTranslation: "Delicious",
    exampleFarsi: "غذای این رستوران خیلی خوشمزه است",
    examplePhonetic: "ghazaye in restoran kheyli khoshmazeh ast",
    exampleEnglish: "The food at this restaurant is very delicious",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نوشابه",
    phonetic: "nooshabe",
    englishTranslation: "Soda",
    exampleFarsi: "یک نوشابه سرد می‌خواهم",
    examplePhonetic: "yek nooshabe-ye sard mikhaaham",
    exampleEnglish: "I want a cold soda",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نوش جان",
    phonetic: "nooshe jan",
    englishTranslation: "Bon appetit",
    exampleFarsi: "بفرمایید، نوش جان",
    examplePhonetic: "befarmayid, nooshe jan",
    exampleEnglish: "Here you go, bon appetit",
    difficultyLevel: 3,
  },
];

// ─── 8. Directions & Location ──────────────────────────────────────────────

const directions: WordData[] = [
  {
    farsiWord: "راست",
    phonetic: "rast",
    englishTranslation: "Right",
    exampleFarsi: "سر چهارراه به راست بپیچید",
    examplePhonetic: "sare chaharrah be rast bepichid",
    exampleEnglish: "Turn right at the intersection",
    difficultyLevel: 3,
  },
  {
    farsiWord: "چپ",
    phonetic: "chap",
    englishTranslation: "Left",
    exampleFarsi: "خانه ما سمت چپ خیابان است",
    examplePhonetic: "khane-ye ma samte chape khiyaban ast",
    exampleEnglish: "Our house is on the left side of the street",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مستقیم",
    phonetic: "mostaghim",
    englishTranslation: "Straight",
    exampleFarsi: "مستقیم بروید تا آخر خیابان",
    examplePhonetic: "mostaghim beravid ta akhare khiyaban",
    exampleEnglish: "Go straight to the end of the street",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شمال",
    phonetic: "shomal",
    englishTranslation: "North",
    exampleFarsi: "شمال ایران سبز و زیبا است",
    examplePhonetic: "shomale iran sabz o ziba ast",
    exampleEnglish: "The north of Iran is green and beautiful",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جنوب",
    phonetic: "jonoob",
    englishTranslation: "South",
    exampleFarsi: "جنوب ایران هوای گرمی دارد",
    examplePhonetic: "jonoobe iran havaye garmi darad",
    exampleEnglish: "The south of Iran has a hot climate",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شرق",
    phonetic: "shargh",
    englishTranslation: "East",
    exampleFarsi: "خورشید از شرق طلوع می‌کند",
    examplePhonetic: "khorshid az shargh toloo' mikonad",
    exampleEnglish: "The sun rises from the east",
    difficultyLevel: 3,
  },
  {
    farsiWord: "غرب",
    phonetic: "gharb",
    englishTranslation: "West",
    exampleFarsi: "خورشید در غرب غروب می‌کند",
    examplePhonetic: "khorshid dar gharb ghoroob mikonad",
    exampleEnglish: "The sun sets in the west",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نزدیک",
    phonetic: "nazdik",
    englishTranslation: "Near",
    exampleFarsi: "مدرسه نزدیک خانه ماست",
    examplePhonetic: "madrese nazdike khaane-ye mast",
    exampleEnglish: "The school is near our house",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دور",
    phonetic: "door",
    englishTranslation: "Far",
    exampleFarsi: "فرودگاه از اینجا خیلی دور است",
    examplePhonetic: "foroodgah az inja kheyli door ast",
    exampleEnglish: "The airport is very far from here",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آدرس",
    phonetic: "adres",
    englishTranslation: "Address",
    exampleFarsi: "آدرس رستوران را داری؟",
    examplePhonetic: "adrese restoran ra dari?",
    exampleEnglish: "Do you have the restaurant's address?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پیچیدن",
    phonetic: "pichidan",
    englishTranslation: "To turn",
    exampleFarsi: "بعد از پل به چپ بپیچید",
    examplePhonetic: "ba'd az pol be chap bepichid",
    exampleEnglish: "Turn left after the bridge",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مسیر",
    phonetic: "masir",
    englishTranslation: "Route/Path",
    exampleFarsi: "بهترین مسیر کدام است؟",
    examplePhonetic: "behtarin masir kodam ast?",
    exampleEnglish: "What is the best route?",
    difficultyLevel: 3,
  },
];

// ─── 9. Nature & Environment ───────────────────────────────────────────────

const nature: WordData[] = [
  {
    farsiWord: "کوه",
    phonetic: "kooh",
    englishTranslation: "Mountain",
    exampleFarsi: "آخر هفته به کوه رفتیم",
    examplePhonetic: "akhare hafte be kooh raftim",
    exampleEnglish: "We went to the mountains on the weekend",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دریا",
    phonetic: "darya",
    englishTranslation: "Sea",
    exampleFarsi: "آب دریا خیلی شور است",
    examplePhonetic: "abe darya kheyli shoor ast",
    exampleEnglish: "The sea water is very salty",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رودخانه",
    phonetic: "roodkhaneh",
    englishTranslation: "River",
    exampleFarsi: "کنار رودخانه نشستیم",
    examplePhonetic: "kenare roodkhaneh neshastim",
    exampleEnglish: "We sat by the river",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جنگل",
    phonetic: "jangal",
    englishTranslation: "Forest",
    exampleFarsi: "جنگل‌های شمال ایران بسیار زیبا هستند",
    examplePhonetic: "jangalhaye shomale iran besyar ziba hastand",
    exampleEnglish: "The forests of northern Iran are very beautiful",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کویر",
    phonetic: "kavir",
    englishTranslation: "Desert",
    exampleFarsi: "شب‌ها در کویر ستاره‌ها واضح هستند",
    examplePhonetic: "shab-ha dar kavir setare-ha vazeh hastand",
    exampleEnglish: "At night the stars are clear in the desert",
    difficultyLevel: 3,
  },
  {
    farsiWord: "درخت",
    phonetic: "derakht",
    englishTranslation: "Tree",
    exampleFarsi: "زیر درخت نشستیم",
    examplePhonetic: "zire derakht neshastim",
    exampleEnglish: "We sat under the tree",
    difficultyLevel: 3,
  },
  {
    farsiWord: "گل",
    phonetic: "gol",
    englishTranslation: "Flower",
    exampleFarsi: "این گل‌ها خیلی خوشبو هستند",
    examplePhonetic: "in golha kheyli khoshboo hastand",
    exampleEnglish: "These flowers are very fragrant",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آسمان",
    phonetic: "aseman",
    englishTranslation: "Sky",
    exampleFarsi: "آسمان امشب صاف است",
    examplePhonetic: "asemane emshab saf ast",
    exampleEnglish: "The sky is clear tonight",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خورشید",
    phonetic: "khorshid",
    englishTranslation: "Sun",
    exampleFarsi: "خورشید داره غروب می‌کنه",
    examplePhonetic: "khorshid dare ghoroob mikone",
    exampleEnglish: "The sun is setting",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ستاره",
    phonetic: "setareh",
    englishTranslation: "Star",
    exampleFarsi: "ستاره‌ها در آسمان می‌درخشند",
    examplePhonetic: "setare-ha dar aseman miderakhshand",
    exampleEnglish: "The stars are shining in the sky",
    difficultyLevel: 3,
  },
  {
    farsiWord: "باران",
    phonetic: "baran",
    englishTranslation: "Rain",
    exampleFarsi: "باران شدیدی می‌بارد",
    examplePhonetic: "barane shadidi mibarad",
    exampleEnglish: "It is raining heavily",
    difficultyLevel: 3,
  },
  {
    farsiWord: "برف",
    phonetic: "barf",
    englishTranslation: "Snow",
    exampleFarsi: "زمستان برف زیادی می‌بارد",
    examplePhonetic: "zemestan barfe ziyadi mibarad",
    exampleEnglish: "In winter it snows a lot",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دریاچه",
    phonetic: "daryacheh",
    englishTranslation: "Lake",
    exampleFarsi: "دریاچه ارومیه در شمال غرب ایران است",
    examplePhonetic: "daryache-ye orumiyeh dar shomale gharbe iran ast",
    exampleEnglish: "Lake Urmia is in northwestern Iran",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جزیره",
    phonetic: "jazireh",
    englishTranslation: "Island",
    exampleFarsi: "کیش یک جزیره زیبا در جنوب ایران است",
    examplePhonetic: "kish yek jazire-ye ziba dar jonoobe iran ast",
    exampleEnglish: "Kish is a beautiful island in southern Iran",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ساحل",
    phonetic: "sahel",
    englishTranslation: "Beach",
    exampleFarsi: "روی ساحل قدم زدیم",
    examplePhonetic: "rooye sahel ghadam zadim",
    exampleEnglish: "We walked on the beach",
    difficultyLevel: 3,
  },
];

// ─── 10. Technology ────────────────────────────────────────────────────────

const technology: WordData[] = [
  {
    farsiWord: "کامپیوتر",
    phonetic: "kampyooter",
    englishTranslation: "Computer",
    exampleFarsi: "کامپیوترم خراب شده",
    examplePhonetic: "kampyooteram kharab shode",
    exampleEnglish: "My computer is broken",
    difficultyLevel: 3,
  },
  {
    farsiWord: "اینترنت",
    phonetic: "internet",
    englishTranslation: "Internet",
    exampleFarsi: "اینترنت امروز خیلی کند است",
    examplePhonetic: "internet emrooz kheyli kond ast",
    exampleEnglish: "The internet is very slow today",
    difficultyLevel: 3,
  },
  {
    farsiWord: "وب‌سایت",
    phonetic: "sayt",
    englishTranslation: "Website",
    exampleFarsi: "وب‌سایت جدیدی طراحی کردیم",
    examplePhonetic: "sayte jadidi tarahi kardim",
    exampleEnglish: "We designed a new website",
    difficultyLevel: 3,
  },
  {
    farsiWord: "برنامه",
    phonetic: "barnaameh",
    englishTranslation: "App/Program",
    exampleFarsi: "این برنامه خیلی مفید است",
    examplePhonetic: "in barnaameh kheyli mofid ast",
    exampleEnglish: "This app is very useful",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پیام",
    phonetic: "peyam",
    englishTranslation: "Message",
    exampleFarsi: "یک پیام برایت فرستادم",
    examplePhonetic: "yek peyam barayat ferestaadam",
    exampleEnglish: "I sent you a message",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عکس",
    phonetic: "aks",
    englishTranslation: "Photo",
    exampleFarsi: "از منظره عکس گرفتم",
    examplePhonetic: "az manzareh aks gereftam",
    exampleEnglish: "I took a photo of the scenery",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دوربین",
    phonetic: "dorbin",
    englishTranslation: "Camera",
    exampleFarsi: "دوربین جدید خریدم",
    examplePhonetic: "dorbine jadid kharidam",
    exampleEnglish: "I bought a new camera",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رمز",
    phonetic: "ramz",
    englishTranslation: "Password",
    exampleFarsi: "رمز عبورت را عوض کن",
    examplePhonetic: "ramze oboret ra avaz kon",
    exampleEnglish: "Change your password",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دانلود",
    phonetic: "danelood",
    englishTranslation: "Download",
    exampleFarsi: "این فیلم را دانلود کردم",
    examplePhonetic: "in film ra danelood kardam",
    exampleEnglish: "I downloaded this movie",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جستجو کردن",
    phonetic: "jostejoo kardan",
    englishTranslation: "To search",
    exampleFarsi: "در گوگل جستجو کن",
    examplePhonetic: "dar google jostejoo kon",
    exampleEnglish: "Search on Google",
    difficultyLevel: 3,
  },
  {
    farsiWord: "چاپ کردن",
    phonetic: "chap kardan",
    englishTranslation: "To print",
    exampleFarsi: "این سند را چاپ کن",
    examplePhonetic: "in sanad ra chap kon",
    exampleEnglish: "Print this document",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سخت‌افزار",
    phonetic: "sakht-afzar",
    englishTranslation: "Hardware",
    exampleFarsi: "مشکل سخت‌افزاری دارد",
    examplePhonetic: "moshkele sakht-afzari darad",
    exampleEnglish: "It has a hardware problem",
    difficultyLevel: 3,
  },
];

// ─── 11. Sports & Hobbies ──────────────────────────────────────────────────

const sportsHobbies: WordData[] = [
  {
    farsiWord: "فوتبال",
    phonetic: "footbal",
    englishTranslation: "Football/Soccer",
    exampleFarsi: "فوتبال محبوب‌ترین ورزش در ایران است",
    examplePhonetic: "footbal mahboobtarin varzesh dar iran ast",
    exampleEnglish: "Football is the most popular sport in Iran",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شنا",
    phonetic: "shena",
    englishTranslation: "Swimming",
    exampleFarsi: "تابستان‌ها شنا می‌کنیم",
    examplePhonetic: "tabestanha shena mikonim",
    exampleEnglish: "We swim in the summers",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دویدن",
    phonetic: "davidan",
    englishTranslation: "Running",
    exampleFarsi: "هر صبح در پارک می‌دوم",
    examplePhonetic: "har sobh dar park midavam",
    exampleEnglish: "I run in the park every morning",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بسکتبال",
    phonetic: "basketbal",
    englishTranslation: "Basketball",
    exampleFarsi: "بسکتبال ورزش مورد علاقه من است",
    examplePhonetic: "basketbal varzeshe mored-e alaghe-ye man ast",
    exampleEnglish: "Basketball is my favorite sport",
    difficultyLevel: 3,
  },
  {
    farsiWord: "باشگاه",
    phonetic: "baashgah",
    englishTranslation: "Gym/Club",
    exampleFarsi: "هر روز به باشگاه می‌روم",
    examplePhonetic: "har rooz be baashgah miravam",
    exampleEnglish: "I go to the gym every day",
    difficultyLevel: 3,
  },
  {
    farsiWord: "موسیقی",
    phonetic: "moosighi",
    englishTranslation: "Music",
    exampleFarsi: "موسیقی ایرانی خیلی دوست دارم",
    examplePhonetic: "moosighiye irani kheyli doost daram",
    exampleEnglish: "I really like Iranian music",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نقاشی",
    phonetic: "naghashi",
    englishTranslation: "Painting",
    exampleFarsi: "نقاشی سرگرمی من است",
    examplePhonetic: "naghashi sargarmi-ye man ast",
    exampleEnglish: "Painting is my hobby",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آشپزی",
    phonetic: "ashpazi",
    englishTranslation: "Cooking (hobby)",
    exampleFarsi: "آشپزی را از مادرم یاد گرفتم",
    examplePhonetic: "ashpazi ra az madaram yad gereftam",
    exampleEnglish: "I learned cooking from my mother",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رقص",
    phonetic: "raghs",
    englishTranslation: "Dance",
    exampleFarsi: "رقص ایرانی خیلی زیباست",
    examplePhonetic: "raghse irani kheyli zibast",
    exampleEnglish: "Iranian dance is very beautiful",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شطرنج",
    phonetic: "shatranj",
    englishTranslation: "Chess",
    exampleFarsi: "شطرنج بازی فکری خوبی است",
    examplePhonetic: "shatranj baziye fekri-ye khoobi ast",
    exampleEnglish: "Chess is a good intellectual game",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بازی کردن",
    phonetic: "bazi kardan",
    englishTranslation: "To play",
    exampleFarsi: "بچه‌ها در حیاط بازی می‌کنند",
    examplePhonetic: "bache-ha dar hayat bazi mikonand",
    exampleEnglish: "The children are playing in the yard",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بازی",
    phonetic: "bazi",
    englishTranslation: "Game",
    exampleFarsi: "این بازی خیلی جالب است",
    examplePhonetic: "in bazi kheyli jaleb ast",
    exampleEnglish: "This game is very interesting",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کوهنوردی",
    phonetic: "kooh-navardi",
    englishTranslation: "Hiking",
    exampleFarsi: "جمعه‌ها کوهنوردی می‌رویم",
    examplePhonetic: "jom'e-ha kooh-navardi miravim",
    exampleEnglish: "We go hiking on Fridays",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دوچرخه‌سواری",
    phonetic: "docharkhe-savari",
    englishTranslation: "Cycling",
    exampleFarsi: "دوچرخه‌سواری ورزش خوبی است",
    examplePhonetic: "docharkhe-savari varzeshe khoobi ast",
    exampleEnglish: "Cycling is a good sport",
    difficultyLevel: 3,
  },
  {
    farsiWord: "یوگا",
    phonetic: "yoga",
    englishTranslation: "Yoga",
    exampleFarsi: "یوگا برای آرامش خیلی خوب است",
    examplePhonetic: "yoga baraye aramesh kheyli khoob ast",
    exampleEnglish: "Yoga is very good for relaxation",
    difficultyLevel: 3,
  },
];

// ─── 12. Office & Work ─────────────────────────────────────────────────────

const officeWork: WordData[] = [
  {
    farsiWord: "دفتر کار",
    phonetic: "daftar-e kar",
    englishTranslation: "Office",
    exampleFarsi: "دفتر کار من در طبقه سوم است",
    examplePhonetic: "daftare kare man dar tabaghe-ye sevom ast",
    exampleEnglish: "My office is on the third floor",
    difficultyLevel: 3,
  },
  {
    farsiWord: "جلسه",
    phonetic: "jalase",
    englishTranslation: "Meeting",
    exampleFarsi: "ساعت ده جلسه داریم",
    examplePhonetic: "sa'ate dah jalase darim",
    exampleEnglish: "We have a meeting at ten",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رئیس",
    phonetic: "ra'is",
    englishTranslation: "Boss",
    exampleFarsi: "رئیسم خیلی سخت‌گیر است",
    examplePhonetic: "ra'isam kheyli sakht-gir ast",
    exampleEnglish: "My boss is very strict",
    difficultyLevel: 3,
  },
  {
    farsiWord: "همکار",
    phonetic: "hamkar",
    englishTranslation: "Colleague",
    exampleFarsi: "همکارم خیلی مهربان است",
    examplePhonetic: "hamkaram kheyli mehraban ast",
    exampleEnglish: "My colleague is very kind",
    difficultyLevel: 3,
  },
  {
    farsiWord: "حقوق",
    phonetic: "hoghogh",
    englishTranslation: "Salary",
    exampleFarsi: "حقوقم را آخر ماه می‌گیرم",
    examplePhonetic: "hoghogham ra akhare mah migiram",
    exampleEnglish: "I get my salary at the end of the month",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پروژه",
    phonetic: "porozhe",
    englishTranslation: "Project",
    exampleFarsi: "این پروژه خیلی مهم است",
    examplePhonetic: "in porozhe kheyli mohem ast",
    exampleEnglish: "This project is very important",
    difficultyLevel: 3,
  },
  {
    farsiWord: "گزارش",
    phonetic: "gozaresh",
    englishTranslation: "Report",
    exampleFarsi: "گزارش ماهانه را آماده کردم",
    examplePhonetic: "gozareshe mahane ra amade kardam",
    exampleEnglish: "I prepared the monthly report",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مهلت",
    phonetic: "mohlat",
    englishTranslation: "Deadline",
    exampleFarsi: "مهلت تحویل پروژه فرداست",
    examplePhonetic: "mohlate tahvile porozhe fardast",
    exampleEnglish: "The project deadline is tomorrow",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مصاحبه",
    phonetic: "mosahebe",
    englishTranslation: "Interview",
    exampleFarsi: "فردا مصاحبه کاری دارم",
    examplePhonetic: "farda mosahebe-ye kari daram",
    exampleEnglish: "I have a job interview tomorrow",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رزومه",
    phonetic: "razome",
    englishTranslation: "Resume",
    exampleFarsi: "رزومه‌ام را به‌روز کردم",
    examplePhonetic: "razome-am ra be-rooz kardam",
    exampleEnglish: "I updated my resume",
    difficultyLevel: 3,
  },
  {
    farsiWord: "استخدام کردن",
    phonetic: "estekhdaam kardan",
    englishTranslation: "To hire",
    exampleFarsi: "شرکت ده نفر جدید استخدام کرد",
    examplePhonetic: "sherkat dah nafar-e jadid estekhdaam kard",
    exampleEnglish: "The company hired ten new people",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شرکت",
    phonetic: "sherkat",
    englishTranslation: "Company",
    exampleFarsi: "شرکت ما صد کارمند دارد",
    examplePhonetic: "sherkate ma sad karmand darad",
    exampleEnglish: "Our company has one hundred employees",
    difficultyLevel: 3,
  },
];

// ─── 13. Opinions & Discussion ─────────────────────────────────────────────

const opinions: WordData[] = [
  {
    farsiWord: "فکر می‌کنم",
    phonetic: "fekr mikonam",
    englishTranslation: "I think",
    exampleFarsi: "فکر می‌کنم این کار درست نیست",
    examplePhonetic: "fekr mikonam in kar dorost nist",
    exampleEnglish: "I think this is not right",
    difficultyLevel: 3,
  },
  {
    farsiWord: "موافقم",
    phonetic: "movafegham",
    englishTranslation: "I agree",
    exampleFarsi: "کاملاً با شما موافقم",
    examplePhonetic: "kamelan ba shoma movafegham",
    exampleEnglish: "I completely agree with you",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مخالفم",
    phonetic: "mokhalefam",
    englishTranslation: "I disagree",
    exampleFarsi: "با این نظر مخالفم",
    examplePhonetic: "ba in nazar mokhalefam",
    exampleEnglish: "I disagree with this opinion",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نظر",
    phonetic: "nazar",
    englishTranslation: "Opinion",
    exampleFarsi: "نظر شما در این مورد چیست؟",
    examplePhonetic: "nazare shoma dar in mored chist?",
    exampleEnglish: "What is your opinion on this matter?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مهم",
    phonetic: "mohem",
    englishTranslation: "Important",
    exampleFarsi: "این موضوع خیلی مهم است",
    examplePhonetic: "in mozoo' kheyli mohem ast",
    exampleEnglish: "This topic is very important",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شاید",
    phonetic: "shayad",
    englishTranslation: "Maybe",
    exampleFarsi: "شاید فردا باران ببارد",
    examplePhonetic: "shayad farda baran bebarad",
    exampleEnglish: "Maybe it will rain tomorrow",
    difficultyLevel: 3,
  },
  {
    farsiWord: "حتماً",
    phonetic: "hatman",
    englishTranslation: "Certainly",
    exampleFarsi: "حتماً به جلسه می‌آیم",
    examplePhonetic: "hatman be jalase miyayam",
    exampleEnglish: "I will certainly come to the meeting",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دلیل",
    phonetic: "dalil",
    englishTranslation: "Reason",
    exampleFarsi: "دلیل تأخیرت چه بود؟",
    examplePhonetic: "dalile ta'khiret che bood?",
    exampleEnglish: "What was the reason for your delay?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "مثال",
    phonetic: "mesal",
    englishTranslation: "Example",
    exampleFarsi: "می‌توانید یک مثال بزنید؟",
    examplePhonetic: "mitavanid yek mesal bezanid?",
    exampleEnglish: "Can you give an example?",
    difficultyLevel: 3,
  },
  {
    farsiWord: "احتمالاً",
    phonetic: "ehtemaalan",
    englishTranslation: "Probably",
    exampleFarsi: "احتمالاً دیر می‌رسم",
    examplePhonetic: "ehtemaalan dir miresam",
    exampleEnglish: "I will probably arrive late",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پیشنهاد",
    phonetic: "pishnahad",
    englishTranslation: "Suggestion",
    exampleFarsi: "پیشنهاد خوبی دارم",
    examplePhonetic: "pishnahade khoobi daram",
    exampleEnglish: "I have a good suggestion",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نتیجه",
    phonetic: "natijeh",
    englishTranslation: "Result",
    exampleFarsi: "نتیجه امتحان‌ها اعلام شد",
    examplePhonetic: "natijeh-ye emtehanha e'lam shod",
    exampleEnglish: "The exam results were announced",
    difficultyLevel: 3,
  },
];

// ─── 14. Time Expressions ──────────────────────────────────────────────────

const timeExpressions: WordData[] = [
  {
    farsiWord: "صبح",
    phonetic: "sobh",
    englishTranslation: "Morning",
    exampleFarsi: "صبح زود بیدار شدم",
    examplePhonetic: "sobhe zood bidaar shodam",
    exampleEnglish: "I woke up early in the morning",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بعد از ظهر",
    phonetic: "ba'd az zohr",
    englishTranslation: "Afternoon",
    exampleFarsi: "بعد از ظهر به کتابخانه می‌روم",
    examplePhonetic: "ba'd az zohr be ketabkhaneh miravam",
    exampleEnglish: "I go to the library in the afternoon",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عصر",
    phonetic: "asr",
    englishTranslation: "Evening",
    exampleFarsi: "عصرها در پارک قدم می‌زنم",
    examplePhonetic: "asrha dar park ghadam mizanam",
    exampleEnglish: "I walk in the park in the evenings",
    difficultyLevel: 3,
  },
  {
    farsiWord: "نیمه شب",
    phonetic: "nime shab",
    englishTranslation: "Midnight",
    exampleFarsi: "نیمه شب صدای عجیبی شنیدم",
    examplePhonetic: "nime shab sedaye ajibi shenidam",
    exampleEnglish: "I heard a strange sound at midnight",
    difficultyLevel: 3,
  },
  {
    farsiWord: "زود",
    phonetic: "zood",
    englishTranslation: "Early",
    exampleFarsi: "خیلی زود رسیدی",
    examplePhonetic: "kheyli zood residi",
    exampleEnglish: "You arrived very early",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دیر",
    phonetic: "dir",
    englishTranslation: "Late",
    exampleFarsi: "ببخشید که دیر رسیدم",
    examplePhonetic: "bebakhshid ke dir residam",
    exampleEnglish: "Sorry I arrived late",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بعضی وقت‌ها",
    phonetic: "ba'zi vaght-ha",
    englishTranslation: "Sometimes",
    exampleFarsi: "بعضی وقت‌ها دلم تنگ می‌شود",
    examplePhonetic: "ba'zi vaght-ha delam tang mishavad",
    exampleEnglish: "Sometimes I feel homesick",
    difficultyLevel: 3,
  },
  {
    farsiWord: "معمولاً",
    phonetic: "mamoolan",
    englishTranslation: "Usually",
    exampleFarsi: "معمولاً ساعت هفت بیدار می‌شوم",
    examplePhonetic: "mamoolan sa'ate haft bidaar mishavam",
    exampleEnglish: "I usually wake up at seven",
    difficultyLevel: 3,
  },
  {
    farsiWord: "به ندرت",
    phonetic: "be nodrat",
    englishTranslation: "Rarely",
    exampleFarsi: "به ندرت رستوران می‌روم",
    examplePhonetic: "be nodrat restoran miravam",
    exampleEnglish: "I rarely go to restaurants",
    difficultyLevel: 3,
  },
  {
    farsiWord: "قبلاً",
    phonetic: "ghablan",
    englishTranslation: "Already/Before",
    exampleFarsi: "قبلاً این فیلم را دیده‌ام",
    examplePhonetic: "ghablan in film ra dide-am",
    exampleEnglish: "I have already seen this movie",
    difficultyLevel: 3,
  },
  {
    farsiWord: "به زودی",
    phonetic: "be zoodi",
    englishTranslation: "Soon",
    exampleFarsi: "به زودی می‌بینمت",
    examplePhonetic: "be zoodi mibinamet",
    exampleEnglish: "I will see you soon",
    difficultyLevel: 3,
  },
  {
    farsiWord: "در طول",
    phonetic: "dar tool-e",
    englishTranslation: "During",
    exampleFarsi: "در طول تابستان سفر کردیم",
    examplePhonetic: "dar toole tabestan safar kardim",
    exampleEnglish: "We traveled during the summer",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تا",
    phonetic: "ta",
    englishTranslation: "Until",
    exampleFarsi: "تا ساعت پنج کار می‌کنم",
    examplePhonetic: "ta sa'ate panj kar mikonam",
    exampleEnglish: "I work until five o'clock",
    difficultyLevel: 3,
  },
  {
    farsiWord: "از وقتی که",
    phonetic: "az vaghti ke",
    englishTranslation: "Since",
    exampleFarsi: "از وقتی که آمده‌ام، خیلی یاد گرفته‌ام",
    examplePhonetic: "az vaghti ke amade-am, kheyli yad gerefte-am",
    exampleEnglish: "Since I came, I have learned a lot",
    difficultyLevel: 3,
  },
  {
    farsiWord: "اکثر اوقات",
    phonetic: "aksare oghaat",
    englishTranslation: "Most of the time",
    exampleFarsi: "اکثر اوقات در خانه هستم",
    examplePhonetic: "aksare oghaat dar khaneh hastam",
    exampleEnglish: "Most of the time I am at home",
    difficultyLevel: 3,
  },
];

// ─── 15. Verbs of Motion ───────────────────────────────────────────────────

const verbsMotion: WordData[] = [
  {
    farsiWord: "حرکت کردن",
    phonetic: "harekat kardan",
    englishTranslation: "To move",
    exampleFarsi: "قطار شروع به حرکت کرد",
    examplePhonetic: "ghatar shoroo' be harekat kard",
    exampleEnglish: "The train started to move",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رسیدن",
    phonetic: "residan",
    englishTranslation: "To arrive",
    exampleFarsi: "ساعت سه به تهران رسیدیم",
    examplePhonetic: "sa'ate se be tehran residim",
    exampleEnglish: "We arrived in Tehran at three o'clock",
    difficultyLevel: 3,
  },
  {
    farsiWord: "وارد شدن",
    phonetic: "vared shodan",
    englishTranslation: "To enter",
    exampleFarsi: "لطفاً وارد اتاق شوید",
    examplePhonetic: "lotfan varede otagh shavid",
    exampleEnglish: "Please enter the room",
    difficultyLevel: 3,
  },
  {
    farsiWord: "خارج شدن",
    phonetic: "kharej shodan",
    englishTranslation: "To exit",
    exampleFarsi: "از ساختمان خارج شدیم",
    examplePhonetic: "az sakhteman kharej shodim",
    exampleEnglish: "We exited the building",
    difficultyLevel: 3,
  },
  {
    farsiWord: "بالا رفتن",
    phonetic: "bala raftan",
    englishTranslation: "To go up/climb",
    exampleFarsi: "از پله‌ها بالا رفتیم",
    examplePhonetic: "az pele-ha bala raftim",
    exampleEnglish: "We went up the stairs",
    difficultyLevel: 3,
  },
  {
    farsiWord: "افتادن",
    phonetic: "oftadan",
    englishTranslation: "To fall",
    exampleFarsi: "برگ‌ها از درخت افتادند",
    examplePhonetic: "barg-ha az derakht oftaadand",
    exampleEnglish: "The leaves fell from the tree",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پرواز کردن",
    phonetic: "parvaz kardan",
    englishTranslation: "To fly",
    exampleFarsi: "پرنده‌ها در آسمان پرواز می‌کنند",
    examplePhonetic: "parande-ha dar aseman parvaz mikonand",
    exampleEnglish: "The birds are flying in the sky",
    difficultyLevel: 3,
  },
  {
    farsiWord: "شنا کردن",
    phonetic: "shena kardan",
    englishTranslation: "To swim",
    exampleFarsi: "در دریا شنا کردیم",
    examplePhonetic: "dar darya shena kardim",
    exampleEnglish: "We swam in the sea",
    difficultyLevel: 3,
  },
  {
    farsiWord: "رانندگی کردن",
    phonetic: "ranandegi kardan",
    englishTranslation: "To drive",
    exampleFarsi: "تا شیراز رانندگی کردیم",
    examplePhonetic: "ta shiraz ranandegi kardim",
    exampleEnglish: "We drove all the way to Shiraz",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پریدن",
    phonetic: "paridan",
    englishTranslation: "To jump",
    exampleFarsi: "بچه‌ها از روی دیوار پریدند",
    examplePhonetic: "bache-ha az rooye divar paridand",
    exampleEnglish: "The children jumped over the wall",
    difficultyLevel: 3,
  },
  {
    farsiWord: "هل دادن",
    phonetic: "hol dadan",
    englishTranslation: "To push",
    exampleFarsi: "در را هل بده",
    examplePhonetic: "dar ra hol bede",
    exampleEnglish: "Push the door",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کشیدن",
    phonetic: "keshidan",
    englishTranslation: "To pull",
    exampleFarsi: "در را به سمت خودت بکش",
    examplePhonetic: "dar ra be samte khodet bekesh",
    exampleEnglish: "Pull the door towards yourself",
    difficultyLevel: 3,
  },
  {
    farsiWord: "حمل کردن",
    phonetic: "haml kardan",
    englishTranslation: "To carry",
    exampleFarsi: "این جعبه را حمل کن",
    examplePhonetic: "in ja'be ra haml kon",
    exampleEnglish: "Carry this box",
    difficultyLevel: 3,
  },
  {
    farsiWord: "پرتاب کردن",
    phonetic: "partab kardan",
    englishTranslation: "To throw",
    exampleFarsi: "توپ را به سمت من پرتاب کن",
    examplePhonetic: "toop ra be samte man partab kon",
    exampleEnglish: "Throw the ball towards me",
    difficultyLevel: 3,
  },
  {
    farsiWord: "دویدن",
    phonetic: "davidan",
    englishTranslation: "To run",
    exampleFarsi: "سریع دوید تا به اتوبوس برسد",
    examplePhonetic: "sari' david ta be otobus beresad",
    exampleEnglish: "He ran fast to catch the bus",
    difficultyLevel: 3,
  },
];

// ─── 16. Descriptive Adjectives ────────────────────────────────────────────

const descriptiveAdjectives: WordData[] = [
  {
    farsiWord: "قدبلند",
    phonetic: "ghad-boland",
    englishTranslation: "Tall",
    exampleFarsi: "برادرم خیلی قدبلند است",
    examplePhonetic: "baradaram kheyli ghad-boland ast",
    exampleEnglish: "My brother is very tall",
    difficultyLevel: 3,
  },
  {
    farsiWord: "لاغر",
    phonetic: "laghar",
    englishTranslation: "Thin",
    exampleFarsi: "او خیلی لاغر شده است",
    examplePhonetic: "oo kheyli laghar shode ast",
    exampleEnglish: "He has become very thin",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سنگین",
    phonetic: "sangin",
    englishTranslation: "Heavy",
    exampleFarsi: "این کیف خیلی سنگین است",
    examplePhonetic: "in kif kheyli sangin ast",
    exampleEnglish: "This bag is very heavy",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سبک",
    phonetic: "sabok",
    englishTranslation: "Light (weight)",
    exampleFarsi: "این جعبه سبک است",
    examplePhonetic: "in ja'be sabok ast",
    exampleEnglish: "This box is light",
    difficultyLevel: 3,
  },
  {
    farsiWord: "قوی",
    phonetic: "ghavi",
    englishTranslation: "Strong",
    exampleFarsi: "او ورزشکار قوی است",
    examplePhonetic: "oo varzeshkare ghavi ast",
    exampleEnglish: "He is a strong athlete",
    difficultyLevel: 3,
  },
  {
    farsiWord: "ضعیف",
    phonetic: "za'if",
    englishTranslation: "Weak",
    exampleFarsi: "بعد از بیماری خیلی ضعیف شدم",
    examplePhonetic: "ba'd az bimari kheyli za'if shodam",
    exampleEnglish: "I became very weak after the illness",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تمیز",
    phonetic: "tamiz",
    englishTranslation: "Clean",
    exampleFarsi: "اتاقت را تمیز کن",
    examplePhonetic: "otaghet ra tamiz kon",
    exampleEnglish: "Clean your room",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کثیف",
    phonetic: "kasif",
    englishTranslation: "Dirty",
    exampleFarsi: "لباس‌هایت کثیف شده‌اند",
    examplePhonetic: "lebashayat kasif shode-and",
    exampleEnglish: "Your clothes have gotten dirty",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آسان",
    phonetic: "asan",
    englishTranslation: "Easy",
    exampleFarsi: "این سؤال خیلی آسان بود",
    examplePhonetic: "in so'al kheyli asan bood",
    exampleEnglish: "This question was very easy",
    difficultyLevel: 3,
  },
  {
    farsiWord: "سخت",
    phonetic: "sakht",
    englishTranslation: "Difficult",
    exampleFarsi: "امتحان ریاضی خیلی سخت بود",
    examplePhonetic: "emtehane riazi kheyli sakht bood",
    exampleEnglish: "The math exam was very difficult",
    difficultyLevel: 3,
  },
  {
    farsiWord: "آرام",
    phonetic: "aram",
    englishTranslation: "Quiet",
    exampleFarsi: "لطفاً آرام باشید",
    examplePhonetic: "lotfan aram bashid",
    exampleEnglish: "Please be quiet",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تند",
    phonetic: "tond",
    englishTranslation: "Fast/Spicy",
    exampleFarsi: "اینقدر تند رانندگی نکن",
    examplePhonetic: "inghadr tond ranandegi nakon",
    exampleEnglish: "Don't drive so fast",
    difficultyLevel: 3,
  },
  {
    farsiWord: "تازه",
    phonetic: "taze",
    englishTranslation: "Fresh",
    exampleFarsi: "نان تازه خریدم",
    examplePhonetic: "nane taze kharidam",
    exampleEnglish: "I bought fresh bread",
    difficultyLevel: 3,
  },
  {
    farsiWord: "کهنه",
    phonetic: "kohneh",
    englishTranslation: "Worn out/Old",
    exampleFarsi: "این کفش‌ها خیلی کهنه شده‌اند",
    examplePhonetic: "in kafsh-ha kheyli kohneh shode-and",
    exampleEnglish: "These shoes have become very worn out",
    difficultyLevel: 3,
  },
  {
    farsiWord: "عجیب",
    phonetic: "ajib",
    englishTranslation: "Strange",
    exampleFarsi: "صدای عجیبی از بیرون می‌آمد",
    examplePhonetic: "sedaye ajibi az biroon miyamad",
    exampleEnglish: "A strange sound was coming from outside",
    difficultyLevel: 3,
  },
];

// ─── Export: seedLevel3 ────────────────────────────────────────────────────

export async function seedLevel3() {
  console.log("\n=== Level 3: Pre-Intermediate ===\n");
  let total = 0;

  const r1 = await seedCategory({
    name: "Countries & Travel",
    slug: "countries-travel",
    description: "Country names and essential travel vocabulary",
    icon: "✈️",
    level: 3,
    sortOrder: 1,
    words: countriesTravel,
  });
  total += r1.wordsAdded;

  const r2 = await seedCategory({
    name: "Phrasal Verbs Part 1",
    slug: "phrasal-verbs",
    description: "Common compound verbs with kardan and gereftan",
    icon: "🔀",
    level: 3,
    sortOrder: 2,
    words: phrasalVerbs,
  });
  total += r2.wordsAdded;

  const r3 = await seedCategory({
    name: "Phrasal Verbs Part 2",
    slug: "phrasal-verbs-2",
    description: "Compound verbs with shodan for states and changes",
    icon: "🔀",
    level: 3,
    sortOrder: 3,
    words: phrasalVerbs2,
  });
  total += r3.wordsAdded;

  const r4 = await seedCategory({
    name: "Abstract Concepts",
    slug: "abstract",
    description: "Abstract nouns for emotions, ideas, and values",
    icon: "💭",
    level: 3,
    sortOrder: 4,
    words: abstractConcepts,
  });
  total += r4.wordsAdded;

  const r5 = await seedCategory({
    name: "Education & Learning",
    slug: "education",
    description: "Academic and school-related vocabulary",
    icon: "📚",
    level: 3,
    sortOrder: 5,
    words: education,
  });
  total += r5.wordsAdded;

  const r6 = await seedCategory({
    name: "Health & Body",
    slug: "health",
    description: "Health, illness, and medical vocabulary",
    icon: "🏥",
    level: 3,
    sortOrder: 6,
    words: health,
  });
  total += r6.wordsAdded;

  const r7 = await seedCategory({
    name: "At the Restaurant",
    slug: "restaurant",
    description: "Restaurant dining and food ordering vocabulary",
    icon: "🍽️",
    level: 3,
    sortOrder: 7,
    words: restaurant,
  });
  total += r7.wordsAdded;

  const r8 = await seedCategory({
    name: "Directions & Location",
    slug: "directions",
    description: "Directional terms and location vocabulary",
    icon: "🧭",
    level: 3,
    sortOrder: 8,
    words: directions,
  });
  total += r8.wordsAdded;

  const r9 = await seedCategory({
    name: "Nature & Environment",
    slug: "nature",
    description: "Natural features, weather, and environment",
    icon: "🌿",
    level: 3,
    sortOrder: 9,
    words: nature,
  });
  total += r9.wordsAdded;

  const r10 = await seedCategory({
    name: "Technology",
    slug: "technology",
    description: "Technology, devices, and digital vocabulary",
    icon: "💻",
    level: 3,
    sortOrder: 10,
    words: technology,
  });
  total += r10.wordsAdded;

  const r11 = await seedCategory({
    name: "Sports & Hobbies",
    slug: "sports-hobbies",
    description: "Sports, games, and leisure activity vocabulary",
    icon: "⚽",
    level: 3,
    sortOrder: 11,
    words: sportsHobbies,
  });
  total += r11.wordsAdded;

  const r12 = await seedCategory({
    name: "Office & Work",
    slug: "office-work",
    description: "Workplace, career, and professional vocabulary",
    icon: "🏢",
    level: 3,
    sortOrder: 12,
    words: officeWork,
  });
  total += r12.wordsAdded;

  const r13 = await seedCategory({
    name: "Opinions & Discussion",
    slug: "opinions",
    description: "Expressing opinions, agreement, and discussion",
    icon: "💬",
    level: 3,
    sortOrder: 13,
    words: opinions,
  });
  total += r13.wordsAdded;

  const r14 = await seedCategory({
    name: "Time Expressions",
    slug: "time-expressions",
    description: "Adverbs and expressions for time and frequency",
    icon: "⏰",
    level: 3,
    sortOrder: 14,
    words: timeExpressions,
  });
  total += r14.wordsAdded;

  const r15 = await seedCategory({
    name: "Verbs of Motion",
    slug: "verbs-motion",
    description: "Verbs describing physical movement and motion",
    icon: "🏃",
    level: 3,
    sortOrder: 15,
    words: verbsMotion,
  });
  total += r15.wordsAdded;

  const r16 = await seedCategory({
    name: "Descriptive Adjectives",
    slug: "descriptive-adjectives",
    description: "Adjectives for describing people, objects, and qualities",
    icon: "📐",
    level: 3,
    sortOrder: 16,
    words: descriptiveAdjectives,
  });
  total += r16.wordsAdded;

  console.log(`\nLevel 3 complete: ${total} new words added\n`);
  return total;
}
