import "dotenv/config";
import { seedCategory, type WordData } from "./seed-helpers";

// ─── 1. Time & Days ────────────────────────────────────────────────────────

const timeDays: WordData[] = [
  {
    farsiWord: "امروز",
    phonetic: "emrooz",
    englishTranslation: "Today",
    exampleFarsi: "امروز هوا خوب است",
    examplePhonetic: "emrooz hava khoob ast",
    exampleEnglish: "Today the weather is nice",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فردا",
    phonetic: "farda",
    englishTranslation: "Tomorrow",
    exampleFarsi: "فردا به مدرسه می‌روم",
    examplePhonetic: "farda be madrese miravam",
    exampleEnglish: "Tomorrow I go to school",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دیروز",
    phonetic: "dirooz",
    englishTranslation: "Yesterday",
    exampleFarsi: "دیروز باران آمد",
    examplePhonetic: "dirooz baran amad",
    exampleEnglish: "Yesterday it rained",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هفته",
    phonetic: "hafte",
    englishTranslation: "Week",
    exampleFarsi: "این هفته خیلی شلوغ بود",
    examplePhonetic: "in hafte kheyli sholoogh bood",
    exampleEnglish: "This week was very busy",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ماه",
    phonetic: "mah",
    englishTranslation: "Month",
    exampleFarsi: "ماه آینده سفر می‌کنیم",
    examplePhonetic: "mahe ayande safar mikonim",
    exampleEnglish: "Next month we will travel",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سال",
    phonetic: "sal",
    englishTranslation: "Year",
    exampleFarsi: "سال نو مبارک",
    examplePhonetic: "sale no mobarak",
    exampleEnglish: "Happy New Year",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شنبه",
    phonetic: "shanbe",
    englishTranslation: "Saturday",
    exampleFarsi: "شنبه اول هفته است",
    examplePhonetic: "shanbe avale hafte ast",
    exampleEnglish: "Saturday is the first day of the week",
    difficultyLevel: 2,
  },
  {
    farsiWord: "یکشنبه",
    phonetic: "yekshanbe",
    englishTranslation: "Sunday",
    exampleFarsi: "یکشنبه به پارک رفتیم",
    examplePhonetic: "yekshanbe be park raftim",
    exampleEnglish: "On Sunday we went to the park",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دوشنبه",
    phonetic: "doshanbe",
    englishTranslation: "Monday",
    exampleFarsi: "دوشنبه کلاس دارم",
    examplePhonetic: "doshanbe kelas daram",
    exampleEnglish: "On Monday I have class",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سه‌شنبه",
    phonetic: "seshanbe",
    englishTranslation: "Tuesday",
    exampleFarsi: "سه‌شنبه دکتر دارم",
    examplePhonetic: "seshanbe doktor daram",
    exampleEnglish: "On Tuesday I have a doctor's appointment",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چهارشنبه",
    phonetic: "chaharshanbe",
    englishTranslation: "Wednesday",
    exampleFarsi: "چهارشنبه ورزش می‌کنم",
    examplePhonetic: "chaharshanbe varzesh mikonam",
    exampleEnglish: "On Wednesday I exercise",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پنج‌شنبه",
    phonetic: "panjshanbe",
    englishTranslation: "Thursday",
    exampleFarsi: "پنج‌شنبه تعطیل هستیم",
    examplePhonetic: "panjshanbe tatil hastim",
    exampleEnglish: "On Thursday we are off",
    difficultyLevel: 2,
  },
  {
    farsiWord: "جمعه",
    phonetic: "jome",
    englishTranslation: "Friday",
    exampleFarsi: "جمعه روز تعطیل است",
    examplePhonetic: "jome rooze tatil ast",
    exampleEnglish: "Friday is a day off",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ساعت",
    phonetic: "saat",
    englishTranslation: "Hour/Clock",
    exampleFarsi: "ساعت چند است؟",
    examplePhonetic: "saat chand ast?",
    exampleEnglish: "What time is it?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دقیقه",
    phonetic: "daghighe",
    englishTranslation: "Minute",
    exampleFarsi: "پنج دقیقه صبر کن",
    examplePhonetic: "panj daghighe sabr kon",
    exampleEnglish: "Wait five minutes",
    difficultyLevel: 2,
  },
];

// ─── 2. Question Words ─────────────────────────────────────────────────────

const questionWords: WordData[] = [
  {
    farsiWord: "چه",
    phonetic: "che",
    englishTranslation: "What",
    exampleFarsi: "چه می‌خواهی؟",
    examplePhonetic: "che mikhahi?",
    exampleEnglish: "What do you want?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کی",
    phonetic: "key",
    englishTranslation: "When",
    exampleFarsi: "کی می‌آیی؟",
    examplePhonetic: "key miyayi?",
    exampleEnglish: "When are you coming?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کجا",
    phonetic: "koja",
    englishTranslation: "Where",
    exampleFarsi: "کجا می‌روی؟",
    examplePhonetic: "koja miravi?",
    exampleEnglish: "Where are you going?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چرا",
    phonetic: "chera",
    englishTranslation: "Why",
    exampleFarsi: "چرا نیامدی؟",
    examplePhonetic: "chera nayamadi?",
    exampleEnglish: "Why didn't you come?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چطور",
    phonetic: "chetor",
    englishTranslation: "How",
    exampleFarsi: "چطور به خانه رفتی؟",
    examplePhonetic: "chetor be khaneh rafti?",
    exampleEnglish: "How did you get home?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چند",
    phonetic: "chand",
    englishTranslation: "How many",
    exampleFarsi: "چند نفر آمدند؟",
    examplePhonetic: "chand nafar amadand?",
    exampleEnglish: "How many people came?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کدام",
    phonetic: "kodam",
    englishTranslation: "Which",
    exampleFarsi: "کدام کتاب را می‌خواهی؟",
    examplePhonetic: "kodam ketab ra mikhahi?",
    exampleEnglish: "Which book do you want?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کی",
    phonetic: "ki",
    englishTranslation: "Who",
    exampleFarsi: "کی زنگ زد؟",
    examplePhonetic: "ki zang zad?",
    exampleEnglish: "Who called?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چقدر",
    phonetic: "cheghdar",
    englishTranslation: "How much",
    exampleFarsi: "این چقدر است؟",
    examplePhonetic: "in cheghdar ast?",
    exampleEnglish: "How much is this?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آیا",
    phonetic: "aya",
    englishTranslation: "Is it / Do you (question marker)",
    exampleFarsi: "آیا فارسی بلدی؟",
    examplePhonetic: "aya farsi baladi?",
    exampleEnglish: "Do you know Farsi?",
    difficultyLevel: 2,
  },
];

// ─── 3. Common Adjectives ──────────────────────────────────────────────────

const adjectives: WordData[] = [
  {
    farsiWord: "بزرگ",
    phonetic: "bozorg",
    englishTranslation: "Big",
    exampleFarsi: "این شهر خیلی بزرگ است",
    examplePhonetic: "in shahr kheyli bozorg ast",
    exampleEnglish: "This city is very big",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کوچک",
    phonetic: "koochak",
    englishTranslation: "Small",
    exampleFarsi: "اتاق من کوچک است",
    examplePhonetic: "otaghe man koochak ast",
    exampleEnglish: "My room is small",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خوب",
    phonetic: "khoob",
    englishTranslation: "Good",
    exampleFarsi: "این فیلم خیلی خوب بود",
    examplePhonetic: "in film kheyli khoob bood",
    exampleEnglish: "This movie was very good",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بد",
    phonetic: "bad",
    englishTranslation: "Bad",
    exampleFarsi: "امروز روز بدی بود",
    examplePhonetic: "emrooz rooze badi bood",
    exampleEnglish: "Today was a bad day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "زیبا",
    phonetic: "ziba",
    englishTranslation: "Beautiful",
    exampleFarsi: "این گل خیلی زیبا است",
    examplePhonetic: "in gol kheyli ziba ast",
    exampleEnglish: "This flower is very beautiful",
    difficultyLevel: 2,
  },
  {
    farsiWord: "جدید",
    phonetic: "jadid",
    englishTranslation: "New",
    exampleFarsi: "ماشین جدید خریدیم",
    examplePhonetic: "mashine jadid kharidim",
    exampleEnglish: "We bought a new car",
    difficultyLevel: 2,
  },
  {
    farsiWord: "قدیمی",
    phonetic: "ghadimi",
    englishTranslation: "Old (things)",
    exampleFarsi: "این ساختمان خیلی قدیمی است",
    examplePhonetic: "in sakhteman kheyli ghadimi ast",
    exampleEnglish: "This building is very old",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گران",
    phonetic: "geraan",
    englishTranslation: "Expensive",
    exampleFarsi: "این رستوران خیلی گران است",
    examplePhonetic: "in restooran kheyli geraan ast",
    exampleEnglish: "This restaurant is very expensive",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ارزان",
    phonetic: "arzaan",
    englishTranslation: "Cheap",
    exampleFarsi: "این مغازه خیلی ارزان است",
    examplePhonetic: "in maghazeh kheyli arzaan ast",
    exampleEnglish: "This shop is very cheap",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تمیز",
    phonetic: "tamiz",
    englishTranslation: "Clean",
    exampleFarsi: "خانه را تمیز کردم",
    examplePhonetic: "khaneh ra tamiz kardam",
    exampleEnglish: "I cleaned the house",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کثیف",
    phonetic: "kasif",
    englishTranslation: "Dirty",
    exampleFarsi: "لباسهایم کثیف شده",
    examplePhonetic: "lebashhayam kasif shode",
    exampleEnglish: "My clothes got dirty",
    difficultyLevel: 2,
  },
  {
    farsiWord: "راحت",
    phonetic: "rahat",
    englishTranslation: "Comfortable",
    exampleFarsi: "این صندلی خیلی راحت است",
    examplePhonetic: "in sandali kheyli rahat ast",
    exampleEnglish: "This chair is very comfortable",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سخت",
    phonetic: "sakht",
    englishTranslation: "Hard/Difficult",
    exampleFarsi: "امتحان خیلی سخت بود",
    examplePhonetic: "emtehan kheyli sakht bood",
    exampleEnglish: "The exam was very difficult",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آسان",
    phonetic: "asan",
    englishTranslation: "Easy",
    exampleFarsi: "این سوال آسان است",
    examplePhonetic: "in soal asan ast",
    exampleEnglish: "This question is easy",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مهم",
    phonetic: "mohem",
    englishTranslation: "Important",
    exampleFarsi: "این جلسه خیلی مهم است",
    examplePhonetic: "in jalase kheyli mohem ast",
    exampleEnglish: "This meeting is very important",
    difficultyLevel: 2,
  },
];

// ─── 4. Family Members ─────────────────────────────────────────────────────

const family: WordData[] = [
  {
    farsiWord: "پدربزرگ",
    phonetic: "pedarbozorg",
    englishTranslation: "Grandfather",
    exampleFarsi: "پدربزرگم هشتاد سال دارد",
    examplePhonetic: "pedarbozorgam hashtad sal darad",
    exampleEnglish: "My grandfather is eighty years old",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مادربزرگ",
    phonetic: "madarbozorg",
    englishTranslation: "Grandmother",
    exampleFarsi: "مادربزرگم غذای خوبی می‌پزد",
    examplePhonetic: "madarbozorgam ghazaye khoobi mipazad",
    exampleEnglish: "My grandmother cooks good food",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عمو",
    phonetic: "amoo",
    englishTranslation: "Paternal uncle",
    exampleFarsi: "عمویم در تهران زندگی می‌کند",
    examplePhonetic: "amooyam dar tehran zendegi mikonad",
    exampleEnglish: "My uncle lives in Tehran",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عمه",
    phonetic: "amme",
    englishTranslation: "Paternal aunt",
    exampleFarsi: "عمه‌ام معلم است",
    examplePhonetic: "ammeam moalem ast",
    exampleEnglish: "My paternal aunt is a teacher",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دایی",
    phonetic: "dayi",
    englishTranslation: "Maternal uncle",
    exampleFarsi: "دایی‌ام دکتر است",
    examplePhonetic: "dayiam doktor ast",
    exampleEnglish: "My maternal uncle is a doctor",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خاله",
    phonetic: "khaleh",
    englishTranslation: "Maternal aunt",
    exampleFarsi: "خاله‌ام فردا می‌آید",
    examplePhonetic: "khaleam farda miyad",
    exampleEnglish: "My maternal aunt is coming tomorrow",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شوهر",
    phonetic: "showhar",
    englishTranslation: "Husband",
    exampleFarsi: "شوهرم مهندس است",
    examplePhonetic: "showharam mohandes ast",
    exampleEnglish: "My husband is an engineer",
    difficultyLevel: 2,
  },
  {
    farsiWord: "زن",
    phonetic: "zan",
    englishTranslation: "Wife",
    exampleFarsi: "زنم در بیمارستان کار می‌کند",
    examplePhonetic: "zanam dar bimarestan kar mikonad",
    exampleEnglish: "My wife works at the hospital",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پسرعمو",
    phonetic: "pesar-amoo",
    englishTranslation: "Cousin (male)",
    exampleFarsi: "پسرعمویم دانشجو است",
    examplePhonetic: "pesar-amooyam daneshjoo ast",
    exampleEnglish: "My cousin is a student",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دخترخاله",
    phonetic: "dokhtar-khaleh",
    englishTranslation: "Cousin (female)",
    exampleFarsi: "دخترخاله‌ام عروسی کرد",
    examplePhonetic: "dokhtar-khaleam aroosi kard",
    exampleEnglish: "My cousin got married",
    difficultyLevel: 2,
  },
  {
    farsiWord: "نوه",
    phonetic: "naveh",
    englishTranslation: "Grandchild",
    exampleFarsi: "نوه‌اش خیلی بامزه است",
    examplePhonetic: "naveash kheyli bamazeh ast",
    exampleEnglish: "His/Her grandchild is very cute",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عروس",
    phonetic: "aroos",
    englishTranslation: "Bride",
    exampleFarsi: "عروس لباس سفید پوشیده بود",
    examplePhonetic: "aroos lebase sefid pooshide bood",
    exampleEnglish: "The bride was wearing a white dress",
    difficultyLevel: 2,
  },
];

// ─── 5. Conjunctions & Adverbs ─────────────────────────────────────────────

const conjunctions: WordData[] = [
  {
    farsiWord: "و",
    phonetic: "va",
    englishTranslation: "And",
    exampleFarsi: "من و برادرم به مدرسه رفتیم",
    examplePhonetic: "man va baradaram be madrese raftim",
    exampleEnglish: "My brother and I went to school",
    difficultyLevel: 2,
  },
  {
    farsiWord: "اما",
    phonetic: "amma",
    englishTranslation: "But",
    exampleFarsi: "می‌خواستم بیایم اما نتوانستم",
    examplePhonetic: "mikhaestam biyam amma natavanestam",
    exampleEnglish: "I wanted to come but I couldn't",
    difficultyLevel: 2,
  },
  {
    farsiWord: "یا",
    phonetic: "ya",
    englishTranslation: "Or",
    exampleFarsi: "چای می‌خواهی یا قهوه؟",
    examplePhonetic: "chay mikhahi ya ghahve?",
    exampleEnglish: "Do you want tea or coffee?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چون",
    phonetic: "chon",
    englishTranslation: "Because",
    exampleFarsi: "نرفتم چون مریض بودم",
    examplePhonetic: "naraftam chon mariz boodam",
    exampleEnglish: "I didn't go because I was sick",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هم",
    phonetic: "ham",
    englishTranslation: "Also",
    exampleFarsi: "من هم می‌خواهم بیایم",
    examplePhonetic: "man ham mikhaham biyam",
    exampleEnglish: "I also want to come",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خیلی",
    phonetic: "kheyli",
    englishTranslation: "Very",
    exampleFarsi: "این کتاب خیلی جالب است",
    examplePhonetic: "in ketab kheyli jaleb ast",
    exampleEnglish: "This book is very interesting",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کمی",
    phonetic: "kami",
    englishTranslation: "A little",
    exampleFarsi: "کمی آب می‌خواهم",
    examplePhonetic: "kami ab mikhaham",
    exampleEnglish: "I want a little water",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هنوز",
    phonetic: "hanooz",
    englishTranslation: "Still/Yet",
    exampleFarsi: "هنوز غذا حاضر نشده",
    examplePhonetic: "hanooz ghaza hazer nashode",
    exampleEnglish: "The food is not ready yet",
    difficultyLevel: 2,
  },
  {
    farsiWord: "همیشه",
    phonetic: "hamishe",
    englishTranslation: "Always",
    exampleFarsi: "او همیشه زود می‌آید",
    examplePhonetic: "oo hamishe zood miyad",
    exampleEnglish: "He/She always comes early",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هرگز",
    phonetic: "hargez",
    englishTranslation: "Never",
    exampleFarsi: "من هرگز دروغ نمی‌گویم",
    examplePhonetic: "man hargez doroogh nemigoyam",
    exampleEnglish: "I never tell lies",
    difficultyLevel: 2,
  },
  {
    farsiWord: "الان",
    phonetic: "alan",
    englishTranslation: "Now",
    exampleFarsi: "الان باید بروم",
    examplePhonetic: "alan bayad beravam",
    exampleEnglish: "I have to go now",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بعد",
    phonetic: "ba'd",
    englishTranslation: "After/Later",
    exampleFarsi: "بعد از ناهار استراحت می‌کنم",
    examplePhonetic: "ba'd az nahar esterahat mikonam",
    exampleEnglish: "I rest after lunch",
    difficultyLevel: 2,
  },
];

// ─── 6. Jobs & Work ────────────────────────────────────────────────────────

const jobs: WordData[] = [
  {
    farsiWord: "دکتر",
    phonetic: "doktor",
    englishTranslation: "Doctor",
    exampleFarsi: "دکتر به بیمار دارو داد",
    examplePhonetic: "doktor be bimar daroo dad",
    exampleEnglish: "The doctor gave medicine to the patient",
    difficultyLevel: 2,
  },
  {
    farsiWord: "معلم",
    phonetic: "moalem",
    englishTranslation: "Teacher",
    exampleFarsi: "معلم درس جدید یاد داد",
    examplePhonetic: "moalem darse jadid yad dad",
    exampleEnglish: "The teacher taught a new lesson",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مهندس",
    phonetic: "mohandes",
    englishTranslation: "Engineer",
    exampleFarsi: "مهندس ساختمان را طراحی کرد",
    examplePhonetic: "mohandes sakhteman ra tarahi kard",
    exampleEnglish: "The engineer designed the building",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پلیس",
    phonetic: "polis",
    englishTranslation: "Police",
    exampleFarsi: "پلیس به ما کمک کرد",
    examplePhonetic: "polis be ma komak kard",
    exampleEnglish: "The police helped us",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آشپز",
    phonetic: "ashpaz",
    englishTranslation: "Chef",
    exampleFarsi: "آشپز رستوران خیلی ماهر است",
    examplePhonetic: "ashpaze restooran kheyli maher ast",
    exampleEnglish: "The restaurant chef is very skilled",
    difficultyLevel: 2,
  },
  {
    farsiWord: "راننده",
    phonetic: "ranande",
    englishTranslation: "Driver",
    exampleFarsi: "راننده اتوبوس خیلی خوب رانندگی می‌کند",
    examplePhonetic: "ranandeye otooboos kheyli khoob ranandegi mikonad",
    exampleEnglish: "The bus driver drives very well",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خلبان",
    phonetic: "khalaban",
    englishTranslation: "Pilot",
    exampleFarsi: "خلبان هواپیما را به سلامت فرود آورد",
    examplePhonetic: "khalaban havapeyma ra be salamat forood avord",
    exampleEnglish: "The pilot landed the plane safely",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پرستار",
    phonetic: "parastar",
    englishTranslation: "Nurse",
    exampleFarsi: "پرستار آمپول زد",
    examplePhonetic: "parastar ampol zad",
    exampleEnglish: "The nurse gave an injection",
    difficultyLevel: 2,
  },
  {
    farsiWord: "وکیل",
    phonetic: "vakil",
    englishTranslation: "Lawyer",
    exampleFarsi: "وکیل پرونده را بررسی کرد",
    examplePhonetic: "vakil parvandeh ra barresi kard",
    exampleEnglish: "The lawyer reviewed the case",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دانشجو",
    phonetic: "daneshjoo",
    englishTranslation: "Student",
    exampleFarsi: "دانشجوها در کتابخانه درس می‌خوانند",
    examplePhonetic: "daneshjoha dar ketabkhaneh dars mikhanand",
    exampleEnglish: "The students study at the library",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هنرمند",
    phonetic: "honarmand",
    englishTranslation: "Artist",
    exampleFarsi: "هنرمند تابلوی زیبایی کشید",
    examplePhonetic: "honarmand tabloye zibai keshid",
    exampleEnglish: "The artist painted a beautiful picture",
    difficultyLevel: 2,
  },
  {
    farsiWord: "نویسنده",
    phonetic: "nevisande",
    englishTranslation: "Writer",
    exampleFarsi: "نویسنده داستان جالبی نوشت",
    examplePhonetic: "nevisande dastane jalebi nevesht",
    exampleEnglish: "The writer wrote an interesting story",
    difficultyLevel: 2,
  },
];

// ─── 7. Weather ────────────────────────────────────────────────────────────

const weather: WordData[] = [
  {
    farsiWord: "آفتابی",
    phonetic: "aftabi",
    englishTranslation: "Sunny",
    exampleFarsi: "فردا هوا آفتابی می‌شود",
    examplePhonetic: "farda hava aftabi mishavad",
    exampleEnglish: "Tomorrow the weather will be sunny",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بارانی",
    phonetic: "barani",
    englishTranslation: "Rainy",
    exampleFarsi: "امروز هوا بارانی است، چتر ببر",
    examplePhonetic: "emrooz hava barani ast, chatr bebar",
    exampleEnglish: "Today is rainy, take an umbrella",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ابری",
    phonetic: "abri",
    englishTranslation: "Cloudy",
    exampleFarsi: "آسمان ابری است اما باران نمی‌بارد",
    examplePhonetic: "aseman abri ast amma baran nemibarad",
    exampleEnglish: "The sky is cloudy but it's not raining",
    difficultyLevel: 2,
  },
  {
    farsiWord: "برفی",
    phonetic: "barfi",
    englishTranslation: "Snowy",
    exampleFarsi: "زمستان در تهران برفی است",
    examplePhonetic: "zemestan dar tehran barfi ast",
    exampleEnglish: "Winter in Tehran is snowy",
    difficultyLevel: 2,
  },
  {
    farsiWord: "باد",
    phonetic: "baad",
    englishTranslation: "Wind",
    exampleFarsi: "امروز باد شدیدی می‌وزد",
    examplePhonetic: "emrooz bade shadidi mivazad",
    exampleEnglish: "A strong wind is blowing today",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گرما",
    phonetic: "garma",
    englishTranslation: "Heat",
    exampleFarsi: "گرمای تابستان خیلی زیاد است",
    examplePhonetic: "garmaye tabestaan kheyli ziad ast",
    exampleEnglish: "The summer heat is very intense",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سرما",
    phonetic: "sarma",
    englishTranslation: "Cold (noun)",
    exampleFarsi: "از سرمای زمستان لباس گرم بپوش",
    examplePhonetic: "az sarmaye zemestaan lebase garm bepoosh",
    exampleEnglish: "Wear warm clothes because of the winter cold",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مه",
    phonetic: "meh",
    englishTranslation: "Fog",
    exampleFarsi: "صبح مه زیادی بود",
    examplePhonetic: "sobh mehe ziadi bood",
    exampleEnglish: "There was a lot of fog in the morning",
    difficultyLevel: 2,
  },
  {
    farsiWord: "طوفان",
    phonetic: "toofan",
    englishTranslation: "Storm",
    exampleFarsi: "دیشب طوفان شدیدی آمد",
    examplePhonetic: "dishab toofane shadidi amad",
    exampleEnglish: "Last night a severe storm came",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هوا",
    phonetic: "hava",
    englishTranslation: "Weather",
    exampleFarsi: "هوای امروز خیلی خوب است",
    examplePhonetic: "havaye emrooz kheyli khoob ast",
    exampleEnglish: "Today's weather is very nice",
    difficultyLevel: 2,
  },
];

// ─── 8. Animals ────────────────────────────────────────────────────────────

const animals: WordData[] = [
  {
    farsiWord: "گربه",
    phonetic: "gorbe",
    englishTranslation: "Cat",
    exampleFarsi: "گربه‌ی ما خیلی بازیگوش است",
    examplePhonetic: "gorbeye ma kheyli bazigoosh ast",
    exampleEnglish: "Our cat is very playful",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سگ",
    phonetic: "sag",
    englishTranslation: "Dog",
    exampleFarsi: "سگ وفادارترین حیوان است",
    examplePhonetic: "sag vafadartarin heyvan ast",
    exampleEnglish: "The dog is the most loyal animal",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پرنده",
    phonetic: "parande",
    englishTranslation: "Bird",
    exampleFarsi: "پرنده‌ها در بهار برمی‌گردند",
    examplePhonetic: "parandeha dar bahar barmigardand",
    exampleEnglish: "Birds return in spring",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ماهی",
    phonetic: "mahi",
    englishTranslation: "Fish",
    exampleFarsi: "ماهی‌های رنگی در آکواریوم هستند",
    examplePhonetic: "mahihaye rangi dar akvariom hastand",
    exampleEnglish: "Colorful fish are in the aquarium",
    difficultyLevel: 2,
  },
  {
    farsiWord: "اسب",
    phonetic: "asb",
    englishTranslation: "Horse",
    exampleFarsi: "اسب سواری خیلی دوست دارم",
    examplePhonetic: "asb savari kheyli doost daram",
    exampleEnglish: "I really like horseback riding",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گاو",
    phonetic: "gav",
    englishTranslation: "Cow",
    exampleFarsi: "گاوها در مزرعه علف می‌خورند",
    examplePhonetic: "gavha dar mazraeh alaf mikhorand",
    exampleEnglish: "Cows eat grass on the farm",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گوسفند",
    phonetic: "gosfand",
    englishTranslation: "Sheep",
    exampleFarsi: "چوپان گوسفندها را به کوه برد",
    examplePhonetic: "choopan gosfandha ra be kooh bord",
    exampleEnglish: "The shepherd took the sheep to the mountain",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مرغ",
    phonetic: "morgh",
    englishTranslation: "Chicken",
    exampleFarsi: "مرغ‌ها در حیاط هستند",
    examplePhonetic: "morghha dar hayat hastand",
    exampleEnglish: "The chickens are in the yard",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شیر",
    phonetic: "shir-lion",
    englishTranslation: "Lion",
    exampleFarsi: "شیر پادشاه جنگل است",
    examplePhonetic: "shir padeshahe jangal ast",
    exampleEnglish: "The lion is the king of the jungle",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فیل",
    phonetic: "fil",
    englishTranslation: "Elephant",
    exampleFarsi: "فیل بزرگ‌ترین حیوان خشکی است",
    examplePhonetic: "fil bozorgtarin heyvane khoshki ast",
    exampleEnglish: "The elephant is the largest land animal",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خرس",
    phonetic: "khers",
    englishTranslation: "Bear",
    exampleFarsi: "خرس قهوه‌ای در جنگل زندگی می‌کند",
    examplePhonetic: "kherse ghahveyi dar jangal zendegi mikonad",
    exampleEnglish: "The brown bear lives in the forest",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خرگوش",
    phonetic: "khargoosh",
    englishTranslation: "Rabbit",
    exampleFarsi: "خرگوش سفید خیلی قشنگ است",
    examplePhonetic: "kharghooshe sefid kheyli ghashang ast",
    exampleEnglish: "The white rabbit is very pretty",
    difficultyLevel: 2,
  },
];

// ─── 9. Body Parts ─────────────────────────────────────────────────────────

const bodyParts: WordData[] = [
  {
    farsiWord: "سر",
    phonetic: "sar",
    englishTranslation: "Head",
    exampleFarsi: "کلاه را روی سرش گذاشت",
    examplePhonetic: "kolah ra rooye sarash gozasht",
    exampleEnglish: "He/She put the hat on his/her head",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چشم",
    phonetic: "cheshm",
    englishTranslation: "Eye",
    exampleFarsi: "چشم‌هایش سبز است",
    examplePhonetic: "cheshmhayash sabz ast",
    exampleEnglish: "His/Her eyes are green",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گوش",
    phonetic: "goosh",
    englishTranslation: "Ear",
    exampleFarsi: "با گوش‌هایت خوب گوش کن",
    examplePhonetic: "ba gooshhayat khoob goosh kon",
    exampleEnglish: "Listen well with your ears",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دهان",
    phonetic: "dahan",
    englishTranslation: "Mouth",
    exampleFarsi: "موقع غذا خوردن دهانت را ببند",
    examplePhonetic: "mogheye ghaza khordan dahanet ra beband",
    exampleEnglish: "Close your mouth when eating",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دست",
    phonetic: "dast",
    englishTranslation: "Hand",
    exampleFarsi: "قبل از غذا دستهایت را بشور",
    examplePhonetic: "ghabl az ghaza dasthayat ra beshoor",
    exampleEnglish: "Wash your hands before eating",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پا",
    phonetic: "pa",
    englishTranslation: "Foot",
    exampleFarsi: "بعد از پیاده‌روی پاهایم درد می‌کند",
    examplePhonetic: "ba'd az piyaderavi pahayam dard mikonad",
    exampleEnglish: "My feet hurt after walking",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بینی",
    phonetic: "bini",
    englishTranslation: "Nose",
    exampleFarsi: "بوی گل‌ها را با بینی‌ام حس کردم",
    examplePhonetic: "booye golha ra ba biniam hes kardam",
    exampleEnglish: "I smelled the flowers with my nose",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مو",
    phonetic: "moo",
    englishTranslation: "Hair",
    exampleFarsi: "موهایش را کوتاه کرد",
    examplePhonetic: "moohayash ra kootah kard",
    exampleEnglish: "He/She cut his/her hair short",
    difficultyLevel: 2,
  },
  {
    farsiWord: "قلب",
    phonetic: "ghalb",
    englishTranslation: "Heart",
    exampleFarsi: "قلبم از خوشحالی تند می‌زند",
    examplePhonetic: "ghalbam az khoshhali tond mizanad",
    exampleEnglish: "My heart beats fast from happiness",
    difficultyLevel: 2,
  },
  {
    farsiWord: "انگشت",
    phonetic: "angosht",
    englishTranslation: "Finger",
    exampleFarsi: "انگشتر را روی انگشتش گذاشت",
    examplePhonetic: "angoshtar ra rooye angoshtash gozasht",
    exampleEnglish: "He/She put the ring on his/her finger",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دندان",
    phonetic: "dandan",
    englishTranslation: "Tooth",
    exampleFarsi: "هر روز دندان‌هایت را مسواک بزن",
    examplePhonetic: "har rooz dandanhayat ra mesvak bezan",
    exampleEnglish: "Brush your teeth every day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "زبان",
    phonetic: "zaban",
    englishTranslation: "Tongue",
    exampleFarsi: "زبان فارسی خیلی زیبا است",
    examplePhonetic: "zabane farsi kheyli ziba ast",
    exampleEnglish: "The Farsi language is very beautiful",
    difficultyLevel: 2,
  },
];

// ─── 10. Clothes ───────────────────────────────────────────────────────────

const clothes: WordData[] = [
  {
    farsiWord: "لباس",
    phonetic: "lebas",
    englishTranslation: "Clothes",
    exampleFarsi: "لباس تمیز بپوش",
    examplePhonetic: "lebase tamiz bepoosh",
    exampleEnglish: "Wear clean clothes",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کفش",
    phonetic: "kafsh",
    englishTranslation: "Shoes",
    exampleFarsi: "کفش‌هایم را در درب گذاشتم",
    examplePhonetic: "kafshhhayam ra dar darb gozashtam",
    exampleEnglish: "I left my shoes at the door",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کلاه",
    phonetic: "kolah",
    englishTranslation: "Hat",
    exampleFarsi: "در تابستان کلاه آفتابی بزن",
    examplePhonetic: "dar tabestaan kolahe aftabi bezan",
    exampleEnglish: "Wear a sun hat in summer",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شلوار",
    phonetic: "shalvar",
    englishTranslation: "Pants",
    exampleFarsi: "شلوار جین خریدم",
    examplePhonetic: "shalvare jin kharidam",
    exampleEnglish: "I bought jeans",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پیراهن",
    phonetic: "pirahan",
    englishTranslation: "Shirt",
    exampleFarsi: "پیراهن آبی به تو می‌آید",
    examplePhonetic: "pirahane abi be to miyad",
    exampleEnglish: "A blue shirt suits you",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کت",
    phonetic: "kot",
    englishTranslation: "Coat",
    exampleFarsi: "هوا سرد است، کتت را بپوش",
    examplePhonetic: "hava sard ast, kotet ra bepoosh",
    exampleEnglish: "It's cold, put on your coat",
    difficultyLevel: 2,
  },
  {
    farsiWord: "جوراب",
    phonetic: "joorab",
    englishTranslation: "Socks",
    exampleFarsi: "جوراب‌های پشمی گرم هستند",
    examplePhonetic: "joorabhaye pashmi garm hastand",
    exampleEnglish: "Wool socks are warm",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عینک",
    phonetic: "eynak",
    englishTranslation: "Glasses",
    exampleFarsi: "بدون عینک نمی‌توانم بخوانم",
    examplePhonetic: "bedoone eynak nemitavanam bekhaanam",
    exampleEnglish: "I can't read without glasses",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دامن",
    phonetic: "daman",
    englishTranslation: "Skirt",
    exampleFarsi: "دامن قرمز خیلی قشنگ است",
    examplePhonetic: "damane ghermez kheyli ghashang ast",
    exampleEnglish: "The red skirt is very pretty",
    difficultyLevel: 2,
  },
  {
    farsiWord: "روسری",
    phonetic: "roosari",
    englishTranslation: "Headscarf",
    exampleFarsi: "روسری ابریشمی خریدم",
    examplePhonetic: "roosariye abrishami kharidam",
    exampleEnglish: "I bought a silk headscarf",
    difficultyLevel: 2,
  },
];

// ─── 11. Basic Verbs Part 1 ────────────────────────────────────────────────

const basicVerbs: WordData[] = [
  {
    farsiWord: "نوشتن",
    phonetic: "neveshtan",
    englishTranslation: "To write",
    exampleFarsi: "من هر روز در دفترم می‌نویسم",
    examplePhonetic: "man har rooz dar daftaram minevisam",
    exampleEnglish: "I write in my notebook every day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خواندن",
    phonetic: "khandan",
    englishTranslation: "To read",
    exampleFarsi: "شب‌ها کتاب می‌خوانم",
    examplePhonetic: "shabbha ketab mikhaanam",
    exampleEnglish: "I read books at night",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شنیدن",
    phonetic: "shenidan",
    englishTranslation: "To hear",
    exampleFarsi: "صدای موسیقی را شنیدم",
    examplePhonetic: "sedaye moosighi ra shenidam",
    exampleEnglish: "I heard the sound of music",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فهمیدن",
    phonetic: "fahmidan",
    englishTranslation: "To understand",
    exampleFarsi: "حرف‌های او را فهمیدم",
    examplePhonetic: "harfhaye oo ra fahmidam",
    exampleEnglish: "I understood what he/she said",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دانستن",
    phonetic: "danestan",
    englishTranslation: "To know",
    exampleFarsi: "جواب سوال را نمی‌دانم",
    examplePhonetic: "javabe soal ra nemidanam",
    exampleEnglish: "I don't know the answer to the question",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خواستن",
    phonetic: "khastan",
    englishTranslation: "To want",
    exampleFarsi: "می‌خواهم فارسی یاد بگیرم",
    examplePhonetic: "mikhaham farsi yad begiram",
    exampleEnglish: "I want to learn Farsi",
    difficultyLevel: 2,
  },
  {
    farsiWord: "توانستن",
    phonetic: "tavanestan",
    englishTranslation: "To be able",
    exampleFarsi: "می‌توانم شنا کنم",
    examplePhonetic: "mitavanam shena konam",
    exampleEnglish: "I can swim",
    difficultyLevel: 2,
  },
  {
    farsiWord: "نشستن",
    phonetic: "neshastan",
    englishTranslation: "To sit",
    exampleFarsi: "لطفاً اینجا بنشینید",
    examplePhonetic: "lotfan inja beneshinid",
    exampleEnglish: "Please sit here",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ایستادن",
    phonetic: "istadan",
    englishTranslation: "To stand",
    exampleFarsi: "مردم در صف ایستاده بودند",
    examplePhonetic: "mardom dar saf istade boodand",
    exampleEnglish: "People were standing in line",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خندیدن",
    phonetic: "khandidan",
    englishTranslation: "To laugh",
    exampleFarsi: "بچه‌ها با صدای بلند خندیدند",
    examplePhonetic: "bachcha ba sedaye boland khandidand",
    exampleEnglish: "The children laughed loudly",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گریه کردن",
    phonetic: "gerye kardan",
    englishTranslation: "To cry",
    exampleFarsi: "بچه از گرسنگی گریه کرد",
    examplePhonetic: "bachche az gorosnegi gerye kard",
    exampleEnglish: "The child cried from hunger",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پرسیدن",
    phonetic: "porsidan",
    englishTranslation: "To ask",
    exampleFarsi: "از معلم سوال پرسیدم",
    examplePhonetic: "az moalem soal porsidam",
    exampleEnglish: "I asked the teacher a question",
    difficultyLevel: 2,
  },
];

// ─── 12. Basic Verbs Part 2 ────────────────────────────────────────────────

const basicVerbs2: WordData[] = [
  {
    farsiWord: "زدن",
    phonetic: "zadan",
    englishTranslation: "To hit/strike",
    exampleFarsi: "توپ را با پا زد",
    examplePhonetic: "toop ra ba pa zad",
    exampleEnglish: "He/She kicked the ball",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بردن",
    phonetic: "bordan",
    englishTranslation: "To take/carry",
    exampleFarsi: "کتاب را به کتابخانه بردم",
    examplePhonetic: "ketab ra be ketabkhaneh bordam",
    exampleEnglish: "I took the book to the library",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آوردن",
    phonetic: "avardan",
    englishTranslation: "To bring",
    exampleFarsi: "لطفاً یک لیوان آب بیاور",
    examplePhonetic: "lotfan yek livan ab biyavar",
    exampleEnglish: "Please bring a glass of water",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ساختن",
    phonetic: "sakhtan",
    englishTranslation: "To build/make",
    exampleFarsi: "بچه‌ها خانه‌ای با لگو ساختند",
    examplePhonetic: "bachceha khaneyi ba lego sakhtand",
    exampleEnglish: "The children built a house with Lego",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شکستن",
    phonetic: "shekastan",
    englishTranslation: "To break",
    exampleFarsi: "لیوان از دستم افتاد و شکست",
    examplePhonetic: "livan az dastam oftad va shekast",
    exampleEnglish: "The glass fell from my hand and broke",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بستن",
    phonetic: "bastan",
    englishTranslation: "To close/tie",
    exampleFarsi: "لطفاً در را ببندید",
    examplePhonetic: "lotfan dar ra bebandid",
    exampleEnglish: "Please close the door",
    difficultyLevel: 2,
  },
  {
    farsiWord: "باز کردن",
    phonetic: "baz kardan",
    englishTranslation: "To open",
    exampleFarsi: "پنجره را باز کردم",
    examplePhonetic: "panjereh ra baz kardam",
    exampleEnglish: "I opened the window",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شروع کردن",
    phonetic: "shorou kardan",
    englishTranslation: "To start",
    exampleFarsi: "فیلم ساعت هشت شروع می‌شود",
    examplePhonetic: "film saate hasht shorou mishavad",
    exampleEnglish: "The movie starts at eight o'clock",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تمام کردن",
    phonetic: "tamam kardan",
    englishTranslation: "To finish",
    exampleFarsi: "تکالیفم را تمام کردم",
    examplePhonetic: "takalifam ra tamam kardam",
    exampleEnglish: "I finished my homework",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عوض کردن",
    phonetic: "avaz kardan",
    englishTranslation: "To change",
    exampleFarsi: "لباسم را عوض کردم",
    examplePhonetic: "lebasam ra avaz kardam",
    exampleEnglish: "I changed my clothes",
    difficultyLevel: 2,
  },
  {
    farsiWord: "یاد گرفتن",
    phonetic: "yad gereftan",
    englishTranslation: "To learn",
    exampleFarsi: "می‌خواهم آشپزی یاد بگیرم",
    examplePhonetic: "mikhaham ashpazi yad begiram",
    exampleEnglish: "I want to learn cooking",
    difficultyLevel: 2,
  },
  {
    farsiWord: "یاد دادن",
    phonetic: "yad dadan",
    englishTranslation: "To teach",
    exampleFarsi: "مادرم آشپزی یاد داد",
    examplePhonetic: "madaram ashpazi yad dad",
    exampleEnglish: "My mother taught cooking",
    difficultyLevel: 2,
  },
];

// ─── 13. Food & Drink Expanded ─────────────────────────────────────────────

const foodDrink: WordData[] = [
  {
    farsiWord: "مرغ",
    phonetic: "morgh-food",
    englishTranslation: "Chicken (food)",
    exampleFarsi: "برای شام مرغ سرخ کردم",
    examplePhonetic: "baraye sham morgh sorkh kardam",
    exampleEnglish: "I fried chicken for dinner",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ماهی",
    phonetic: "mahi-food",
    englishTranslation: "Fish (food)",
    exampleFarsi: "ماهی کبابی خیلی خوشمزه است",
    examplePhonetic: "mahiye kababi kheyli khoshmaze ast",
    exampleEnglish: "Grilled fish is very delicious",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سبزی",
    phonetic: "sabzi",
    englishTranslation: "Vegetable",
    exampleFarsi: "سبزی تازه از بازار خریدم",
    examplePhonetic: "sabziye tazeh az bazar kharidam",
    exampleEnglish: "I bought fresh vegetables from the market",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سوپ",
    phonetic: "soope",
    englishTranslation: "Soup",
    exampleFarsi: "وقتی مریض هستم سوپ می‌خورم",
    examplePhonetic: "vaghti mariz hastam soope mikhoram",
    exampleEnglish: "When I'm sick I eat soup",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کباب",
    phonetic: "kabab",
    englishTranslation: "Kebab",
    exampleFarsi: "کباب کوبیده غذای معروف ایران است",
    examplePhonetic: "kababe koobide ghazaye maroofe iran ast",
    exampleEnglish: "Koobideh kebab is a famous Iranian food",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آب میوه",
    phonetic: "ab-mive",
    englishTranslation: "Juice",
    exampleFarsi: "یک لیوان آب میوه می‌خواهم",
    examplePhonetic: "yek livan ab-mive mikhaham",
    exampleEnglish: "I want a glass of juice",
    difficultyLevel: 2,
  },
  {
    farsiWord: "قهوه",
    phonetic: "ghahve",
    englishTranslation: "Coffee",
    exampleFarsi: "هر صبح قهوه می‌نوشم",
    examplePhonetic: "har sobh ghahve minoosham",
    exampleEnglish: "I drink coffee every morning",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بستنی",
    phonetic: "bastani",
    englishTranslation: "Ice cream",
    exampleFarsi: "بستنی زعفرانی خیلی خوشمزه است",
    examplePhonetic: "bastaniye zaferani kheyli khoshmaze ast",
    exampleEnglish: "Saffron ice cream is very delicious",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سیب",
    phonetic: "sib",
    englishTranslation: "Apple",
    exampleFarsi: "هر روز یک سیب می‌خورم",
    examplePhonetic: "har rooz yek sib mikhoram",
    exampleEnglish: "I eat an apple every day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هندوانه",
    phonetic: "hendevaneh",
    englishTranslation: "Watermelon",
    exampleFarsi: "تابستان هندوانه خیلی می‌چسبد",
    examplePhonetic: "tabestaan hendevaneh kheyli michasbad",
    exampleEnglish: "Watermelon is great in summer",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پرتقال",
    phonetic: "porteghal",
    englishTranslation: "Orange (fruit)",
    exampleFarsi: "آب پرتقال تازه خوشمزه است",
    examplePhonetic: "abe porteghale tazeh khoshmaze ast",
    exampleEnglish: "Fresh orange juice is delicious",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گوجه",
    phonetic: "gojeh",
    englishTranslation: "Tomato",
    exampleFarsi: "گوجه را برای سالاد خرد کردم",
    examplePhonetic: "gojeh ra baraye salad khord kardam",
    exampleEnglish: "I chopped tomatoes for the salad",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سیب‌زمینی",
    phonetic: "sib-zamini",
    englishTranslation: "Potato",
    exampleFarsi: "سیب‌زمینی سرخ کرده خوشمزه است",
    examplePhonetic: "sib-zaminiye sorkh karde khoshmaze ast",
    exampleEnglish: "French fries are delicious",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پیاز",
    phonetic: "piaz",
    englishTranslation: "Onion",
    exampleFarsi: "پیاز را ریز خرد کن",
    examplePhonetic: "piaz ra riz khord kon",
    exampleEnglish: "Chop the onion finely",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خیار",
    phonetic: "khiyar",
    englishTranslation: "Cucumber",
    exampleFarsi: "خیار با ماست خیلی خوشمزه است",
    examplePhonetic: "khiyar ba mast kheyli khoshmaze ast",
    exampleEnglish: "Cucumber with yogurt is very delicious",
    difficultyLevel: 2,
  },
];

// ─── 14. Home & Furniture ──────────────────────────────────────────────────

const homeFurniture: WordData[] = [
  {
    farsiWord: "اتاق",
    phonetic: "otagh",
    englishTranslation: "Room",
    exampleFarsi: "اتاقم را مرتب کردم",
    examplePhonetic: "otagham ra moratab kardam",
    exampleEnglish: "I tidied up my room",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آشپزخانه",
    phonetic: "ashpaz-khaneh",
    englishTranslation: "Kitchen",
    exampleFarsi: "مادرم در آشپزخانه غذا می‌پزد",
    examplePhonetic: "madaram dar ashpaz-khaneh ghaza mipazad",
    exampleEnglish: "My mother cooks food in the kitchen",
    difficultyLevel: 2,
  },
  {
    farsiWord: "حمام",
    phonetic: "hamam",
    englishTranslation: "Bathroom",
    exampleFarsi: "حمام را تمیز کردم",
    examplePhonetic: "hamam ra tamiz kardam",
    exampleEnglish: "I cleaned the bathroom",
    difficultyLevel: 2,
  },
  {
    farsiWord: "اتاق خواب",
    phonetic: "otagh-e khab",
    englishTranslation: "Bedroom",
    exampleFarsi: "اتاق خوابم دو پنجره دارد",
    examplePhonetic: "otaghe khabam do panjereh darad",
    exampleEnglish: "My bedroom has two windows",
    difficultyLevel: 2,
  },
  {
    farsiWord: "باغ",
    phonetic: "bagh",
    englishTranslation: "Garden",
    exampleFarsi: "در باغ گل کاشتم",
    examplePhonetic: "dar bagh gol kashtam",
    exampleEnglish: "I planted flowers in the garden",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تخت",
    phonetic: "takht",
    englishTranslation: "Bed",
    exampleFarsi: "تختم خیلی راحت است",
    examplePhonetic: "takhtam kheyli rahat ast",
    exampleEnglish: "My bed is very comfortable",
    difficultyLevel: 2,
  },
  {
    farsiWord: "یخچال",
    phonetic: "yakhchal",
    englishTranslation: "Refrigerator",
    exampleFarsi: "شیر را در یخچال بگذار",
    examplePhonetic: "shir ra dar yakhchal begozar",
    exampleEnglish: "Put the milk in the refrigerator",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تلویزیون",
    phonetic: "televizion",
    englishTranslation: "Television",
    exampleFarsi: "شب‌ها تلویزیون تماشا می‌کنیم",
    examplePhonetic: "shabha televizion tamasha mikonim",
    exampleEnglish: "We watch television at night",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مبل",
    phonetic: "mobl",
    englishTranslation: "Sofa",
    exampleFarsi: "روی مبل نشستم و کتاب خواندم",
    examplePhonetic: "rooye mobl neshastam va ketab khaanam",
    exampleEnglish: "I sat on the sofa and read a book",
    difficultyLevel: 2,
  },
  {
    farsiWord: "زمین",
    phonetic: "zamin",
    englishTranslation: "Floor/Ground",
    exampleFarsi: "زمین خانه را جارو کردم",
    examplePhonetic: "zamine khaneh ra jaroo kardam",
    exampleEnglish: "I swept the floor of the house",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دیوار",
    phonetic: "divar",
    englishTranslation: "Wall",
    exampleFarsi: "تابلو را به دیوار زدم",
    examplePhonetic: "tablo ra be divar zadam",
    exampleEnglish: "I hung the picture on the wall",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پله",
    phonetic: "pele",
    englishTranslation: "Stairs",
    exampleFarsi: "از پله‌ها بالا رفتم",
    examplePhonetic: "az peleha bala raftam",
    exampleEnglish: "I went up the stairs",
    difficultyLevel: 2,
  },
];

// ─── 15. Places Around Town ────────────────────────────────────────────────

const placesTown: WordData[] = [
  {
    farsiWord: "بازار",
    phonetic: "bazaar",
    englishTranslation: "Market/Bazaar",
    exampleFarsi: "بازار بزرگ تهران خیلی معروف است",
    examplePhonetic: "bazare bozorge tehran kheyli marouf ast",
    exampleEnglish: "Tehran's Grand Bazaar is very famous",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بیمارستان",
    phonetic: "bimarestan",
    englishTranslation: "Hospital",
    exampleFarsi: "مادرم در بیمارستان بستری شد",
    examplePhonetic: "madaram dar bimarestan bastari shod",
    exampleEnglish: "My mother was admitted to the hospital",
    difficultyLevel: 2,
  },
  {
    farsiWord: "رستوران",
    phonetic: "restooran",
    englishTranslation: "Restaurant",
    exampleFarsi: "شب در رستوران شام خوردیم",
    examplePhonetic: "shab dar restooran sham khordim",
    exampleEnglish: "We had dinner at the restaurant at night",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پارک",
    phonetic: "park",
    englishTranslation: "Park",
    exampleFarsi: "بچه‌ها در پارک بازی می‌کنند",
    examplePhonetic: "bacheha dar park bazi mikonand",
    exampleEnglish: "Children play in the park",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بانک",
    phonetic: "bank",
    englishTranslation: "Bank",
    exampleFarsi: "باید به بانک بروم و پول بگیرم",
    examplePhonetic: "bayad be bank beravam va pool begiram",
    exampleEnglish: "I have to go to the bank and get money",
    difficultyLevel: 2,
  },
  {
    farsiWord: "داروخانه",
    phonetic: "darookhaneh",
    englishTranslation: "Pharmacy",
    exampleFarsi: "از داروخانه دارو خریدم",
    examplePhonetic: "az darookhaneh daroo kharidam",
    exampleEnglish: "I bought medicine from the pharmacy",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کتابخانه",
    phonetic: "ketabkhaneh",
    englishTranslation: "Library",
    exampleFarsi: "در کتابخانه درس می‌خوانم",
    examplePhonetic: "dar ketabkhaneh dars mikhanam",
    exampleEnglish: "I study at the library",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مسجد",
    phonetic: "masjed",
    englishTranslation: "Mosque",
    exampleFarsi: "مسجد نزدیک خانه ماست",
    examplePhonetic: "masjed nazdike khaneh mast",
    exampleEnglish: "The mosque is near our house",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مغازه",
    phonetic: "maghazeh",
    englishTranslation: "Shop/Store",
    exampleFarsi: "مغازه ساعت ده باز می‌شود",
    examplePhonetic: "maghazeh saate dah baz mishavad",
    exampleEnglish: "The shop opens at ten o'clock",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خیابان",
    phonetic: "khiyaban",
    englishTranslation: "Street",
    exampleFarsi: "خیابان اصلی شهر خیلی شلوغ است",
    examplePhonetic: "khiyabane aslie shahr kheyli sholoogh ast",
    exampleEnglish: "The main street of the city is very crowded",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سینما",
    phonetic: "sinema",
    englishTranslation: "Cinema",
    exampleFarsi: "دیشب به سینما رفتیم",
    examplePhonetic: "dishab be sinema raftim",
    exampleEnglish: "Last night we went to the cinema",
    difficultyLevel: 2,
  },
  {
    farsiWord: "موزه",
    phonetic: "moozeh",
    englishTranslation: "Museum",
    exampleFarsi: "موزه ملی ایران خیلی دیدنی است",
    examplePhonetic: "moozeh melliye iran kheyli didani ast",
    exampleEnglish: "The National Museum of Iran is worth visiting",
    difficultyLevel: 2,
  },
];

// ─── 16. Transportation ────────────────────────────────────────────────────

const transportation: WordData[] = [
  {
    farsiWord: "ماشین",
    phonetic: "mashin",
    englishTranslation: "Car",
    exampleFarsi: "با ماشین به سر کار می‌روم",
    examplePhonetic: "ba mashin be sare kar miravam",
    exampleEnglish: "I go to work by car",
    difficultyLevel: 2,
  },
  {
    farsiWord: "اتوبوس",
    phonetic: "otooboos",
    englishTranslation: "Bus",
    exampleFarsi: "هر روز با اتوبوس به دانشگاه می‌روم",
    examplePhonetic: "har rooz ba otooboos be daneshgah miravam",
    exampleEnglish: "I go to university by bus every day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دوچرخه",
    phonetic: "docharkhe",
    englishTranslation: "Bicycle",
    exampleFarsi: "دوچرخه‌سواری ورزش خوبی است",
    examplePhonetic: "docharkhesavari varzesha khoobi ast",
    exampleEnglish: "Cycling is a good sport",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هواپیما",
    phonetic: "havapeyma",
    englishTranslation: "Airplane",
    exampleFarsi: "با هواپیما به شیراز رفتیم",
    examplePhonetic: "ba havapeyma be shiraz raftim",
    exampleEnglish: "We went to Shiraz by airplane",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مترو",
    phonetic: "metro",
    englishTranslation: "Metro/Subway",
    exampleFarsi: "مترو تهران خیلی شلوغ است",
    examplePhonetic: "metrove tehran kheyli sholoogh ast",
    exampleEnglish: "Tehran's metro is very crowded",
    difficultyLevel: 2,
  },
  {
    farsiWord: "موتور",
    phonetic: "motor",
    englishTranslation: "Motorcycle",
    exampleFarsi: "با موتور در ترافیک راحت‌تر است",
    examplePhonetic: "ba motor dar terafik rahatttar ast",
    exampleEnglish: "It's easier with a motorcycle in traffic",
    difficultyLevel: 2,
  },
  {
    farsiWord: "جاده",
    phonetic: "jadeh",
    englishTranslation: "Road",
    exampleFarsi: "جاده لغزنده است، آهسته رانندگی کن",
    examplePhonetic: "jadeh laghzande ast, aheste ranandegi kon",
    exampleEnglish: "The road is slippery, drive slowly",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ترافیک",
    phonetic: "terafik",
    englishTranslation: "Traffic",
    exampleFarsi: "صبح‌ها ترافیک خیلی سنگین است",
    examplePhonetic: "sobhha terafik kheyli sangin ast",
    exampleEnglish: "The traffic is very heavy in the mornings",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پارکینگ",
    phonetic: "parking",
    englishTranslation: "Parking",
    exampleFarsi: "ماشین را در پارکینگ گذاشتم",
    examplePhonetic: "mashin ra dar parking gozashtam",
    exampleEnglish: "I parked the car in the parking lot",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پمپ بنزین",
    phonetic: "pompe benzin",
    englishTranslation: "Gas station",
    exampleFarsi: "باید به پمپ بنزین بروم",
    examplePhonetic: "bayad be pompe benzin beravam",
    exampleEnglish: "I have to go to the gas station",
    difficultyLevel: 2,
  },
];

// ─── 17. Emotions & Feelings ───────────────────────────────────────────────

const emotions: WordData[] = [
  {
    farsiWord: "خوشحال",
    phonetic: "khoshhal",
    englishTranslation: "Happy",
    exampleFarsi: "از دیدن تو خوشحالم",
    examplePhonetic: "az didane to khoshhalam",
    exampleEnglish: "I am happy to see you",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ناراحت",
    phonetic: "narahat",
    englishTranslation: "Sad/Upset",
    exampleFarsi: "از این خبر خیلی ناراحت شدم",
    examplePhonetic: "az in khabar kheyli narahat shodam",
    exampleEnglish: "I was very upset by this news",
    difficultyLevel: 2,
  },
  {
    farsiWord: "عصبانی",
    phonetic: "asabani",
    englishTranslation: "Angry",
    exampleFarsi: "پدرم از دست من عصبانی شد",
    examplePhonetic: "pedaram az daste man asabani shod",
    exampleEnglish: "My father got angry at me",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ترسیده",
    phonetic: "tarsideh",
    englishTranslation: "Scared",
    exampleFarsi: "بچه از تاریکی ترسیده بود",
    examplePhonetic: "bachche az tariki tarsideh bood",
    exampleEnglish: "The child was scared of the dark",
    difficultyLevel: 2,
  },
  {
    farsiWord: "نگران",
    phonetic: "negaraan",
    englishTranslation: "Worried",
    exampleFarsi: "مادرم همیشه نگران من است",
    examplePhonetic: "madaram hamishe negarane man ast",
    exampleEnglish: "My mother is always worried about me",
    difficultyLevel: 2,
  },
  {
    farsiWord: "خسته",
    phonetic: "khaste",
    englishTranslation: "Tired",
    exampleFarsi: "بعد از کار خیلی خسته هستم",
    examplePhonetic: "ba'd az kar kheyli khaste hastam",
    exampleEnglish: "I am very tired after work",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تنها",
    phonetic: "tanha",
    englishTranslation: "Lonely",
    exampleFarsi: "احساس تنهایی می‌کنم",
    examplePhonetic: "ehsase tanhayi mikonam",
    exampleEnglish: "I feel lonely",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آرام",
    phonetic: "aram",
    englishTranslation: "Calm",
    exampleFarsi: "آرام باش، همه چیز درست می‌شود",
    examplePhonetic: "aram bash, hame chiz dorost mishavad",
    exampleEnglish: "Be calm, everything will be fine",
    difficultyLevel: 2,
  },
  {
    farsiWord: "متعجب",
    phonetic: "motaajeb",
    englishTranslation: "Surprised",
    exampleFarsi: "از دیدن او متعجب شدم",
    examplePhonetic: "az didane oo motaajeb shodam",
    exampleEnglish: "I was surprised to see him/her",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شرمنده",
    phonetic: "sharmandeh",
    englishTranslation: "Ashamed/Sorry",
    exampleFarsi: "شرمنده، دیر آمدم",
    examplePhonetic: "sharmandeh, dir amadam",
    exampleEnglish: "Sorry, I came late",
    difficultyLevel: 2,
  },
  {
    farsiWord: "امیدوار",
    phonetic: "omidvar",
    englishTranslation: "Hopeful",
    exampleFarsi: "امیدوارم همه چیز خوب شود",
    examplePhonetic: "omidvaram hame chiz khoob shavad",
    exampleEnglish: "I hope everything goes well",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مفتخر",
    phonetic: "mofakher",
    englishTranslation: "Proud",
    exampleFarsi: "پدرم از موفقیتم مفتخر است",
    examplePhonetic: "pedaram az movafaghiyatam mofakher ast",
    exampleEnglish: "My father is proud of my success",
    difficultyLevel: 2,
  },
];

// ─── 18. Daily Routines ────────────────────────────────────────────────────

const dailyRoutines: WordData[] = [
  {
    farsiWord: "بیدار شدن",
    phonetic: "bidaar shodan",
    englishTranslation: "To wake up",
    exampleFarsi: "هر روز ساعت شش بیدار می‌شوم",
    examplePhonetic: "har rooz saate shesh bidaar mishavam",
    exampleEnglish: "I wake up at six every day",
    difficultyLevel: 2,
  },
  {
    farsiWord: "مسواک زدن",
    phonetic: "mesvak zadan",
    englishTranslation: "To brush teeth",
    exampleFarsi: "صبح و شب مسواک می‌زنم",
    examplePhonetic: "sobh va shab mesvak mizanam",
    exampleEnglish: "I brush my teeth morning and night",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دوش گرفتن",
    phonetic: "doosh gereftan",
    englishTranslation: "To shower",
    exampleFarsi: "هر روز صبح دوش می‌گیرم",
    examplePhonetic: "har rooz sobh doosh migiram",
    exampleEnglish: "I take a shower every morning",
    difficultyLevel: 2,
  },
  {
    farsiWord: "صبحانه",
    phonetic: "sobhaneh",
    englishTranslation: "Breakfast",
    exampleFarsi: "صبحانه مهم‌ترین وعده غذایی است",
    examplePhonetic: "sobhaneh mohemtarin va'de ghazayi ast",
    exampleEnglish: "Breakfast is the most important meal",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ناهار",
    phonetic: "nahar",
    englishTranslation: "Lunch",
    exampleFarsi: "ناهار چه غذایی داریم؟",
    examplePhonetic: "nahar che ghazayi darim?",
    exampleEnglish: "What are we having for lunch?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شام",
    phonetic: "sham",
    englishTranslation: "Dinner",
    exampleFarsi: "شام را با خانواده می‌خوریم",
    examplePhonetic: "sham ra ba khanevadeh mikhorim",
    exampleEnglish: "We eat dinner with the family",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آشپزی کردن",
    phonetic: "ashpazi kardan",
    englishTranslation: "To cook",
    exampleFarsi: "امروز من آشپزی می‌کنم",
    examplePhonetic: "emrooz man ashpazi mikonam",
    exampleEnglish: "Today I will cook",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تمیز کردن",
    phonetic: "tamiz kardan",
    englishTranslation: "To clean",
    exampleFarsi: "آخر هفته خانه را تمیز می‌کنم",
    examplePhonetic: "akhare hafte khaneh ra tamiz mikonam",
    exampleEnglish: "I clean the house on weekends",
    difficultyLevel: 2,
  },
  {
    farsiWord: "استراحت کردن",
    phonetic: "esterahat kardan",
    englishTranslation: "To rest",
    exampleFarsi: "بعد از ناهار کمی استراحت می‌کنم",
    examplePhonetic: "ba'd az nahar kami esterahat mikonam",
    exampleEnglish: "I rest a little after lunch",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ورزش کردن",
    phonetic: "varzesh kardan",
    englishTranslation: "To exercise",
    exampleFarsi: "هر روز صبح ورزش می‌کنم",
    examplePhonetic: "har rooz sobh varzesh mikonam",
    exampleEnglish: "I exercise every morning",
    difficultyLevel: 2,
  },
];

// ─── 19. Large Numbers & Ordinals ──────────────────────────────────────────

const numbersLarge: WordData[] = [
  {
    farsiWord: "سی",
    phonetic: "si",
    englishTranslation: "Thirty",
    exampleFarsi: "او سی سال دارد",
    examplePhonetic: "oo si sal darad",
    exampleEnglish: "He/She is thirty years old",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چهل",
    phonetic: "chehel",
    englishTranslation: "Forty",
    exampleFarsi: "چهل دانش‌آموز در کلاس هستند",
    examplePhonetic: "chehel daneshamooz dar kelas hastand",
    exampleEnglish: "There are forty students in the class",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پنجاه",
    phonetic: "panjah",
    englishTranslation: "Fifty",
    exampleFarsi: "پدربزرگم پنجاه سال کار کرد",
    examplePhonetic: "pedarbozorgam panjah sal kar kard",
    exampleEnglish: "My grandfather worked for fifty years",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شصت",
    phonetic: "shast",
    englishTranslation: "Sixty",
    exampleFarsi: "هر ساعت شصت دقیقه است",
    examplePhonetic: "har saat shast daghighe ast",
    exampleEnglish: "Every hour is sixty minutes",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هفتاد",
    phonetic: "haftad",
    englishTranslation: "Seventy",
    exampleFarsi: "مادربزرگم هفتاد ساله است",
    examplePhonetic: "madarbozorgam haftad saleh ast",
    exampleEnglish: "My grandmother is seventy years old",
    difficultyLevel: 2,
  },
  {
    farsiWord: "هشتاد",
    phonetic: "hashtad",
    englishTranslation: "Eighty",
    exampleFarsi: "هشتاد درصد مردم رای دادند",
    examplePhonetic: "hashtad darsade mardom ray dadand",
    exampleEnglish: "Eighty percent of people voted",
    difficultyLevel: 2,
  },
  {
    farsiWord: "نود",
    phonetic: "navad",
    englishTranslation: "Ninety",
    exampleFarsi: "نمره‌ام نود شد",
    examplePhonetic: "nomream navad shod",
    exampleEnglish: "My grade was ninety",
    difficultyLevel: 2,
  },
  {
    farsiWord: "اول",
    phonetic: "aval",
    englishTranslation: "First",
    exampleFarsi: "نفر اول جایزه گرفت",
    examplePhonetic: "nafare aval jayeze gereft",
    exampleEnglish: "The first person won a prize",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دوم",
    phonetic: "dovom",
    englishTranslation: "Second",
    exampleFarsi: "خانه ما در طبقه دوم است",
    examplePhonetic: "khaneh ma dar tabagheye dovom ast",
    exampleEnglish: "Our home is on the second floor",
    difficultyLevel: 2,
  },
  {
    farsiWord: "سوم",
    phonetic: "sevom",
    englishTranslation: "Third",
    exampleFarsi: "سومین روز هفته سه‌شنبه است",
    examplePhonetic: "sevomin rooze hafte seshanbe ast",
    exampleEnglish: "The third day of the week is Tuesday",
    difficultyLevel: 2,
  },
];

// ─── 20. Common Verbs 2 ────────────────────────────────────────────────────

const commonVerbs2: WordData[] = [
  {
    farsiWord: "خریدن",
    phonetic: "kharidan",
    englishTranslation: "To buy",
    exampleFarsi: "از بازار میوه خریدم",
    examplePhonetic: "az bazar miveh kharidam",
    exampleEnglish: "I bought fruit from the market",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فروختن",
    phonetic: "forokhtan",
    englishTranslation: "To sell",
    exampleFarsi: "ماشین قدیمی‌مان را فروختیم",
    examplePhonetic: "mashine ghadimimaan ra forokhtim",
    exampleEnglish: "We sold our old car",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پرداخت کردن",
    phonetic: "pardakht kardan",
    englishTranslation: "To pay",
    exampleFarsi: "صورتحساب را پرداخت کردم",
    examplePhonetic: "soorat-hesab ra pardakht kardam",
    exampleEnglish: "I paid the bill",
    difficultyLevel: 2,
  },
  {
    farsiWord: "دادن",
    phonetic: "dadan",
    englishTranslation: "To give",
    exampleFarsi: "هدیه‌ای به دوستم دادم",
    examplePhonetic: "hediyeyi be doostam dadam",
    exampleEnglish: "I gave a gift to my friend",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گرفتن",
    phonetic: "gereftan",
    englishTranslation: "To take/get",
    exampleFarsi: "کتاب را از کتابخانه گرفتم",
    examplePhonetic: "ketab ra az ketabkhaneh gereftam",
    exampleEnglish: "I got the book from the library",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فرستادن",
    phonetic: "ferestadan",
    englishTranslation: "To send",
    exampleFarsi: "نامه‌ای به دوستم فرستادم",
    examplePhonetic: "nameyi be doostam ferestadam",
    exampleEnglish: "I sent a letter to my friend",
    difficultyLevel: 2,
  },
  {
    farsiWord: "آوردن",
    phonetic: "avardan-verb",
    englishTranslation: "To bring",
    exampleFarsi: "کتابم را از خانه آوردم",
    examplePhonetic: "ketabam ra az khaneh avardam",
    exampleEnglish: "I brought my book from home",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گذاشتن",
    phonetic: "gozashtan",
    englishTranslation: "To put",
    exampleFarsi: "کلیدها را روی میز گذاشتم",
    examplePhonetic: "kelidha ra rooye miz gozashtam",
    exampleEnglish: "I put the keys on the table",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بریدن",
    phonetic: "boridan",
    englishTranslation: "To cut",
    exampleFarsi: "نان را با چاقو بریدم",
    examplePhonetic: "nan ra ba chaghu boridam",
    exampleEnglish: "I cut the bread with a knife",
    difficultyLevel: 2,
  },
  {
    farsiWord: "شستن",
    phonetic: "shostan",
    englishTranslation: "To wash",
    exampleFarsi: "ظرف‌ها را شستم",
    examplePhonetic: "zarfha ra shostam",
    exampleEnglish: "I washed the dishes",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پوشیدن",
    phonetic: "pooshidan",
    englishTranslation: "To wear",
    exampleFarsi: "لباس گرم بپوش چون هوا سرد است",
    examplePhonetic: "lebase garm bepoosh chon hava sard ast",
    exampleEnglish: "Wear warm clothes because it's cold",
    difficultyLevel: 2,
  },
  {
    farsiWord: "درست کردن",
    phonetic: "dorost kardan",
    englishTranslation: "To fix/make",
    exampleFarsi: "پدرم ماشین را درست کرد",
    examplePhonetic: "pedaram mashin ra dorost kard",
    exampleEnglish: "My father fixed the car",
    difficultyLevel: 2,
  },
];

// ─── 21. Household Items ───────────────────────────────────────────────────

const householdItems: WordData[] = [
  {
    farsiWord: "چراغ",
    phonetic: "cheragh",
    englishTranslation: "Lamp/Light",
    exampleFarsi: "لطفاً چراغ را روشن کن",
    examplePhonetic: "lotfan cheragh ra roshan kon",
    exampleEnglish: "Please turn on the light",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فرش",
    phonetic: "farsh",
    englishTranslation: "Carpet",
    exampleFarsi: "فرش ایرانی در دنیا معروف است",
    examplePhonetic: "farshe irani dar donya marouf ast",
    exampleEnglish: "Iranian carpet is famous in the world",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بالش",
    phonetic: "balesh",
    englishTranslation: "Pillow",
    exampleFarsi: "بالش نرمی دوست دارم",
    examplePhonetic: "baleshe narmi doost daram",
    exampleEnglish: "I like a soft pillow",
    difficultyLevel: 2,
  },
  {
    farsiWord: "پتو",
    phonetic: "patu",
    englishTranslation: "Blanket",
    exampleFarsi: "شب‌های سرد پتوی کلفت لازم است",
    examplePhonetic: "shabhaye sard patooye koloft lazem ast",
    exampleEnglish: "Cold nights require a thick blanket",
    difficultyLevel: 2,
  },
  {
    farsiWord: "بشقاب",
    phonetic: "boshghab",
    englishTranslation: "Plate",
    exampleFarsi: "غذا را در بشقاب ریختم",
    examplePhonetic: "ghaza ra dar boshghab rikhtam",
    exampleEnglish: "I put the food on the plate",
    difficultyLevel: 2,
  },
  {
    farsiWord: "لیوان",
    phonetic: "livan",
    englishTranslation: "Glass (cup)",
    exampleFarsi: "یک لیوان آب لطفاً",
    examplePhonetic: "yek livan ab lotfan",
    exampleEnglish: "A glass of water, please",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چنگال",
    phonetic: "changal",
    englishTranslation: "Fork",
    exampleFarsi: "با چنگال غذا می‌خورم",
    examplePhonetic: "ba changal ghaza mikhoram",
    exampleEnglish: "I eat food with a fork",
    difficultyLevel: 2,
  },
  {
    farsiWord: "قاشق",
    phonetic: "ghashogh",
    englishTranslation: "Spoon",
    exampleFarsi: "سوپ را با قاشق بخور",
    examplePhonetic: "soope ra ba ghashogh bokhor",
    exampleEnglish: "Eat the soup with a spoon",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چاقو",
    phonetic: "chaghu",
    englishTranslation: "Knife",
    exampleFarsi: "چاقو تیز است، مواظب باش",
    examplePhonetic: "chaghu tiz ast, movazeb bash",
    exampleEnglish: "The knife is sharp, be careful",
    difficultyLevel: 2,
  },
  {
    farsiWord: "حوله",
    phonetic: "howleh",
    englishTranslation: "Towel",
    exampleFarsi: "حوله تمیز در حمام است",
    examplePhonetic: "howleye tamiz dar hamam ast",
    exampleEnglish: "The clean towel is in the bathroom",
    difficultyLevel: 2,
  },
];

// ─── 22. Shopping & Money ──────────────────────────────────────────────────

const shoppingMoney: WordData[] = [
  {
    farsiWord: "پول",
    phonetic: "pool",
    englishTranslation: "Money",
    exampleFarsi: "پول کافی همراه داری؟",
    examplePhonetic: "poole kafi hamrah dari?",
    exampleEnglish: "Do you have enough money with you?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "قیمت",
    phonetic: "gheymat",
    englishTranslation: "Price",
    exampleFarsi: "قیمت این کفش چقدر است؟",
    examplePhonetic: "gheimate in kafsh cheghdar ast?",
    exampleEnglish: "What is the price of these shoes?",
    difficultyLevel: 2,
  },
  {
    farsiWord: "گران",
    phonetic: "geran",
    englishTranslation: "Expensive",
    exampleFarsi: "این لباس خیلی گران است",
    examplePhonetic: "in lebas kheyli geran ast",
    exampleEnglish: "These clothes are very expensive",
    difficultyLevel: 2,
  },
  {
    farsiWord: "ارزان",
    phonetic: "arzan",
    englishTranslation: "Cheap",
    exampleFarsi: "میوه‌ها در بازار ارزان‌تر هستند",
    examplePhonetic: "miveha dar bazar arzantar hastand",
    exampleEnglish: "Fruits are cheaper at the market",
    difficultyLevel: 2,
  },
  {
    farsiWord: "فروشگاه",
    phonetic: "foroshgah",
    englishTranslation: "Store",
    exampleFarsi: "فروشگاه بزرگی نزدیک خانه ماست",
    examplePhonetic: "foroshgahe bozorgi nazdike khaneye mast",
    exampleEnglish: "There is a large store near our house",
    difficultyLevel: 2,
  },
  {
    farsiWord: "رسید",
    phonetic: "resid",
    englishTranslation: "Receipt",
    exampleFarsi: "لطفاً رسید بدهید",
    examplePhonetic: "lotfan resid bedahid",
    exampleEnglish: "Please give me a receipt",
    difficultyLevel: 2,
  },
  {
    farsiWord: "کیف پول",
    phonetic: "kife pool",
    englishTranslation: "Wallet",
    exampleFarsi: "کیف پولم را گم کردم",
    examplePhonetic: "kife poolam ra gom kardam",
    exampleEnglish: "I lost my wallet",
    difficultyLevel: 2,
  },
  {
    farsiWord: "تخفیف",
    phonetic: "takhfif",
    englishTranslation: "Discount",
    exampleFarsi: "این فروشگاه تخفیف زیادی دارد",
    examplePhonetic: "in foroshgah takhfife ziadi darad",
    exampleEnglish: "This store has a big discount",
    difficultyLevel: 2,
  },
  {
    farsiWord: "باقی پول",
    phonetic: "baghie pool",
    englishTranslation: "Change (money)",
    exampleFarsi: "باقی پولم را پس بدهید",
    examplePhonetic: "baghie poolam ra pas bedahid",
    exampleEnglish: "Please give me back my change",
    difficultyLevel: 2,
  },
  {
    farsiWord: "چانه زدن",
    phonetic: "chane zadan",
    englishTranslation: "To bargain",
    exampleFarsi: "در بازار می‌توانید چانه بزنید",
    examplePhonetic: "dar bazar mitavanid chaneh bezanid",
    exampleEnglish: "You can bargain at the bazaar",
    difficultyLevel: 2,
  },
];

// ─── Seed Function ─────────────────────────────────────────────────────────

export async function seedLevel2() {
  console.log("\n=== Level 2: Elementary ===\n");
  let total = 0;

  const r1 = await seedCategory({
    name: "Time & Days",
    slug: "time-days",
    description: "Days of the week and time expressions",
    icon: "🕐",
    level: 2,
    sortOrder: 1,
    words: timeDays,
  });
  total += r1.wordsAdded;

  const r2 = await seedCategory({
    name: "Question Words",
    slug: "question-words",
    description: "Essential question words for forming questions",
    icon: "❓",
    level: 2,
    sortOrder: 2,
    words: questionWords,
  });
  total += r2.wordsAdded;

  const r3 = await seedCategory({
    name: "Common Adjectives",
    slug: "adjectives",
    description: "Frequently used adjectives for descriptions",
    icon: "✨",
    level: 2,
    sortOrder: 3,
    words: adjectives,
  });
  total += r3.wordsAdded;

  const r4 = await seedCategory({
    name: "Family Members",
    slug: "family",
    description: "Extended family members and relationships",
    icon: "👪",
    level: 2,
    sortOrder: 4,
    words: family,
  });
  total += r4.wordsAdded;

  const r5 = await seedCategory({
    name: "Conjunctions & Adverbs",
    slug: "conjunctions",
    description: "Connecting words and common adverbs",
    icon: "🔗",
    level: 2,
    sortOrder: 5,
    words: conjunctions,
  });
  total += r5.wordsAdded;

  const r6 = await seedCategory({
    name: "Jobs & Work",
    slug: "jobs",
    description: "Common professions and work-related vocabulary",
    icon: "💼",
    level: 2,
    sortOrder: 6,
    words: jobs,
  });
  total += r6.wordsAdded;

  const r7 = await seedCategory({
    name: "Weather",
    slug: "weather",
    description: "Weather conditions and climate vocabulary",
    icon: "🌤️",
    level: 2,
    sortOrder: 7,
    words: weather,
  });
  total += r7.wordsAdded;

  const r8 = await seedCategory({
    name: "Animals",
    slug: "animals",
    description: "Common animals and wildlife",
    icon: "🐱",
    level: 2,
    sortOrder: 8,
    words: animals,
  });
  total += r8.wordsAdded;

  const r9 = await seedCategory({
    name: "Body Parts",
    slug: "body-parts",
    description: "Parts of the human body",
    icon: "🫀",
    level: 2,
    sortOrder: 9,
    words: bodyParts,
  });
  total += r9.wordsAdded;

  const r10 = await seedCategory({
    name: "Clothes",
    slug: "clothes",
    description: "Clothing and accessories vocabulary",
    icon: "👕",
    level: 2,
    sortOrder: 10,
    words: clothes,
  });
  total += r10.wordsAdded;

  const r11 = await seedCategory({
    name: "Basic Verbs Part 1",
    slug: "basic-verbs",
    description: "Essential verbs for everyday communication",
    icon: "💪",
    level: 2,
    sortOrder: 11,
    words: basicVerbs,
  });
  total += r11.wordsAdded;

  const r12 = await seedCategory({
    name: "Basic Verbs Part 2",
    slug: "basic-verbs-2",
    description: "More essential verbs for daily activities",
    icon: "💪",
    level: 2,
    sortOrder: 12,
    words: basicVerbs2,
  });
  total += r12.wordsAdded;

  const r13 = await seedCategory({
    name: "Food & Drink Expanded",
    slug: "food-drink",
    description: "Food, fruits, vegetables, and beverages",
    icon: "🍲",
    level: 2,
    sortOrder: 13,
    words: foodDrink,
  });
  total += r13.wordsAdded;

  const r14 = await seedCategory({
    name: "Home & Furniture",
    slug: "home-furniture",
    description: "Rooms, furniture, and household vocabulary",
    icon: "🏠",
    level: 2,
    sortOrder: 14,
    words: homeFurniture,
  });
  total += r14.wordsAdded;

  const r15 = await seedCategory({
    name: "Places Around Town",
    slug: "places-town",
    description: "Common places and locations in a city",
    icon: "🏙️",
    level: 2,
    sortOrder: 15,
    words: placesTown,
  });
  total += r15.wordsAdded;

  const r16 = await seedCategory({
    name: "Transportation",
    slug: "transportation",
    description: "Vehicles and transportation vocabulary",
    icon: "🚗",
    level: 2,
    sortOrder: 16,
    words: transportation,
  });
  total += r16.wordsAdded;

  const r17 = await seedCategory({
    name: "Emotions & Feelings",
    slug: "emotions",
    description: "Words for expressing emotions and feelings",
    icon: "😊",
    level: 2,
    sortOrder: 17,
    words: emotions,
  });
  total += r17.wordsAdded;

  const r18 = await seedCategory({
    name: "Daily Routines",
    slug: "daily-routines",
    description: "Common daily activities and routines",
    icon: "☀️",
    level: 2,
    sortOrder: 18,
    words: dailyRoutines,
  });
  total += r18.wordsAdded;

  const r19 = await seedCategory({
    name: "Large Numbers & Ordinals",
    slug: "numbers-large",
    description: "Larger numbers and ordinal numbers",
    icon: "🔢",
    level: 2,
    sortOrder: 19,
    words: numbersLarge,
  });
  total += r19.wordsAdded;

  const r20 = await seedCategory({
    name: "Common Verbs 2",
    slug: "common-verbs-2",
    description: "Additional common verbs for everyday use",
    icon: "🔄",
    level: 2,
    sortOrder: 20,
    words: commonVerbs2,
  });
  total += r20.wordsAdded;

  const r21 = await seedCategory({
    name: "Household Items",
    slug: "household-items",
    description: "Common items found around the house",
    icon: "🏡",
    level: 2,
    sortOrder: 21,
    words: householdItems,
  });
  total += r21.wordsAdded;

  const r22 = await seedCategory({
    name: "Shopping & Money",
    slug: "shopping-money",
    description: "Shopping, money, and transaction vocabulary",
    icon: "💰",
    level: 2,
    sortOrder: 22,
    words: shoppingMoney,
  });
  total += r22.wordsAdded;

  console.log(`\nLevel 2 complete: ${total} new words added\n`);
  return total;
}
