import "dotenv/config";
import { seedCategory, type WordData } from "./seed-helpers";

// ─── 1. Formal Expressions ──────────────────────────────────────────────────

const formalExpressions: WordData[] = [
  {
    farsiWord: "با احترام",
    phonetic: "ba ehteram",
    englishTranslation: "With respect",
    exampleFarsi: "با احترام، نامه شما را دریافت کردیم",
    examplePhonetic: "ba ehteram, nameye shoma ra daryaft kardim",
    exampleEnglish: "With respect, we received your letter",
    difficultyLevel: 4,
  },
  {
    farsiWord: "جناب",
    phonetic: "jenab",
    englishTranslation: "Sir/Your honor",
    exampleFarsi: "جناب آقای رئیسی، لطفاً صحبت کنید",
    examplePhonetic: "jenabe aghaye raisi, lotfan sohbat konid",
    exampleEnglish: "Your honor Mr. Raisi, please speak",
    difficultyLevel: 4,
  },
  {
    farsiWord: "عزیز",
    phonetic: "aziz",
    englishTranslation: "Dear",
    exampleFarsi: "دوست عزیز، از محبت شما ممنونم",
    examplePhonetic: "dooste aziz, az mohabbate shoma mamnoonam",
    exampleEnglish: "Dear friend, I appreciate your kindness",
    difficultyLevel: 4,
  },
  {
    farsiWord: "درخواست",
    phonetic: "darkhast",
    englishTranslation: "Request",
    exampleFarsi: "درخواست مرخصی را به مدیر دادم",
    examplePhonetic: "darkhaste morakhasi ra be modir dadam",
    exampleEnglish: "I submitted the leave request to the manager",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اطلاعیه",
    phonetic: "etela'iyeh",
    englishTranslation: "Announcement",
    exampleFarsi: "اطلاعیه مهمی روی تابلو نصب شده است",
    examplePhonetic: "etela'iyeye mohemmi rooye tablo nasb shode ast",
    exampleEnglish: "An important announcement has been posted on the board",
    difficultyLevel: 4,
  },
  {
    farsiWord: "رسمی",
    phonetic: "rasmi",
    englishTranslation: "Official",
    exampleFarsi: "لباس رسمی برای جلسه بپوشید",
    examplePhonetic: "lebase rasmi baraye jalase bepooshid",
    exampleEnglish: "Wear official attire for the meeting",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سند",
    phonetic: "sanad",
    englishTranslation: "Document",
    exampleFarsi: "سند خانه را در جای امنی نگه دارید",
    examplePhonetic: "sanade khaneh ra dar jaye amni negah darid",
    exampleEnglish: "Keep the house document in a safe place",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اجازه",
    phonetic: "ejazeh",
    englishTranslation: "Permission",
    exampleFarsi: "بدون اجازه نمی‌توانید وارد شوید",
    examplePhonetic: "bedoone ejazeh nemitavanid vared shavid",
    exampleEnglish: "You cannot enter without permission",
    difficultyLevel: 4,
  },
  {
    farsiWord: "امضا",
    phonetic: "emza",
    englishTranslation: "Signature",
    exampleFarsi: "لطفاً انتهای نامه را امضا کنید",
    examplePhonetic: "lotfan entehaye nameh ra emza konid",
    exampleEnglish: "Please sign at the bottom of the letter",
    difficultyLevel: 4,
  },
  {
    farsiWord: "نامه",
    phonetic: "nameh",
    englishTranslation: "Letter",
    exampleFarsi: "نامه رسمی را با دقت بنویسید",
    examplePhonetic: "nameye rasmi ra ba deghat benevisid",
    exampleEnglish: "Write the official letter carefully",
    difficultyLevel: 4,
  },
  {
    farsiWord: "دعوت",
    phonetic: "da'vat",
    englishTranslation: "Invitation",
    exampleFarsi: "دعوت‌نامه جشن را برای همکاران فرستادیم",
    examplePhonetic: "da'vatnamehe jashn ra baraye hamkaran ferestadim",
    exampleEnglish: "We sent the party invitation to our colleagues",
    difficultyLevel: 4,
  },
  {
    farsiWord: "محترمانه",
    phonetic: "mohtaramane",
    englishTranslation: "Respectfully",
    exampleFarsi: "محترمانه از شما می‌خواهم کمک کنید",
    examplePhonetic: "mohtaramane az shoma mikhaham komak konid",
    exampleEnglish: "I respectfully ask you to help",
    difficultyLevel: 4,
  },
  {
    farsiWord: "گزارش",
    phonetic: "gozaresh-formal",
    englishTranslation: "Report",
    exampleFarsi: "گزارش ماهانه را تا فردا آماده کنید",
    examplePhonetic: "gozareshe mahaneh ra ta farda amadeh konid",
    exampleEnglish: "Prepare the monthly report by tomorrow",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اعلام",
    phonetic: "e'lam",
    englishTranslation: "Declaration",
    exampleFarsi: "نتایج امتحان را اعلام کردند",
    examplePhonetic: "natayeje emtehan ra e'lam kardand",
    exampleEnglish: "They declared the exam results",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ارزیابی",
    phonetic: "arziyabi",
    englishTranslation: "Evaluation",
    exampleFarsi: "ارزیابی عملکرد کارکنان هر سال انجام می‌شود",
    examplePhonetic: "arziyabiye amalkarde karkonan har sal anjam mishavad",
    exampleEnglish: "Employee performance evaluation is done every year",
    difficultyLevel: 4,
  },
];

// ─── 2. Feelings & Mental States ────────────────────────────────────────────

const mentalStates: WordData[] = [
  {
    farsiWord: "مطمئن",
    phonetic: "motmaen",
    englishTranslation: "Confident",
    exampleFarsi: "از موفقیتش مطمئن هستم",
    examplePhonetic: "az movaffaghiyatash motmaen hastam",
    exampleEnglish: "I am confident about his success",
    difficultyLevel: 4,
  },
  {
    farsiWord: "گیج",
    phonetic: "gij",
    englishTranslation: "Confused",
    exampleFarsi: "از این همه اطلاعات گیج شدم",
    examplePhonetic: "az in hame etela'at gij shodam",
    exampleEnglish: "I got confused from all this information",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ناامید",
    phonetic: "na-omid",
    englishTranslation: "Disappointed",
    exampleFarsi: "از نتیجه امتحان ناامید شدم",
    examplePhonetic: "az natijehe emtehan na-omid shodam",
    exampleEnglish: "I was disappointed by the exam result",
    difficultyLevel: 4,
  },
  {
    farsiWord: "امیدوار",
    phonetic: "omidvar-mental",
    englishTranslation: "Hopeful",
    exampleFarsi: "به آینده‌ای بهتر امیدوار هستم",
    examplePhonetic: "be ayandeye behtar omidvar hastam",
    exampleEnglish: "I am hopeful for a better future",
    difficultyLevel: 4,
  },
  {
    farsiWord: "صبور",
    phonetic: "saboor",
    englishTranslation: "Patient",
    exampleFarsi: "معلم خوب باید صبور باشد",
    examplePhonetic: "moaleme khoob bayad saboor bashad",
    exampleEnglish: "A good teacher should be patient",
    difficultyLevel: 4,
  },
  {
    farsiWord: "پشیمان",
    phonetic: "pashiman",
    englishTranslation: "Regretful",
    exampleFarsi: "از تصمیمم پشیمان شدم",
    examplePhonetic: "az tasmimam pashiman shodam",
    exampleEnglish: "I became regretful about my decision",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مضطرب",
    phonetic: "moztareb",
    englishTranslation: "Anxious",
    exampleFarsi: "قبل از مصاحبه کاری خیلی مضطرب بودم",
    examplePhonetic: "ghabl az mosahebe kari kheyli moztareb boodam",
    exampleEnglish: "I was very anxious before the job interview",
    difficultyLevel: 4,
  },
  {
    farsiWord: "افسرده",
    phonetic: "afsordeh",
    englishTranslation: "Depressed",
    exampleFarsi: "بعد از شکست در امتحان افسرده شد",
    examplePhonetic: "ba'd az shekast dar emtehan afsordeh shod",
    exampleEnglish: "He became depressed after failing the exam",
    difficultyLevel: 4,
  },
  {
    farsiWord: "باانگیزه",
    phonetic: "ba-angize",
    englishTranslation: "Motivated",
    exampleFarsi: "دانشجویان باانگیزه بهتر درس می‌خوانند",
    examplePhonetic: "daneshjooyan ba-angize behtar dars mikhanand",
    exampleEnglish: "Motivated students study better",
    difficultyLevel: 4,
  },
  {
    farsiWord: "کنجکاو",
    phonetic: "konjkav",
    englishTranslation: "Curious",
    exampleFarsi: "بچه‌ها ذاتاً کنجکاو هستند",
    examplePhonetic: "bacheha zatan konjkav hastand",
    exampleEnglish: "Children are naturally curious",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مفتخر",
    phonetic: "mofakher-mental",
    englishTranslation: "Proud",
    exampleFarsi: "از دستاوردهای تیمم مفتخر هستم",
    examplePhonetic: "az dastavardehaye timam mofakher hastam",
    exampleEnglish: "I am proud of my team's achievements",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شجاع",
    phonetic: "shojaa",
    englishTranslation: "Brave",
    exampleFarsi: "آتش‌نشان‌ها بسیار شجاع هستند",
    examplePhonetic: "atashneshanha besyar shojaa hastand",
    exampleEnglish: "Firefighters are very brave",
    difficultyLevel: 4,
  },
  {
    farsiWord: "فروتن",
    phonetic: "forutan",
    englishTranslation: "Humble",
    exampleFarsi: "با وجود موفقیت بزرگ، فروتن باقی ماند",
    examplePhonetic: "ba vojoode movaffaghiyate bozorg, forutan baghi mand",
    exampleEnglish: "Despite great success, he remained humble",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بخشنده",
    phonetic: "bakhshandeh",
    englishTranslation: "Generous",
    exampleFarsi: "او آدم بسیار بخشنده‌ای است",
    examplePhonetic: "oo adame besyar bakhshandeyi ast",
    exampleEnglish: "He is a very generous person",
    difficultyLevel: 4,
  },
  {
    farsiWord: "یکدنده",
    phonetic: "yek-dande",
    englishTranslation: "Stubborn",
    exampleFarsi: "او خیلی یکدنده است و حرف کسی را گوش نمی‌دهد",
    examplePhonetic: "oo kheyli yek-dande ast va harfe kasi ra goosh nemidahad",
    exampleEnglish: "He is very stubborn and doesn't listen to anyone",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خودخواه",
    phonetic: "khodkhah",
    englishTranslation: "Selfish",
    exampleFarsi: "آدم خودخواه فقط به خودش فکر می‌کند",
    examplePhonetic: "adame khodkhah faghat be khodash fekr mikonad",
    exampleEnglish: "A selfish person only thinks about themselves",
    difficultyLevel: 4,
  },
  {
    farsiWord: "صمیمی",
    phonetic: "sameemi",
    englishTranslation: "Sincere",
    exampleFarsi: "رابطه صمیمی با دوستانم دارم",
    examplePhonetic: "rabeteye sameemi ba doostananam daram",
    exampleEnglish: "I have a sincere relationship with my friends",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مشتاق",
    phonetic: "moshtagh",
    englishTranslation: "Eager",
    exampleFarsi: "مشتاق یادگیری زبان فارسی هستم",
    examplePhonetic: "moshtaqe yadgiriye zabane farsi hastam",
    exampleEnglish: "I am eager to learn the Farsi language",
    difficultyLevel: 4,
  },
];

// ─── 3. Law & Government ────────────────────────────────────────────────────

const lawGovernment: WordData[] = [
  {
    farsiWord: "دولت",
    phonetic: "dolat",
    englishTranslation: "Government",
    exampleFarsi: "دولت بودجه سال جدید را اعلام کرد",
    examplePhonetic: "dolat boodjeye sale jadid ra e'lam kard",
    exampleEnglish: "The government announced the new year's budget",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قانون",
    phonetic: "ghanoon",
    englishTranslation: "Law",
    exampleFarsi: "همه باید از قانون پیروی کنند",
    examplePhonetic: "hame bayad az ghanoon peyravi konand",
    exampleEnglish: "Everyone must follow the law",
    difficultyLevel: 4,
  },
  {
    farsiWord: "رئیس جمهور",
    phonetic: "ra'is-jomhoor",
    englishTranslation: "President",
    exampleFarsi: "رئیس جمهور در مراسم سخنرانی کرد",
    examplePhonetic: "ra'is-jomhoor dar marasem sokhanrani kard",
    exampleEnglish: "The president gave a speech at the ceremony",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مجلس",
    phonetic: "majles",
    englishTranslation: "Parliament",
    exampleFarsi: "مجلس قانون جدیدی را تصویب کرد",
    examplePhonetic: "majles ghanoone jadidi ra tasvib kard",
    exampleEnglish: "Parliament approved a new law",
    difficultyLevel: 4,
  },
  {
    farsiWord: "دادگاه",
    phonetic: "dadgah",
    englishTranslation: "Court",
    exampleFarsi: "پرونده در دادگاه بررسی شد",
    examplePhonetic: "parvandeh dar dadgah barresi shod",
    exampleEnglish: "The case was reviewed in court",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قاضی",
    phonetic: "ghazi",
    englishTranslation: "Judge",
    exampleFarsi: "قاضی حکم نهایی را صادر کرد",
    examplePhonetic: "ghazi hokme nahayi ra sader kard",
    exampleEnglish: "The judge issued the final verdict",
    difficultyLevel: 4,
  },
  {
    farsiWord: "رأی",
    phonetic: "ray",
    englishTranslation: "Vote",
    exampleFarsi: "مردم با رأی خود نماینده انتخاب می‌کنند",
    examplePhonetic: "mardom ba raye khod namayandeh entekhab mikonand",
    exampleEnglish: "People choose representatives with their vote",
    difficultyLevel: 4,
  },
  {
    farsiWord: "انتخابات",
    phonetic: "entekhabat",
    englishTranslation: "Election",
    exampleFarsi: "انتخابات مجلس سال آینده برگزار می‌شود",
    examplePhonetic: "entekhabate majles sale ayandeh bargozar mishavad",
    exampleEnglish: "The parliamentary election will be held next year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شهروند",
    phonetic: "shahrvand",
    englishTranslation: "Citizen",
    exampleFarsi: "هر شهروند حقوق و وظایفی دارد",
    examplePhonetic: "har shahrvand hoghoogh va vazayefi darad",
    exampleEnglish: "Every citizen has rights and duties",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مرز",
    phonetic: "marz",
    englishTranslation: "Border",
    exampleFarsi: "مرزهای کشور توسط ارتش حفاظت می‌شود",
    examplePhonetic: "marzhaye keshvar tavasote artesh hefazat mishavad",
    exampleEnglish: "The country's borders are protected by the army",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مالیات",
    phonetic: "maliat",
    englishTranslation: "Tax",
    exampleFarsi: "پرداخت مالیات وظیفه هر شهروند است",
    examplePhonetic: "pardakhte maliat vazifeye har shahrvand ast",
    exampleEnglish: "Paying taxes is every citizen's duty",
    difficultyLevel: 4,
  },
  {
    farsiWord: "آزادی",
    phonetic: "azadi-law",
    englishTranslation: "Freedom",
    exampleFarsi: "آزادی بیان حق اساسی هر انسان است",
    examplePhonetic: "azadiye bayan haqqe asasiye har ensan ast",
    exampleEnglish: "Freedom of speech is a fundamental right of every human",
    difficultyLevel: 4,
  },
  {
    farsiWord: "عدالت",
    phonetic: "edalat",
    englishTranslation: "Justice",
    exampleFarsi: "عدالت اجتماعی برای همه مردم مهم است",
    examplePhonetic: "edalate ejtemaa'i baraye hame mardom mohem ast",
    exampleEnglish: "Social justice is important for all people",
    difficultyLevel: 4,
  },
  {
    farsiWord: "وزارت",
    phonetic: "vezarat",
    englishTranslation: "Ministry",
    exampleFarsi: "وزارت آموزش و پرورش برنامه جدیدی اعلام کرد",
    examplePhonetic: "vezarate amoozesh va parvaresh barnameye jadidi e'lam kard",
    exampleEnglish: "The Ministry of Education announced a new program",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قانونگذار",
    phonetic: "ghanoongozar",
    englishTranslation: "Legislator",
    exampleFarsi: "قانونگذاران در حال بررسی لایحه جدید هستند",
    examplePhonetic: "ghanoongozaran dar hale barresi layeheye jadid hastand",
    exampleEnglish: "The legislators are reviewing the new bill",
    difficultyLevel: 4,
  },
];

// ─── 4. Media & News ────────────────────────────────────────────────────────

const mediaNews: WordData[] = [
  {
    farsiWord: "اخبار",
    phonetic: "akhbar",
    englishTranslation: "News",
    exampleFarsi: "هر شب اخبار تلویزیون را می‌بینم",
    examplePhonetic: "har shab akhbare televizion ra mibinam",
    exampleEnglish: "I watch the television news every night",
    difficultyLevel: 4,
  },
  {
    farsiWord: "روزنامه",
    phonetic: "roozname",
    englishTranslation: "Newspaper",
    exampleFarsi: "پدرم هر صبح روزنامه می‌خواند",
    examplePhonetic: "pedaram har sobh roozname mikhaanad",
    exampleEnglish: "My father reads the newspaper every morning",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خبرنگار",
    phonetic: "khabarnegar",
    englishTranslation: "Journalist",
    exampleFarsi: "خبرنگار از محل حادثه گزارش داد",
    examplePhonetic: "khabarnegar az mahalle hadeseh gozaresh dad",
    exampleEnglish: "The journalist reported from the scene of the incident",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مقاله",
    phonetic: "maghale",
    englishTranslation: "Article",
    exampleFarsi: "مقاله جالبی درباره محیط زیست خواندم",
    examplePhonetic: "maghaleye jalebi darbare mohite zist khaaandam",
    exampleEnglish: "I read an interesting article about the environment",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تیتر",
    phonetic: "titr",
    englishTranslation: "Headline",
    exampleFarsi: "تیتر روزنامه امروز خیلی جالب بود",
    examplePhonetic: "titre rooznameye emrooz kheyli jaleb bood",
    exampleEnglish: "Today's newspaper headline was very interesting",
    difficultyLevel: 4,
  },
  {
    farsiWord: "برنامه",
    phonetic: "barnameh-media",
    englishTranslation: "Program",
    exampleFarsi: "برنامه مستند درباره طبیعت ایران پخش شد",
    examplePhonetic: "barnameye mostanad darbare tabiate iran pakhsh shod",
    exampleEnglish: "A documentary program about Iran's nature was broadcast",
    difficultyLevel: 4,
  },
  {
    farsiWord: "آگهی",
    phonetic: "agahi",
    englishTranslation: "Advertisement",
    exampleFarsi: "آگهی تبلیغاتی را در تلویزیون دیدم",
    examplePhonetic: "agahiye tablighatiye ra dar televizion didam",
    exampleEnglish: "I saw the advertisement on television",
    difficultyLevel: 4,
  },
  {
    farsiWord: "منتشر کردن",
    phonetic: "monatsher kardan",
    englishTranslation: "To publish",
    exampleFarsi: "کتاب جدیدش را ماه آینده منتشر می‌کنند",
    examplePhonetic: "ketabe jadidash ra mahe ayandeh montasher mikonand",
    exampleEnglish: "They will publish his new book next month",
    difficultyLevel: 4,
  },
  {
    farsiWord: "کانال",
    phonetic: "kanal",
    englishTranslation: "Channel",
    exampleFarsi: "این کانال تلویزیونی فیلم‌های خوبی پخش می‌کند",
    examplePhonetic: "in kanale televizioni filmhaye khoobi pakhsh mikonad",
    exampleEnglish: "This television channel broadcasts good movies",
    difficultyLevel: 4,
  },
  {
    farsiWord: "گزارشگر",
    phonetic: "gozareshgar",
    englishTranslation: "Reporter",
    exampleFarsi: "گزارشگر ورزشی مسابقه فوتبال را توضیح داد",
    examplePhonetic: "gozareshgare varzeshi mosabegheye footbal ra tozih dad",
    exampleEnglish: "The sports reporter described the football match",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مصاحبه",
    phonetic: "mosahebe-media",
    englishTranslation: "Interview",
    exampleFarsi: "با نویسنده معروف مصاحبه کردند",
    examplePhonetic: "ba nevisandeye marouf mosahebe kardand",
    exampleEnglish: "They interviewed the famous writer",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تحریریه",
    phonetic: "tahrir",
    englishTranslation: "Editorial",
    exampleFarsi: "سردبیر تحریریه مقاله مهمی نوشت",
    examplePhonetic: "sardabire tahriri maghaleye mohemmi nevesht",
    exampleEnglish: "The editor-in-chief wrote an important editorial",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اجتماعی",
    phonetic: "ejtemaa'i",
    englishTranslation: "Social",
    exampleFarsi: "شبکه‌های اجتماعی تأثیر زیادی بر جوانان دارند",
    examplePhonetic: "shabakehaye ejtemaa'i ta'sire ziadi bar javanan darand",
    exampleEnglish: "Social networks have a great influence on young people",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مستند",
    phonetic: "mostanad",
    englishTranslation: "Documentary",
    exampleFarsi: "فیلم مستند درباره تاریخ ایران بسیار آموزنده بود",
    examplePhonetic: "filme mostanad darbare tarikhe iran besyar amoozandeh bood",
    exampleEnglish: "The documentary about Iran's history was very educational",
    difficultyLevel: 4,
  },
  {
    farsiWord: "رادیو",
    phonetic: "radio",
    englishTranslation: "Radio",
    exampleFarsi: "صبح‌ها در ماشین رادیو گوش می‌دهم",
    examplePhonetic: "sobhha dar mashin radio goosh midaham",
    exampleEnglish: "I listen to the radio in the car in the mornings",
    difficultyLevel: 4,
  },
];

// ─── 5. Banking & Finance ───────────────────────────────────────────────────

const bankingFinance: WordData[] = [
  {
    farsiWord: "حساب",
    phonetic: "hesab",
    englishTranslation: "Account",
    exampleFarsi: "یک حساب جدید در بانک باز کردم",
    examplePhonetic: "yek hesabe jadid dar bank baz kardam",
    exampleEnglish: "I opened a new account at the bank",
    difficultyLevel: 4,
  },
  {
    farsiWord: "حواله",
    phonetic: "havale",
    englishTranslation: "Transfer",
    exampleFarsi: "حواله بانکی را به حساب شرکت فرستادم",
    examplePhonetic: "havaleye banki ra be hesabe sherkat ferestadam",
    exampleEnglish: "I sent the bank transfer to the company's account",
    difficultyLevel: 4,
  },
  {
    farsiWord: "وام",
    phonetic: "vam",
    englishTranslation: "Loan",
    exampleFarsi: "برای خرید خانه وام گرفتیم",
    examplePhonetic: "baraye kharide khaneh vam gereftim",
    exampleEnglish: "We took a loan to buy a house",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بهره",
    phonetic: "bahre",
    englishTranslation: "Interest",
    exampleFarsi: "نرخ بهره بانکی امسال کاهش یافت",
    examplePhonetic: "nerkhe bahreye banki emsal kahesh yaft",
    exampleEnglish: "The bank interest rate decreased this year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خودپرداز",
    phonetic: "khodpardaz",
    englishTranslation: "ATM",
    exampleFarsi: "از خودپرداز پول برداشت کردم",
    examplePhonetic: "az khodpardaz pool bardasht kardam",
    exampleEnglish: "I withdrew money from the ATM",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سپرده",
    phonetic: "sepordeh",
    englishTranslation: "Deposit",
    exampleFarsi: "سپرده بلندمدت سود بیشتری دارد",
    examplePhonetic: "sepordeye bolandmodat soode bishtari darad",
    exampleEnglish: "A long-term deposit has more profit",
    difficultyLevel: 4,
  },
  {
    farsiWord: "کارت اعتباری",
    phonetic: "kart-e etebari",
    englishTranslation: "Credit card",
    exampleFarsi: "با کارت اعتباری خرید کردم",
    examplePhonetic: "ba karte etebari kharid kardam",
    exampleEnglish: "I made a purchase with a credit card",
    difficultyLevel: 4,
  },
  {
    farsiWord: "نرخ ارز",
    phonetic: "nerkh-e arz",
    englishTranslation: "Exchange rate",
    exampleFarsi: "نرخ ارز امروز تغییر کرد",
    examplePhonetic: "nerkhe arze emrooz taghyir kard",
    exampleEnglish: "The exchange rate changed today",
    difficultyLevel: 4,
  },
  {
    farsiWord: "پس‌انداز",
    phonetic: "pas-andaz",
    englishTranslation: "Savings",
    exampleFarsi: "هر ماه مقداری پس‌انداز می‌کنم",
    examplePhonetic: "har mah meghdari pas-andaz mikonam",
    exampleEnglish: "I save some money every month",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سرمایه‌گذاری",
    phonetic: "sarmayeh-gozari",
    englishTranslation: "Investment",
    exampleFarsi: "سرمایه‌گذاری در بورس ریسک بالایی دارد",
    examplePhonetic: "sarmayeh-gozari dar boors riske balai darad",
    exampleEnglish: "Investing in the stock market has high risk",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بدهی",
    phonetic: "bedehi",
    englishTranslation: "Debt",
    exampleFarsi: "تمام بدهی‌هایم را پرداخت کردم",
    examplePhonetic: "tamame bedehihayam ra pardakht kardam",
    exampleEnglish: "I paid off all my debts",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سود",
    phonetic: "sood",
    englishTranslation: "Profit",
    exampleFarsi: "شرکت امسال سود خوبی به دست آورد",
    examplePhonetic: "sherkat emsal soode khoobi be dast avard",
    exampleEnglish: "The company earned good profit this year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ضرر",
    phonetic: "zarar",
    englishTranslation: "Loss",
    exampleFarsi: "فروشگاه به دلیل کمبود مشتری ضرر کرد",
    examplePhonetic: "foroshgah be dalile kamboode moshtari zarar kard",
    exampleEnglish: "The store suffered a loss due to lack of customers",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سهم",
    phonetic: "sahm",
    englishTranslation: "Share/Stock",
    exampleFarsi: "سهم این شرکت در بورس بالا رفت",
    examplePhonetic: "sahme in sherkat dar boors bala raft",
    exampleEnglish: "This company's stock went up in the market",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بیمه",
    phonetic: "bime",
    englishTranslation: "Insurance",
    exampleFarsi: "بیمه سلامت برای همه ضروری است",
    examplePhonetic: "bimeye salamat baraye hame zaroori ast",
    exampleEnglish: "Health insurance is essential for everyone",
    difficultyLevel: 4,
  },
];

// ─── 6. Housing & Real Estate ───────────────────────────────────────────────

const housing: WordData[] = [
  {
    farsiWord: "آپارتمان",
    phonetic: "aparteman",
    englishTranslation: "Apartment",
    exampleFarsi: "آپارتمان جدیدی در مرکز شهر اجاره کردیم",
    examplePhonetic: "apartemane jadidi dar markaze shahr ejareh kardim",
    exampleEnglish: "We rented a new apartment in the city center",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اجاره",
    phonetic: "ejareh",
    englishTranslation: "Rent",
    exampleFarsi: "اجاره خانه هر سال گران‌تر می‌شود",
    examplePhonetic: "ejareye khaneh har sal gerantar mishavad",
    exampleEnglish: "The rent increases every year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "صاحبخانه",
    phonetic: "saheb-khaneh",
    englishTranslation: "Landlord",
    exampleFarsi: "صاحبخانه قرارداد جدیدی پیشنهاد داد",
    examplePhonetic: "saheb-khaneh gharardade jadidi pishnahad dad",
    exampleEnglish: "The landlord proposed a new contract",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مستأجر",
    phonetic: "mostajer",
    englishTranslation: "Tenant",
    exampleFarsi: "مستأجر جدید ماه آینده اسباب‌کشی می‌کند",
    examplePhonetic: "mostajere jadid mahe ayandeh asbabkeshi mikonad",
    exampleEnglish: "The new tenant will move in next month",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قرارداد",
    phonetic: "gharardad",
    englishTranslation: "Contract",
    exampleFarsi: "قرارداد اجاره را برای یک سال امضا کردیم",
    examplePhonetic: "gharardade ejareh ra baraye yek sal emza kardim",
    exampleEnglish: "We signed the rental contract for one year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "پیش‌پرداخت",
    phonetic: "pish-pardakht",
    englishTranslation: "Down payment",
    exampleFarsi: "پیش‌پرداخت خانه مبلغ زیادی بود",
    examplePhonetic: "pish-pardakhte khaneh mablaghe ziadi bood",
    exampleEnglish: "The house down payment was a large amount",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مبل",
    phonetic: "mobl-housing",
    englishTranslation: "Furniture",
    exampleFarsi: "مبل‌های جدیدی برای پذیرایی خریدیم",
    examplePhonetic: "moblhaye jadidi baraye pazirayi kharidim",
    exampleEnglish: "We bought new furniture for the living room",
    difficultyLevel: 4,
  },
  {
    farsiWord: "محله",
    phonetic: "mahalleh",
    englishTranslation: "Neighborhood",
    exampleFarsi: "محله ما آرام و امن است",
    examplePhonetic: "mahalleye ma aram va amn ast",
    exampleEnglish: "Our neighborhood is quiet and safe",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ساختمان",
    phonetic: "sakhteman",
    englishTranslation: "Building",
    exampleFarsi: "ساختمان جدیدی در خیابان ما ساخته شد",
    examplePhonetic: "sakhtemane jadidi dar khiyabane ma sakhteh shod",
    exampleEnglish: "A new building was constructed on our street",
    difficultyLevel: 4,
  },
  {
    farsiWord: "طبقه",
    phonetic: "tabaghe",
    englishTranslation: "Floor/Story",
    exampleFarsi: "دفتر ما در طبقه پنجم است",
    examplePhonetic: "daftare ma dar tabagheye panjom ast",
    exampleEnglish: "Our office is on the fifth floor",
    difficultyLevel: 4,
  },
  {
    farsiWord: "آسانسور",
    phonetic: "asansor",
    englishTranslation: "Elevator",
    exampleFarsi: "آسانسور ساختمان خراب شده است",
    examplePhonetic: "asansore sakhteman kharab shode ast",
    exampleEnglish: "The building's elevator is broken",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بالکن",
    phonetic: "balkon",
    englishTranslation: "Balcony",
    exampleFarsi: "از بالکن منظره زیبایی دیده می‌شود",
    examplePhonetic: "az balkon manzareye zibai dideh mishavad",
    exampleEnglish: "A beautiful view can be seen from the balcony",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بام",
    phonetic: "bam",
    englishTranslation: "Roof",
    exampleFarsi: "بام خانه به تعمیر نیاز دارد",
    examplePhonetic: "bame khaneh be tamir niyaz darad",
    exampleEnglish: "The roof of the house needs repair",
    difficultyLevel: 4,
  },
  {
    farsiWord: "زیرزمین",
    phonetic: "zirzemeen",
    englishTranslation: "Basement",
    exampleFarsi: "وسایل قدیمی را در زیرزمین نگه می‌داریم",
    examplePhonetic: "vasayele ghadimi ra dar zirzemeen negah midarim",
    exampleEnglish: "We keep old things in the basement",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تعمیر",
    phonetic: "tamir",
    englishTranslation: "Repair",
    exampleFarsi: "تعمیر لوله‌کشی خانه هزینه زیادی داشت",
    examplePhonetic: "tamire loolekeshiye khaneh hazineye ziadi dasht",
    exampleEnglish: "The plumbing repair cost a lot",
    difficultyLevel: 4,
  },
];

// ─── 7. Education Advanced ──────────────────────────────────────────────────

const educationAdvanced: WordData[] = [
  {
    farsiWord: "دانشگاه",
    phonetic: "daneshgah-adv",
    englishTranslation: "University",
    exampleFarsi: "دانشگاه تهران یکی از معتبرترین دانشگاه‌های ایران است",
    examplePhonetic: "daneshgahe tehran yeki az mo'tabartarin daneshgahhaye iran ast",
    exampleEnglish: "The University of Tehran is one of Iran's most prestigious universities",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مدرک",
    phonetic: "madrak-adv",
    englishTranslation: "Degree",
    exampleFarsi: "مدرک کارشناسی ارشد در رشته مهندسی گرفتم",
    examplePhonetic: "madrake karshenasiye arshad dar reshteye mohandesi gereftam",
    exampleEnglish: "I obtained a master's degree in engineering",
    difficultyLevel: 4,
  },
  {
    farsiWord: "امتحان",
    phonetic: "emtehan-adv",
    englishTranslation: "Exam",
    exampleFarsi: "امتحان پایان ترم بسیار سخت بود",
    examplePhonetic: "emtehane payane term besyar sakht bood",
    exampleEnglish: "The final exam was very difficult",
    difficultyLevel: 4,
  },
  {
    farsiWord: "نمره",
    phonetic: "nomreh-adv",
    englishTranslation: "Grade",
    exampleFarsi: "نمره پایان‌نامه‌ام بیست شد",
    examplePhonetic: "nomreye payan-nameam bist shod",
    exampleEnglish: "My thesis grade was twenty (perfect score)",
    difficultyLevel: 4,
  },
  {
    farsiWord: "استاد",
    phonetic: "ostad-adv",
    englishTranslation: "Professor",
    exampleFarsi: "استاد راهنمای من متخصص زبان‌شناسی است",
    examplePhonetic: "ostade rahnamaye man motakhassese zabanashenasi ast",
    exampleEnglish: "My supervising professor is a specialist in linguistics",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تحقیق",
    phonetic: "tahghigh-adv",
    englishTranslation: "Research",
    exampleFarsi: "تحقیقات علمی نیاز به صبر و دقت دارد",
    examplePhonetic: "tahghighate elmi niyaz be sabr va deghat darad",
    exampleEnglish: "Scientific research requires patience and precision",
    difficultyLevel: 4,
  },
  {
    farsiWord: "پایان‌نامه",
    phonetic: "payan-nameh",
    englishTranslation: "Thesis",
    exampleFarsi: "پایان‌نامه دکترایم درباره هوش مصنوعی است",
    examplePhonetic: "payan-nameye doktorayam darbare hooshe masnooi ast",
    exampleEnglish: "My doctoral thesis is about artificial intelligence",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بورس",
    phonetic: "bors",
    englishTranslation: "Scholarship",
    exampleFarsi: "بورس تحصیلی برای رفتن به خارج گرفتم",
    examplePhonetic: "borse tahsili baraye raftan be kharej gereftam",
    exampleEnglish: "I received a scholarship to study abroad",
    difficultyLevel: 4,
  },
  {
    farsiWord: "درس",
    phonetic: "dars-adv",
    englishTranslation: "Lecture",
    exampleFarsi: "درس امروز استاد خیلی جالب بود",
    examplePhonetic: "darse emrooze ostad kheyli jaleb bood",
    exampleEnglish: "Today's lecture by the professor was very interesting",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تکلیف",
    phonetic: "taklif-adv",
    englishTranslation: "Homework",
    exampleFarsi: "تکلیف‌های دانشگاه خیلی سنگین هستند",
    examplePhonetic: "taklifhaye daneshgah kheyli sangin hastand",
    exampleEnglish: "The university homework assignments are very heavy",
    difficultyLevel: 4,
  },
  {
    farsiWord: "فارغ‌التحصیل شدن",
    phonetic: "faaregh-ol-tahsil shodan",
    englishTranslation: "To graduate",
    exampleFarsi: "سال آینده از دانشگاه فارغ‌التحصیل می‌شوم",
    examplePhonetic: "sale ayandeh az daneshgah faaregh-ol-tahsil mishavam",
    exampleEnglish: "I will graduate from university next year",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ترم",
    phonetic: "term",
    englishTranslation: "Semester",
    exampleFarsi: "ترم بهار شش درس انتخاب کردم",
    examplePhonetic: "terme bahar shesh dars entekhab kardam",
    exampleEnglish: "I chose six courses for the spring semester",
    difficultyLevel: 4,
  },
  {
    farsiWord: "رشته",
    phonetic: "reshte-adv",
    englishTranslation: "Major",
    exampleFarsi: "رشته تحصیلی من پزشکی است",
    examplePhonetic: "reshteye tahsiliye man pezeshki ast",
    exampleEnglish: "My major is medicine",
    difficultyLevel: 4,
  },
  {
    farsiWord: "علم",
    phonetic: "elm-adv",
    englishTranslation: "Science",
    exampleFarsi: "پیشرفت علم زندگی بشر را بهتر کرده است",
    examplePhonetic: "pishrafte elm zendegiye bashar ra behtar karde ast",
    exampleEnglish: "The advancement of science has improved human life",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ریاضی",
    phonetic: "riazi-adv",
    englishTranslation: "Mathematics",
    exampleFarsi: "ریاضی پایه بسیاری از علوم مهندسی است",
    examplePhonetic: "riazi payeye besyari az oloome mohandesi ast",
    exampleEnglish: "Mathematics is the foundation of many engineering sciences",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تاریخ",
    phonetic: "tarikh-adv",
    englishTranslation: "History",
    exampleFarsi: "تاریخ ایران باستان بسیار غنی و جالب است",
    examplePhonetic: "tarikhe irane bastan besyar ghani va jaleb ast",
    exampleEnglish: "The history of ancient Iran is very rich and interesting",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ادبیات",
    phonetic: "adabiyat",
    englishTranslation: "Literature",
    exampleFarsi: "ادبیات فارسی یکی از غنی‌ترین ادبیات جهان است",
    examplePhonetic: "adabiyate farsi yeki az ghanitarin adabiyate jahan ast",
    exampleEnglish: "Persian literature is one of the richest in the world",
    difficultyLevel: 4,
  },
  {
    farsiWord: "جغرافیا",
    phonetic: "joghrafiya",
    englishTranslation: "Geography",
    exampleFarsi: "در درس جغرافیا درباره اقلیم ایران یاد گرفتیم",
    examplePhonetic: "dar darse joghrafiya darbare eghlime iran yad gereftim",
    exampleEnglish: "In geography class, we learned about Iran's climate",
    difficultyLevel: 4,
  },
];

// ─── 8. Cooking & Kitchen ───────────────────────────────────────────────────

const cookingKitchen: WordData[] = [
  {
    farsiWord: "پختن",
    phonetic: "pokhtan",
    englishTranslation: "To cook",
    exampleFarsi: "مادرم بهترین غذاها را می‌پزد",
    examplePhonetic: "madaram behtarin ghazaha ra mipazad",
    exampleEnglish: "My mother cooks the best food",
    difficultyLevel: 4,
  },
  {
    farsiWord: "فر",
    phonetic: "fer",
    englishTranslation: "Oven",
    exampleFarsi: "کیک را در فر گذاشتم",
    examplePhonetic: "keyk ra dar fer gozashtam",
    exampleEnglish: "I put the cake in the oven",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اجاق",
    phonetic: "ojagh",
    englishTranslation: "Stove",
    exampleFarsi: "غذا روی اجاق گاز در حال پختن است",
    examplePhonetic: "ghaza rooye ojaghe gaz dar hale pokhtan ast",
    exampleEnglish: "The food is cooking on the gas stove",
    difficultyLevel: 4,
  },
  {
    farsiWord: "دستور غذا",
    phonetic: "dastoor-e ghaza",
    englishTranslation: "Recipe",
    exampleFarsi: "دستور غذای قورمه‌سبزی را از مادربزرگم یاد گرفتم",
    examplePhonetic: "dastoore ghazaye ghorme-sabzi ra az madarbozorgam yad gereftam",
    exampleEnglish: "I learned the ghormeh sabzi recipe from my grandmother",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مواد",
    phonetic: "mavad",
    englishTranslation: "Ingredients",
    exampleFarsi: "مواد لازم برای کیک را آماده کردم",
    examplePhonetic: "mavade lazem baraye keyk ra amadeh kardam",
    exampleEnglish: "I prepared the necessary ingredients for the cake",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سرخ کردن",
    phonetic: "sorkh kardan",
    englishTranslation: "To fry",
    exampleFarsi: "پیاز را در روغن سرخ کردم",
    examplePhonetic: "piaz ra dar roghan sorkh kardam",
    exampleEnglish: "I fried the onion in oil",
    difficultyLevel: 4,
  },
  {
    farsiWord: "جوشاندن",
    phonetic: "jooshandan",
    englishTranslation: "To boil",
    exampleFarsi: "آب را برای چای جوشاندم",
    examplePhonetic: "ab ra baraye chai jooshandam",
    exampleEnglish: "I boiled water for tea",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مخلوط کردن",
    phonetic: "makhloot kardan",
    englishTranslation: "To mix",
    exampleFarsi: "آرد و شکر را با هم مخلوط کنید",
    examplePhonetic: "ard va shekar ra ba ham makhloot konid",
    exampleEnglish: "Mix the flour and sugar together",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خرد کردن",
    phonetic: "khord kardan",
    englishTranslation: "To chop",
    exampleFarsi: "سبزیجات را ریز خرد کردم",
    examplePhonetic: "sabzijat ra riz khord kardam",
    exampleEnglish: "I chopped the vegetables finely",
    difficultyLevel: 4,
  },
  {
    farsiWord: "روغن",
    phonetic: "roghan",
    englishTranslation: "Oil",
    exampleFarsi: "روغن زیتون برای سالاد عالی است",
    examplePhonetic: "roghane zeytoon baraye salad aali ast",
    exampleEnglish: "Olive oil is excellent for salad",
    difficultyLevel: 4,
  },
  {
    farsiWord: "ادویه",
    phonetic: "adviyeh",
    englishTranslation: "Spice",
    exampleFarsi: "ادویه‌های ایرانی عطر و طعم خاصی دارند",
    examplePhonetic: "adviyehaye irani atr va ta'me khassi darand",
    exampleEnglish: "Iranian spices have a special aroma and flavor",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مزه",
    phonetic: "maze",
    englishTranslation: "Taste",
    exampleFarsi: "مزه این غذا فوق‌العاده است",
    examplePhonetic: "mazeye in ghaza fogh-ol-ade ast",
    exampleEnglish: "The taste of this food is wonderful",
    difficultyLevel: 4,
  },
  {
    farsiWord: "هم زدن",
    phonetic: "ham zadan",
    englishTranslation: "To stir",
    exampleFarsi: "سوپ را مرتب هم بزنید تا ته نگیرد",
    examplePhonetic: "soop ra moratab ham bezanid ta tah nagirad",
    exampleEnglish: "Stir the soup regularly so it doesn't stick",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خام",
    phonetic: "kham",
    englishTranslation: "Raw",
    exampleFarsi: "سبزیجات خام ویتامین بیشتری دارند",
    examplePhonetic: "sabzijate kham vitamin bishtari darand",
    exampleEnglish: "Raw vegetables have more vitamins",
    difficultyLevel: 4,
  },
  {
    farsiWord: "دم کردن",
    phonetic: "dam kardan",
    englishTranslation: "To brew/steep",
    exampleFarsi: "چای را ده دقیقه دم بگذارید",
    examplePhonetic: "chai ra dah daghighe dam begozarid",
    exampleEnglish: "Let the tea steep for ten minutes",
    difficultyLevel: 4,
  },
];

// ─── 9. Cultural Vocabulary ─────────────────────────────────────────────────

const culture: WordData[] = [
  {
    farsiWord: "نوروز",
    phonetic: "norooz",
    englishTranslation: "Nowruz",
    exampleFarsi: "نوروز مهم‌ترین جشن ایرانی است",
    examplePhonetic: "norooz mohemtarin jashne irani ast",
    exampleEnglish: "Nowruz is the most important Iranian celebration",
    difficultyLevel: 4,
  },
  {
    farsiWord: "عید",
    phonetic: "eyd",
    englishTranslation: "Holiday/Eid",
    exampleFarsi: "در روزهای عید به دیدن بزرگترها می‌رویم",
    examplePhonetic: "dar roozhaye eyd be didane bozorgtarha miravim",
    exampleEnglish: "During the holidays, we visit the elders",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سنت",
    phonetic: "sonat",
    englishTranslation: "Tradition",
    exampleFarsi: "سنت‌های ایرانی بسیار غنی و متنوع هستند",
    examplePhonetic: "sonathaye irani besyar ghani va motanavve hastand",
    exampleEnglish: "Iranian traditions are very rich and diverse",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شعر",
    phonetic: "she'r",
    englishTranslation: "Poetry/Poem",
    exampleFarsi: "شعر فارسی در جهان شهرت دارد",
    examplePhonetic: "she're farsi dar jahan shohrat darad",
    exampleEnglish: "Persian poetry is famous worldwide",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شاعر",
    phonetic: "sha'er",
    englishTranslation: "Poet",
    exampleFarsi: "حافظ شاعر بزرگ ایران است",
    examplePhonetic: "hafez sha'ere bozorge iran ast",
    exampleEnglish: "Hafez is a great poet of Iran",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قالی",
    phonetic: "ghali",
    englishTranslation: "Carpet",
    exampleFarsi: "قالی ایرانی دست‌بافت در جهان معروف است",
    examplePhonetic: "ghaliye iraniye dast-baft dar jahan marouf ast",
    exampleEnglish: "Handwoven Iranian carpet is famous worldwide",
    difficultyLevel: 4,
  },
  {
    farsiWord: "چایخانه",
    phonetic: "chai-khaneh",
    englishTranslation: "Tea house",
    exampleFarsi: "در چایخانه سنتی چای و قلیان سرو می‌کنند",
    examplePhonetic: "dar chai-khaneye sonnati chai va ghalyan serv mikonand",
    exampleEnglish: "In the traditional tea house, they serve tea and hookah",
    difficultyLevel: 4,
  },
  {
    farsiWord: "خوشنویسی",
    phonetic: "khosh-nevisi",
    englishTranslation: "Calligraphy",
    exampleFarsi: "خوشنویسی فارسی هنر زیبایی است",
    examplePhonetic: "khosh-nevisiye farsi honare zibai ast",
    exampleEnglish: "Persian calligraphy is a beautiful art",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مهمان‌نوازی",
    phonetic: "mehmandoosti",
    englishTranslation: "Hospitality",
    exampleFarsi: "ایرانی‌ها به مهمان‌نوازی معروف هستند",
    examplePhonetic: "iraniha be mehmandoosti marouf hastand",
    exampleEnglish: "Iranians are known for their hospitality",
    difficultyLevel: 4,
  },
  {
    farsiWord: "احترام",
    phonetic: "ehteram-culture",
    englishTranslation: "Respect",
    exampleFarsi: "احترام به بزرگترها در فرهنگ ایرانی بسیار مهم است",
    examplePhonetic: "ehteram be bozorgtarha dar farhange irani besyar mohem ast",
    exampleEnglish: "Respect for elders is very important in Iranian culture",
    difficultyLevel: 4,
  },
  {
    farsiWord: "باستان",
    phonetic: "bastan",
    englishTranslation: "Ancient",
    exampleFarsi: "تخت جمشید از آثار باستانی ایران است",
    examplePhonetic: "takhte jamshid az asare bastaniye iran ast",
    exampleEnglish: "Persepolis is one of Iran's ancient monuments",
    difficultyLevel: 4,
  },
  {
    farsiWord: "هنر",
    phonetic: "honar",
    englishTranslation: "Art",
    exampleFarsi: "هنر ایرانی شامل مینیاتور و کاشی‌کاری است",
    examplePhonetic: "honare irani shamel miniyator va kashikari ast",
    exampleEnglish: "Iranian art includes miniature painting and tile work",
    difficultyLevel: 4,
  },
  {
    farsiWord: "دین",
    phonetic: "din",
    englishTranslation: "Religion",
    exampleFarsi: "احترام به دین و باورهای دیگران مهم است",
    examplePhonetic: "ehteram be din va bavarhaye digaran mohem ast",
    exampleEnglish: "Respecting others' religion and beliefs is important",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بازار",
    phonetic: "bazaar-culture",
    englishTranslation: "Bazaar",
    exampleFarsi: "بازار بزرگ تبریز از میراث جهانی یونسکو است",
    examplePhonetic: "bazare bozorge tabriz az mirase jahaniye yonesko ast",
    exampleEnglish: "Tabriz Grand Bazaar is a UNESCO World Heritage site",
    difficultyLevel: 4,
  },
  {
    farsiWord: "حافظ",
    phonetic: "hafez",
    englishTranslation: "Hafez (poet)",
    exampleFarsi: "غزل‌های حافظ در سراسر جهان خوانده می‌شود",
    examplePhonetic: "ghazalhaye hafez dar sarasare jahan khandeh mishavad",
    exampleEnglish: "Hafez's ghazals are read throughout the world",
    difficultyLevel: 4,
  },
  {
    farsiWord: "فردوسی",
    phonetic: "ferdowsi",
    englishTranslation: "Ferdowsi (poet)",
    exampleFarsi: "فردوسی شاهنامه را در طول سی سال نوشت",
    examplePhonetic: "ferdowsi shahnameh ra dar toole si sal nevesht",
    exampleEnglish: "Ferdowsi wrote the Shahnameh over thirty years",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مولانا",
    phonetic: "mowlana",
    englishTranslation: "Rumi",
    exampleFarsi: "مولانا شاعر عارف بزرگ ایرانی است",
    examplePhonetic: "mowlana sha'ere arefe bozorge irani ast",
    exampleEnglish: "Rumi is a great Iranian mystic poet",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تعارف",
    phonetic: "taarof",
    englishTranslation: "Taarof (politeness custom)",
    exampleFarsi: "تعارف بخش مهمی از فرهنگ ایرانی است",
    examplePhonetic: "taarof bakhshe mohemmi az farhange irani ast",
    exampleEnglish: "Taarof is an important part of Iranian culture",
    difficultyLevel: 4,
  },
];

// ─── 10. Advanced Verbs ─────────────────────────────────────────────────────

const advancedVerbs: WordData[] = [
  {
    farsiWord: "توضیح دادن",
    phonetic: "tozih dadan",
    englishTranslation: "To explain",
    exampleFarsi: "معلم درس را به خوبی توضیح داد",
    examplePhonetic: "moalem dars ra be khoobi tozih dad",
    exampleEnglish: "The teacher explained the lesson well",
    difficultyLevel: 4,
  },
  {
    farsiWord: "فهمیدن",
    phonetic: "fahmidan-adv",
    englishTranslation: "To understand",
    exampleFarsi: "بعد از توضیح استاد، مطلب را فهمیدم",
    examplePhonetic: "ba'd az tozihe ostad, matlab ra fahmidam",
    exampleEnglish: "After the professor's explanation, I understood the material",
    difficultyLevel: 4,
  },
  {
    farsiWord: "تصمیم گرفتن",
    phonetic: "tasmim-gereftan",
    englishTranslation: "To decide",
    exampleFarsi: "تصمیم گرفتم رشته پزشکی بخوانم",
    examplePhonetic: "tasmim gereftam reshteye pezeshki bekhaanam",
    exampleEnglish: "I decided to study medicine",
    difficultyLevel: 4,
  },
  {
    farsiWord: "قول دادن",
    phonetic: "gho'l dadan",
    englishTranslation: "To promise",
    exampleFarsi: "قول دادم که به موقع برسم",
    examplePhonetic: "ghol dadam ke be moghe beresam",
    exampleEnglish: "I promised to arrive on time",
    difficultyLevel: 4,
  },
  {
    farsiWord: "پیشنهاد دادن",
    phonetic: "pishnahad dadan",
    englishTranslation: "To suggest",
    exampleFarsi: "دوستم پیشنهاد داد به رستوران ایتالیایی برویم",
    examplePhonetic: "doostam pishnahad dad be restorane italiyai beravim",
    exampleEnglish: "My friend suggested we go to an Italian restaurant",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شکایت کردن",
    phonetic: "shekayat kardan",
    englishTranslation: "To complain",
    exampleFarsi: "مشتری از کیفیت محصول شکایت کرد",
    examplePhonetic: "moshtari az keyfiyate mahsool shekayat kard",
    exampleEnglish: "The customer complained about the product quality",
    difficultyLevel: 4,
  },
  {
    farsiWord: "عذر خواستن",
    phonetic: "ozr khaastan",
    englishTranslation: "To apologize",
    exampleFarsi: "بابت تأخیرم عذر خواستم",
    examplePhonetic: "babate ta'khiram ozr khastam",
    exampleEnglish: "I apologized for my delay",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بخشیدن",
    phonetic: "bakhshidan",
    englishTranslation: "To forgive",
    exampleFarsi: "لطفاً مرا ببخشید، اشتباه کردم",
    examplePhonetic: "lotfan mara bebakhshid, eshtebah kardam",
    exampleEnglish: "Please forgive me, I made a mistake",
    difficultyLevel: 4,
  },
  {
    farsiWord: "موفق شدن",
    phonetic: "movaffagh shodan",
    englishTranslation: "To succeed",
    exampleFarsi: "با تلاش و پشتکار موفق شد",
    examplePhonetic: "ba talash va poshtkar movaffagh shod",
    exampleEnglish: "He succeeded through effort and perseverance",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شکست خوردن",
    phonetic: "shekast khordan",
    englishTranslation: "To fail",
    exampleFarsi: "اگر تلاش نکنی، شکست می‌خوری",
    examplePhonetic: "agar talash nakoni, shekast mikhori",
    exampleEnglish: "If you don't try, you will fail",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مقایسه کردن",
    phonetic: "moghayese kardan",
    englishTranslation: "To compare",
    exampleFarsi: "قبل از خرید، قیمت‌ها را مقایسه کنید",
    examplePhonetic: "ghabl az kharid, gheymatha ra moghayese konid",
    exampleEnglish: "Compare prices before buying",
    difficultyLevel: 4,
  },
  {
    farsiWord: "بهبود دادن",
    phonetic: "behbood dadan",
    englishTranslation: "To improve",
    exampleFarsi: "باید کیفیت خدمات را بهبود دهیم",
    examplePhonetic: "bayad keyfiyate khadamat ra behbood dahim",
    exampleEnglish: "We must improve the quality of services",
    difficultyLevel: 4,
  },
  {
    farsiWord: "آماده کردن",
    phonetic: "amade kardan",
    englishTranslation: "To prepare",
    exampleFarsi: "ارائه فردا را آماده کردم",
    examplePhonetic: "era'eye farda ra amadeh kardam",
    exampleEnglish: "I prepared tomorrow's presentation",
    difficultyLevel: 4,
  },
  {
    farsiWord: "سازماندهی کردن",
    phonetic: "sazmaandahi kardan",
    englishTranslation: "To organize",
    exampleFarsi: "کنفرانس بین‌المللی را سازماندهی کردیم",
    examplePhonetic: "konferanse beynolmelali ra sazmaandahi kardim",
    exampleEnglish: "We organized the international conference",
    difficultyLevel: 4,
  },
  {
    farsiWord: "توسعه دادن",
    phonetic: "tose'e dadan",
    englishTranslation: "To develop",
    exampleFarsi: "شرکت محصول جدیدی را توسعه داده است",
    examplePhonetic: "sherkat mahsoole jadidi ra tose'e dade ast",
    exampleEnglish: "The company has developed a new product",
    difficultyLevel: 4,
  },
  {
    farsiWord: "شرکت کردن",
    phonetic: "sherkat-kardan",
    englishTranslation: "To participate",
    exampleFarsi: "در مسابقه دو و میدانی شرکت کردم",
    examplePhonetic: "dar mosabegheye do va meydani sherkat kardam",
    exampleEnglish: "I participated in the track and field competition",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اعلام کردن",
    phonetic: "e'lam kardan",
    englishTranslation: "To announce",
    exampleFarsi: "نتایج نهایی را فردا اعلام می‌کنند",
    examplePhonetic: "natayeje nahayi ra farda e'lam mikonand",
    exampleEnglish: "They will announce the final results tomorrow",
    difficultyLevel: 4,
  },
  {
    farsiWord: "توصیه کردن",
    phonetic: "towsiye kardan",
    englishTranslation: "To recommend",
    exampleFarsi: "دکتر استراحت کامل را توصیه کرد",
    examplePhonetic: "doktor esterahate kamel ra towsiye kard",
    exampleEnglish: "The doctor recommended complete rest",
    difficultyLevel: 4,
  },
];

// ─── 11. Connectors & Discourse ─────────────────────────────────────────────

const connectors: WordData[] = [
  {
    farsiWord: "بنابراین",
    phonetic: "banabarin",
    englishTranslation: "Therefore",
    exampleFarsi: "هوا بارانی است، بنابراین چتر ببرید",
    examplePhonetic: "hava barani ast, banabarin chatr bebarid",
    exampleEnglish: "It's rainy, therefore take an umbrella",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به علاوه",
    phonetic: "be alave",
    englishTranslation: "Moreover",
    exampleFarsi: "این رستوران غذای خوبی دارد، به علاوه قیمتش هم مناسب است",
    examplePhonetic: "in restooran ghazaye khoobi darad, be alave gheymtash ham monaseb ast",
    exampleEnglish: "This restaurant has good food, moreover its prices are reasonable",
    difficultyLevel: 4,
  },
  {
    farsiWord: "همچنین",
    phonetic: "hamchenin",
    englishTranslation: "Also/Furthermore",
    exampleFarsi: "او دکتر است و همچنین نویسنده‌ای موفق",
    examplePhonetic: "oo doktor ast va hamchenin nevisandeyi movaffagh",
    exampleEnglish: "She is a doctor and also a successful writer",
    difficultyLevel: 4,
  },
  {
    farsiWord: "اگرچه",
    phonetic: "agarcheh",
    englishTranslation: "Although",
    exampleFarsi: "اگرچه خسته بودم، اما به کارم ادامه دادم",
    examplePhonetic: "agarcheh khaste boodam, amma be karam edame dadam",
    exampleEnglish: "Although I was tired, I continued my work",
    difficultyLevel: 4,
  },
  {
    farsiWord: "با وجود",
    phonetic: "ba vojood",
    englishTranslation: "Despite",
    exampleFarsi: "با وجود مشکلات، از تلاش دست نکشید",
    examplePhonetic: "ba vojoode moshkelat, az talash dast nakeshid",
    exampleEnglish: "Despite the problems, he didn't give up trying",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به جای",
    phonetic: "be jaye",
    englishTranslation: "Instead of",
    exampleFarsi: "به جای تاکسی، با مترو رفتم",
    examplePhonetic: "be jaye taksi, ba metro raftam",
    exampleEnglish: "Instead of a taxi, I went by metro",
    difficultyLevel: 4,
  },
  {
    farsiWord: "در این حال",
    phonetic: "dar in hal",
    englishTranslation: "Meanwhile",
    exampleFarsi: "من غذا پختم، در این حال او میز را چید",
    examplePhonetic: "man ghaza pokhtam, dar in hal oo miz ra chid",
    exampleEnglish: "I cooked the food, meanwhile she set the table",
    difficultyLevel: 4,
  },
  {
    farsiWord: "وگرنه",
    phonetic: "varna",
    englishTranslation: "Otherwise",
    exampleFarsi: "زود بیا، وگرنه دیر می‌شود",
    examplePhonetic: "zood biya, varna dir mishavad",
    exampleEnglish: "Come early, otherwise it will be late",
    difficultyLevel: 4,
  },
  {
    farsiWord: "در واقع",
    phonetic: "dar vagheh",
    englishTranslation: "In fact",
    exampleFarsi: "در واقع، مشکل خیلی ساده‌تر از آن بود که فکر می‌کردیم",
    examplePhonetic: "dar vagheh, moshkel kheyli sadetar az an bood ke fekr mikardim",
    exampleEnglish: "In fact, the problem was much simpler than we thought",
    difficultyLevel: 4,
  },
  {
    farsiWord: "مثلاً",
    phonetic: "masalan",
    englishTranslation: "For example",
    exampleFarsi: "ورزش‌های مختلفی هست، مثلاً فوتبال و والیبال",
    examplePhonetic: "varzeshhaye mokhtalafi hast, masalan footbal va valibal",
    exampleEnglish: "There are various sports, for example football and volleyball",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به عبارت دیگر",
    phonetic: "be ebarate digar",
    englishTranslation: "In other words",
    exampleFarsi: "او فارغ‌التحصیل شد، به عبارت دیگر تحصیلاتش تمام شد",
    examplePhonetic: "oo faregh-ol-tahsil shod, be ebarate digar tahsilatash tamam shod",
    exampleEnglish: "He graduated, in other words he finished his studies",
    difficultyLevel: 4,
  },
  {
    farsiWord: "از طرف دیگر",
    phonetic: "az tarafe digar",
    englishTranslation: "On the other hand",
    exampleFarsi: "این شهر شلوغ است، از طرف دیگر امکانات زیادی دارد",
    examplePhonetic: "in shahr sholoogh ast, az tarafe digar emkanat ziadi darad",
    exampleEnglish: "This city is crowded, on the other hand it has many amenities",
    difficultyLevel: 4,
  },
  {
    farsiWord: "در نتیجه",
    phonetic: "dar natijeh",
    englishTranslation: "As a result",
    exampleFarsi: "سخت درس خواند، در نتیجه نمره خوبی گرفت",
    examplePhonetic: "sakht dars khand, dar natijeh nomreye khoobi gereft",
    exampleEnglish: "He studied hard, as a result he got a good grade",
    difficultyLevel: 4,
  },
  {
    farsiWord: "با این حال",
    phonetic: "ba in hal",
    englishTranslation: "Nevertheless",
    exampleFarsi: "بارانی بود، با این حال به پیاده‌روی رفتیم",
    examplePhonetic: "barani bood, ba in hal be piaderuyi raftim",
    exampleEnglish: "It was rainy, nevertheless we went for a walk",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به هر حال",
    phonetic: "be har hal",
    englishTranslation: "Anyway",
    exampleFarsi: "به هر حال، ممنون از وقتی که گذاشتید",
    examplePhonetic: "be har hal, mamnoon az vaghti ke gozashtid",
    exampleEnglish: "Anyway, thank you for your time",
    difficultyLevel: 4,
  },
  {
    farsiWord: "از این رو",
    phonetic: "az in ro",
    englishTranslation: "Hence",
    exampleFarsi: "تقاضا افزایش یافت، از این رو قیمت‌ها بالا رفت",
    examplePhonetic: "taghaza afzayesh yaft, az in ro gheymatha bala raft",
    exampleEnglish: "Demand increased, hence prices went up",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به دلیل",
    phonetic: "be dalile",
    englishTranslation: "Due to",
    exampleFarsi: "به دلیل ترافیک سنگین، دیر رسیدم",
    examplePhonetic: "be dalile terafike sangin, dir residam",
    exampleEnglish: "Due to heavy traffic, I arrived late",
    difficultyLevel: 4,
  },
  {
    farsiWord: "به طور کلی",
    phonetic: "be tore kolli",
    englishTranslation: "Generally",
    exampleFarsi: "به طور کلی، مردم ایران مهمان‌نواز هستند",
    examplePhonetic: "be tore kolli, mardome iran mehmandoost hastand",
    exampleEnglish: "Generally, Iranian people are hospitable",
    difficultyLevel: 4,
  },
];

// ─── Seed Function ──────────────────────────────────────────────────────────

export async function seedLevel4() {
  console.log("\n=== Level 4: Intermediate ===\n");
  let total = 0;

  const r1 = await seedCategory({
    name: "Formal Expressions",
    slug: "formal-expressions",
    description: "Formal and professional expressions for official settings",
    icon: "🎩",
    level: 4,
    sortOrder: 1,
    words: formalExpressions,
  });
  total += r1.wordsAdded;

  const r2 = await seedCategory({
    name: "Feelings & Mental States",
    slug: "mental-states",
    description: "Advanced feelings, mental states, and personality traits",
    icon: "🧠",
    level: 4,
    sortOrder: 2,
    words: mentalStates,
  });
  total += r2.wordsAdded;

  const r3 = await seedCategory({
    name: "Law & Government",
    slug: "law-government",
    description: "Legal, political, and governmental vocabulary",
    icon: "⚖️",
    level: 4,
    sortOrder: 3,
    words: lawGovernment,
  });
  total += r3.wordsAdded;

  const r4 = await seedCategory({
    name: "Media & News",
    slug: "media-news",
    description: "Media, journalism, and news-related vocabulary",
    icon: "📰",
    level: 4,
    sortOrder: 4,
    words: mediaNews,
  });
  total += r4.wordsAdded;

  const r5 = await seedCategory({
    name: "Banking & Finance",
    slug: "banking-finance",
    description: "Banking, finance, and economic vocabulary",
    icon: "🏦",
    level: 4,
    sortOrder: 5,
    words: bankingFinance,
  });
  total += r5.wordsAdded;

  const r6 = await seedCategory({
    name: "Housing & Real Estate",
    slug: "housing",
    description: "Housing, real estate, and residential vocabulary",
    icon: "🏘️",
    level: 4,
    sortOrder: 6,
    words: housing,
  });
  total += r6.wordsAdded;

  const r7 = await seedCategory({
    name: "Education Advanced",
    slug: "education-advanced",
    description: "Advanced academic and university vocabulary",
    icon: "🎓",
    level: 4,
    sortOrder: 7,
    words: educationAdvanced,
  });
  total += r7.wordsAdded;

  const r8 = await seedCategory({
    name: "Cooking & Kitchen",
    slug: "cooking-kitchen",
    description: "Cooking techniques, kitchen tools, and food preparation",
    icon: "👨‍🍳",
    level: 4,
    sortOrder: 8,
    words: cookingKitchen,
  });
  total += r8.wordsAdded;

  const r9 = await seedCategory({
    name: "Cultural Vocabulary",
    slug: "culture",
    description: "Iranian culture, traditions, arts, and famous figures",
    icon: "🕌",
    level: 4,
    sortOrder: 9,
    words: culture,
  });
  total += r9.wordsAdded;

  const r10 = await seedCategory({
    name: "Advanced Verbs",
    slug: "advanced-verbs",
    description: "Complex verbs for formal and professional communication",
    icon: "🎯",
    level: 4,
    sortOrder: 10,
    words: advancedVerbs,
  });
  total += r10.wordsAdded;

  const r11 = await seedCategory({
    name: "Connectors & Discourse",
    slug: "connectors",
    description: "Discourse markers, connectors, and linking expressions",
    icon: "🔗",
    level: 4,
    sortOrder: 11,
    words: connectors,
  });
  total += r11.wordsAdded;

  console.log(`\nLevel 4 complete: ${total} new words added\n`);
  return total;
}
