import "dotenv/config";
import { seedCategory, type WordData } from "./seed-helpers";

// ─── 1. Academic & Professional ─────────────────────────────────────────────

const academicProfessional: WordData[] = [
  {
    farsiWord: "کنفرانس",
    phonetic: "konferans",
    englishTranslation: "Conference",
    exampleFarsi: "کنفرانس بین‌المللی علوم کامپیوتر هفته آینده برگزار می‌شود",
    examplePhonetic: "konferanse beynolmelali oloome kampyooter hafteye ayandeh bargozar mishavad",
    exampleEnglish: "The international computer science conference will be held next week",
    difficultyLevel: 5,
  },
  {
    farsiWord: "ارائه",
    phonetic: "araye",
    englishTranslation: "Presentation",
    exampleFarsi: "ارائه تحقیقاتم در کنفرانس مورد توجه قرار گرفت",
    examplePhonetic: "arayeye tahghighatam dar konferans morede tavajoh gharar gereft",
    exampleEnglish: "My research presentation received attention at the conference",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تجزیه و تحلیل",
    phonetic: "tajziye va tahlil",
    englishTranslation: "Analysis",
    exampleFarsi: "تجزیه و تحلیل داده‌ها نتایج جالبی را نشان داد",
    examplePhonetic: "tajziye va tahlile dadeha natayeje jalebi ra neshan dad",
    exampleEnglish: "The data analysis revealed interesting results",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مدیریت",
    phonetic: "modiriyat",
    englishTranslation: "Management",
    exampleFarsi: "مدیریت پروژه‌های بزرگ به تجربه و مهارت نیاز دارد",
    examplePhonetic: "modiriyate prozhehaye bozorg be tajrobe va maharat niyaz darad",
    exampleEnglish: "Managing large projects requires experience and skill",
    difficultyLevel: 5,
  },
  {
    farsiWord: "نظریه",
    phonetic: "nazariyeh",
    englishTranslation: "Theory",
    exampleFarsi: "نظریه نسبیت اینشتین فیزیک را متحول کرد",
    examplePhonetic: "nazariyeye nesbiyate einstein fizik ra motehavvel kard",
    exampleEnglish: "Einstein's theory of relativity transformed physics",
    difficultyLevel: 5,
  },
  {
    farsiWord: "نتیجه‌گیری",
    phonetic: "natijeh-giri",
    englishTranslation: "Conclusion",
    exampleFarsi: "نتیجه‌گیری مقاله باید خلاصه و روشن باشد",
    examplePhonetic: "natijeh-giriye maghaleh bayad kholase va roshan bashad",
    exampleEnglish: "The conclusion of the paper should be concise and clear",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مرجع",
    phonetic: "marja",
    englishTranslation: "Reference",
    exampleFarsi: "لطفاً منابع و مراجع مقاله را به‌درستی ذکر کنید",
    examplePhonetic: "lotfan manabe va maraje'e maghaleh ra be dorosti zekr konid",
    exampleEnglish: "Please cite the paper's sources and references correctly",
    difficultyLevel: 5,
  },
  {
    farsiWord: "روش‌شناسی",
    phonetic: "ravesh-shenasi",
    englishTranslation: "Methodology",
    exampleFarsi: "روش‌شناسی این تحقیق بر مبنای روش کیفی است",
    examplePhonetic: "ravesh-shenasiye in tahghigh bar mabnaye raveshe keyfi ast",
    exampleEnglish: "The methodology of this research is based on a qualitative approach",
    difficultyLevel: 5,
  },
  {
    farsiWord: "فرضیه",
    phonetic: "farziyeh",
    englishTranslation: "Hypothesis",
    exampleFarsi: "فرضیه اولیه ما با نتایج آزمایش تأیید شد",
    examplePhonetic: "farziyeye avvaliyeye ma ba natayeje azmayesh ta'yid shod",
    exampleEnglish: "Our initial hypothesis was confirmed by the experiment results",
    difficultyLevel: 5,
  },
  {
    farsiWord: "داده‌ها",
    phonetic: "dade-ha",
    englishTranslation: "Data",
    exampleFarsi: "داده‌های جمع‌آوری شده باید به دقت پردازش شوند",
    examplePhonetic: "dadehaye jam'avari shodeh bayad be deghat pardazesh shavand",
    exampleEnglish: "The collected data must be processed carefully",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مدرک",
    phonetic: "madrak-acad",
    englishTranslation: "Evidence",
    exampleFarsi: "مدرک کافی برای اثبات این ادعا وجود ندارد",
    examplePhonetic: "madrake kafi baraye esbate in edde'a vojood nadarad",
    exampleEnglish: "There is not enough evidence to prove this claim",
    difficultyLevel: 5,
  },
  {
    farsiWord: "ارزیابی کردن",
    phonetic: "arziyabi kardan",
    englishTranslation: "To evaluate",
    exampleFarsi: "عملکرد کارکنان هر سه ماه ارزیابی می‌شود",
    examplePhonetic: "amalkarde karkonan har se mah arziyabi mishavad",
    exampleEnglish: "Employee performance is evaluated every three months",
    difficultyLevel: 5,
  },
  {
    farsiWord: "معیار",
    phonetic: "me'yar",
    englishTranslation: "Criteria",
    exampleFarsi: "معیارهای پذیرش در این دانشگاه بسیار سخت‌گیرانه است",
    examplePhonetic: "me'yarhaye paziresh dar in daneshgah besyar sakht-giraneh ast",
    exampleEnglish: "The admission criteria at this university are very strict",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مشارکت",
    phonetic: "mosharekat",
    englishTranslation: "Contribution",
    exampleFarsi: "مشارکت فعال دانشجویان در کلاس ضروری است",
    examplePhonetic: "mosharekate fa'ale daneshjooyan dar kelas zaroori ast",
    exampleEnglish: "Active contribution of students in class is essential",
    difficultyLevel: 5,
  },
  {
    farsiWord: "نوآوری",
    phonetic: "noavari",
    englishTranslation: "Innovation",
    exampleFarsi: "نوآوری در فناوری باعث پیشرفت جامعه می‌شود",
    examplePhonetic: "noavari dar fanavari ba'ese pishrafte jame'eh mishavad",
    exampleEnglish: "Innovation in technology drives the progress of society",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تخصصی",
    phonetic: "takhassosi",
    englishTranslation: "Specialized",
    exampleFarsi: "این مجله تخصصی در زمینه پزشکی منتشر می‌شود",
    examplePhonetic: "in majaleye takhassosi dar zamineye pezeshki montasher mishavad",
    exampleEnglish: "This specialized journal is published in the field of medicine",
    difficultyLevel: 5,
  },
  {
    farsiWord: "استراتژی",
    phonetic: "estratezhi",
    englishTranslation: "Strategy",
    exampleFarsi: "شرکت استراتژی جدیدی برای توسعه بازار تدوین کرد",
    examplePhonetic: "sherkat estratezhiye jadidi baraye tose'eye bazar tadvin kard",
    exampleEnglish: "The company formulated a new strategy for market expansion",
    difficultyLevel: 5,
  },
  {
    farsiWord: "پیشرفت",
    phonetic: "pishraft",
    englishTranslation: "Progress",
    exampleFarsi: "پیشرفت چشمگیری در زمینه هوش مصنوعی صورت گرفته است",
    examplePhonetic: "pishrafte cheshmgiri dar zamineye hooshe masnooi soorat gerefte ast",
    exampleEnglish: "Significant progress has been made in the field of artificial intelligence",
    difficultyLevel: 5,
  },
];

// ─── 2. Nuanced Emotions ────────────────────────────────────────────────────

const nuancedEmotions: WordData[] = [
  {
    farsiWord: "دلتنگ",
    phonetic: "deltang",
    englishTranslation: "Nostalgic/Homesick",
    exampleFarsi: "از وقتی از ایران رفتم، خیلی دلتنگ خانواده‌ام هستم",
    examplePhonetic: "az vaghti az iran raftam, kheyli deltange khanevadeam hastam",
    exampleEnglish: "Since I left Iran, I am very homesick for my family",
    difficultyLevel: 5,
  },
  {
    farsiWord: "غمگین",
    phonetic: "ghamgin",
    englishTranslation: "Sorrowful",
    exampleFarsi: "شنیدن آن خبر همه را غمگین کرد",
    examplePhonetic: "shenidane an khabar hame ra ghamgin kard",
    exampleEnglish: "Hearing that news made everyone sorrowful",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دلسوز",
    phonetic: "delsoz",
    englishTranslation: "Compassionate",
    exampleFarsi: "او پرستاری دلسوز است و همیشه به بیماران کمک می‌کند",
    examplePhonetic: "oo parastari delsoz ast va hamishe be bimaran komak mikonad",
    exampleEnglish: "She is a compassionate nurse who always helps the patients",
    difficultyLevel: 5,
  },
  {
    farsiWord: "فروتن",
    phonetic: "forutan",
    englishTranslation: "Humble",
    exampleFarsi: "با وجود موفقیت‌هایش، او آدم بسیار فروتنی است",
    examplePhonetic: "ba vojoode movaffaghiyathayash, oo adame besyar forutani ast",
    exampleEnglish: "Despite his successes, he is a very humble person",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دانا",
    phonetic: "dana",
    englishTranslation: "Wise",
    exampleFarsi: "پدربزرگم مرد دانا و باتجربه‌ای است",
    examplePhonetic: "pedarbozorgam marde dana va ba tajrobeyi ast",
    exampleEnglish: "My grandfather is a wise and experienced man",
    difficultyLevel: 5,
  },
  {
    farsiWord: "وفادار",
    phonetic: "vafadar",
    englishTranslation: "Loyal",
    exampleFarsi: "او دوستی وفادار است که همیشه در کنارم بوده",
    examplePhonetic: "oo doosti vafadar ast ke hamishe dar kenaram boode",
    exampleEnglish: "He is a loyal friend who has always been by my side",
    difficultyLevel: 5,
  },
  {
    farsiWord: "بدبین",
    phonetic: "badbin",
    englishTranslation: "Pessimistic",
    exampleFarsi: "نسبت به آینده بدبین نباشید، همه چیز درست می‌شود",
    examplePhonetic: "nesbat be ayandeh badbin nabashid, hame chiz dorost mishavad",
    exampleEnglish: "Don't be pessimistic about the future, everything will be fine",
    difficultyLevel: 5,
  },
  {
    farsiWord: "خوش‌بین",
    phonetic: "khoshbin",
    englishTranslation: "Optimistic",
    exampleFarsi: "او همیشه نسبت به زندگی خوش‌بین است",
    examplePhonetic: "oo hamishe nesbat be zendegi khoshbin ast",
    exampleEnglish: "She is always optimistic about life",
    difficultyLevel: 5,
  },
  {
    farsiWord: "پرشور",
    phonetic: "porshoor",
    englishTranslation: "Enthusiastic",
    exampleFarsi: "دانشجویان پرشور و با انگیزه در کلاس شرکت کردند",
    examplePhonetic: "daneshjooyan porshoor va ba angize dar kelas sherkat kardand",
    exampleEnglish: "The enthusiastic and motivated students participated in class",
    difficultyLevel: 5,
  },
  {
    farsiWord: "بی‌حوصله",
    phonetic: "bi-howseleh",
    englishTranslation: "Impatient",
    exampleFarsi: "بچه‌ها بعد از مدتی بی‌حوصله شدند و شروع به شلوغ کردن کردند",
    examplePhonetic: "bacheha ba'd az moddati bi-howseleh shodand va shoro' be sholoogh kardan kardand",
    exampleEnglish: "The children became impatient after a while and started making noise",
    difficultyLevel: 5,
  },
  {
    farsiWord: "سرخورده",
    phonetic: "sarkhordeh",
    englishTranslation: "Disillusioned",
    exampleFarsi: "بعد از سال‌ها تلاش بی‌نتیجه، کاملاً سرخورده شده بود",
    examplePhonetic: "ba'd az salha talashe bi-natijeh, kamelan sarkhordeh shode bood",
    exampleEnglish: "After years of fruitless effort, he had become completely disillusioned",
    difficultyLevel: 5,
  },
  {
    farsiWord: "بی‌تاب",
    phonetic: "bi-tab",
    englishTranslation: "Restless",
    exampleFarsi: "از بی‌تابی نمی‌توانست بنشیند و منتظر نتیجه باشد",
    examplePhonetic: "az bi-tabi nemitavanest beneshinad va montazere natijeh bashad",
    exampleEnglish: "He was so restless that he couldn't sit and wait for the result",
    difficultyLevel: 5,
  },
  {
    farsiWord: "حسرتمند",
    phonetic: "hasratmand",
    englishTranslation: "Regretful/Longing",
    exampleFarsi: "با نگاهی حسرتمند به عکس‌های قدیمی نگاه می‌کرد",
    examplePhonetic: "ba negahi hasratmand be akshaye ghadimi negah mikard",
    exampleEnglish: "She looked at the old photos with a longing gaze",
    difficultyLevel: 5,
  },
  {
    farsiWord: "باوقار",
    phonetic: "ba-veghar",
    englishTranslation: "Dignified",
    exampleFarsi: "او زنی باوقار و محترم بود که همه احترامش می‌گذاشتند",
    examplePhonetic: "oo zani ba-veghar va mohtaram bood ke hame ehteramash migozashtand",
    exampleEnglish: "She was a dignified and respected woman whom everyone respected",
    difficultyLevel: 5,
  },
  {
    farsiWord: "سوزناک",
    phonetic: "sooznak",
    englishTranslation: "Heartbreaking",
    exampleFarsi: "داستان زندگی او بسیار سوزناک و تأثیرگذار بود",
    examplePhonetic: "dastane zendegiye oo besyar sooznak va ta'sirgozar bood",
    exampleEnglish: "The story of his life was very heartbreaking and moving",
    difficultyLevel: 5,
  },
];

// ─── 3. Proverbs & Idioms ───────────────────────────────────────────────────

const proverbsIdioms: WordData[] = [
  {
    farsiWord: "آب از آب تکان نخورد",
    phonetic: "ab az ab tekan nakhord",
    englishTranslation: "Nothing happened (lit: water didn't move from water)",
    exampleFarsi: "بعد از آن همه سر و صدا، آب از آب تکان نخورد",
    examplePhonetic: "ba'd az an hame sar o seda, ab az ab tekan nakhord",
    exampleEnglish: "After all that commotion, nothing happened at all",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دست از سرم بردار",
    phonetic: "dast az saram bardar",
    englishTranslation: "Leave me alone",
    exampleFarsi: "دست از سرم بردار، حوصله بحث کردن ندارم",
    examplePhonetic: "dast az saram bardar, howseleye bahs kardan nadaram",
    exampleEnglish: "Leave me alone, I'm not in the mood for arguing",
    difficultyLevel: 5,
  },
  {
    farsiWord: "سرش به تنش نمی‌ارزد",
    phonetic: "sarash be tanash nemiarzad",
    englishTranslation: "Not worth the trouble",
    exampleFarsi: "این کار آنقدر سخت است که سرش به تنش نمی‌ارزد",
    examplePhonetic: "in kar anghadr sakht ast ke sarash be tanash nemiarzad",
    exampleEnglish: "This task is so difficult that it's not worth the trouble",
    difficultyLevel: 5,
  },
  {
    farsiWord: "هر که بامش بیش برفش بیشتر",
    phonetic: "har ke bamash bish barfash bishtar",
    englishTranslation: "The more you have, the more responsibility",
    exampleFarsi: "مدیر شرکت بزرگ مسئولیت سنگینی دارد؛ هر که بامش بیش برفش بیشتر",
    examplePhonetic: "modire sherkate bozorg mas'ooliyate sangini darad; har ke bamash bish barfash bishtar",
    exampleEnglish: "The manager of a big company has heavy responsibilities; the more you have, the more responsibility",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تا نباشد چیزکی مردم نگویند چیزها",
    phonetic: "ta nabashad chizaki mardom naguyand chizha",
    englishTranslation: "Nothing comes from nothing / Where there's smoke there's fire",
    exampleFarsi: "مردم بی‌دلیل حرف نمی‌زنند؛ تا نباشد چیزکی مردم نگویند چیزها",
    examplePhonetic: "mardom bi-dalil harf nemizanand; ta nabashad chizaki mardom naguyand chizha",
    exampleEnglish: "People don't talk without reason; where there's smoke, there's fire",
    difficultyLevel: 5,
  },
  {
    farsiWord: "کار نیکو کردن از پر کردن است",
    phonetic: "kare niko kardan az por kardan ast",
    englishTranslation: "Doing good is satisfying",
    exampleFarsi: "به دیگران کمک کن؛ کار نیکو کردن از پر کردن است",
    examplePhonetic: "be digaran komak kon; kare niko kardan az por kardan ast",
    exampleEnglish: "Help others; doing good deeds is truly fulfilling",
    difficultyLevel: 5,
  },
  {
    farsiWord: "آش نخورده و دهان سوخته",
    phonetic: "ash nakhorde va dahan sookhteh",
    englishTranslation: "Punished without cause",
    exampleFarsi: "من کاری نکرده بودم ولی سرزنش شدم؛ آش نخورده و دهان سوخته",
    examplePhonetic: "man kari nakarde boodam vali sarzanesh shodam; ash nakhorde va dahan sookhteh",
    exampleEnglish: "I hadn't done anything but was blamed; punished without cause",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مرغ همسایه غاز است",
    phonetic: "morghe hamsaye ghaz ast",
    englishTranslation: "The grass is greener on the other side",
    exampleFarsi: "همیشه فکر می‌کنی زندگی دیگران بهتر است؛ مرغ همسایه غاز است",
    examplePhonetic: "hamishe fekr mikoni zendegiye digaran behtar ast; morghe hamsaye ghaz ast",
    exampleEnglish: "You always think others have it better; the grass is always greener",
    difficultyLevel: 5,
  },
  {
    farsiWord: "از ماست که بر ماست",
    phonetic: "az mast ke bar mast",
    englishTranslation: "We brought it on ourselves",
    exampleFarsi: "مشکلات کنونی نتیجه اشتباهات خودمان است؛ از ماست که بر ماست",
    examplePhonetic: "moshkelate konuni natijeh eshtebahate khodeman ast; az mast ke bar mast",
    exampleEnglish: "The current problems are the result of our own mistakes; we brought it on ourselves",
    difficultyLevel: 5,
  },
  {
    farsiWord: "جوینده یابنده است",
    phonetic: "joyandeh yabandeh ast",
    englishTranslation: "Seekers shall find",
    exampleFarsi: "ناامید نشو و به تلاشت ادامه بده؛ جوینده یابنده است",
    examplePhonetic: "na-omid nasho va be talashat edame bede; joyandeh yabandeh ast",
    exampleEnglish: "Don't lose hope and keep trying; seekers shall find",
    difficultyLevel: 5,
  },
  {
    farsiWord: "با یک دست نمی‌شود دو هندوانه برداشت",
    phonetic: "ba yek dast nemishavad do hendevaneh bardasht",
    englishTranslation: "Can't do two things at once",
    exampleFarsi: "نمی‌توانی هم کار کنی هم درس بخوانی؛ با یک دست نمی‌شود دو هندوانه برداشت",
    examplePhonetic: "nemitavani ham kar koni ham dars bekhani; ba yek dast nemishavad do hendevaneh bardasht",
    exampleEnglish: "You can't work and study at the same time; you can't do two things at once",
    difficultyLevel: 5,
  },
  {
    farsiWord: "نابرده رنج گنج میسر نمی‌شود",
    phonetic: "naborde ranj ganj moyassar nemishavad",
    englishTranslation: "No pain, no gain",
    exampleFarsi: "برای موفقیت باید سخت تلاش کنی؛ نابرده رنج گنج میسر نمی‌شود",
    examplePhonetic: "baraye movaffaghiyat bayad sakht talash koni; naborde ranj ganj moyassar nemishavad",
    exampleEnglish: "You must work hard for success; no pain, no gain",
    difficultyLevel: 5,
  },
  {
    farsiWord: "یک بام و دو هوا",
    phonetic: "yek bam o do hava",
    englishTranslation: "Double standards",
    exampleFarsi: "نمی‌شود یک بام و دو هوا باشد؛ قانون باید برای همه یکسان باشد",
    examplePhonetic: "nemishavad yek bam o do hava bashad; ghanoon bayad baraye hame yeksan bashad",
    exampleEnglish: "There can't be double standards; the law should be the same for everyone",
    difficultyLevel: 5,
  },
  {
    farsiWord: "هر چه کنی به خود کنی",
    phonetic: "har che koni be khod koni",
    englishTranslation: "What goes around comes around",
    exampleFarsi: "به دیگران بدی نکن؛ هر چه کنی به خود کنی",
    examplePhonetic: "be digaran badi nakon; har che koni be khod koni",
    exampleEnglish: "Don't do evil to others; what goes around comes around",
    difficultyLevel: 5,
  },
  {
    farsiWord: "آب که از سر گذشت چه یک نیزه چه صد نیزه",
    phonetic: "ab ke az sar gozasht che yek neyzeh che sad neyzeh",
    englishTranslation: "When it's too late, it doesn't matter how bad it gets",
    exampleFarsi: "حالا که اوضاع خراب شده، فرقی نمی‌کند؛ آب که از سر گذشت چه یک نیزه چه صد نیزه",
    examplePhonetic: "hala ke owza' kharab shode, farghi nemikonad; ab ke az sar gozasht che yek neyzeh che sad neyzeh",
    exampleEnglish: "Now that things have gone bad, it doesn't matter; when you're already in deep, it makes no difference",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تخم مرغ دزد شتر دزد می‌شود",
    phonetic: "tokhme morgh dozd shotor dozd mishavad",
    englishTranslation: "Small crimes lead to big ones",
    exampleFarsi: "از کارهای کوچک غلط چشم‌پوشی نکنید؛ تخم مرغ دزد شتر دزد می‌شود",
    examplePhonetic: "az karhaye koochake ghalat cheshmposhi nakonid; tokhme morgh dozd shotor dozd mishavad",
    exampleEnglish: "Don't overlook small wrongdoings; small crimes lead to big ones",
    difficultyLevel: 5,
  },
  {
    farsiWord: "چراغ را باید زیر پای خود گرفت",
    phonetic: "cheragh ra bayad zire paye khod gereft",
    englishTranslation: "Charity begins at home / Start with yourself",
    exampleFarsi: "قبل از نصیحت کردن دیگران، چراغ را باید زیر پای خود گرفت",
    examplePhonetic: "ghabl az nasihat kardane digaran, cheragh ra bayad zire paye khod gereft",
    exampleEnglish: "Before advising others, start with yourself",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دیوار موش دارد",
    phonetic: "divar moosh darad",
    englishTranslation: "Walls have ears",
    exampleFarsi: "مواظب حرف زدنت باش؛ دیوار موش دارد، موش هم گوش دارد",
    examplePhonetic: "movazebe harf zadanat bash; divar moosh darad, moosh ham goosh darad",
    exampleEnglish: "Be careful what you say; walls have ears",
    difficultyLevel: 5,
  },
];

// ─── 4. Literature & Poetry ─────────────────────────────────────────────────

const literaturePoetry: WordData[] = [
  {
    farsiWord: "بیت",
    phonetic: "beyt",
    englishTranslation: "Verse (couplet)",
    exampleFarsi: "این بیت از حافظ یکی از معروف‌ترین ابیات فارسی است",
    examplePhonetic: "in beyt az hafez yeki az marooftarin abyate farsi ast",
    exampleEnglish: "This couplet by Hafez is one of the most famous Persian verses",
    difficultyLevel: 5,
  },
  {
    farsiWord: "قافیه",
    phonetic: "ghafiyeh",
    englishTranslation: "Rhyme",
    exampleFarsi: "شاعر با مهارت قافیه‌های زیبایی برای غزلش انتخاب کرد",
    examplePhonetic: "sha'er ba maharat ghafiyehaye zibai baraye ghazalash entekhab kard",
    exampleEnglish: "The poet skillfully chose beautiful rhymes for his ghazal",
    difficultyLevel: 5,
  },
  {
    farsiWord: "استعاره",
    phonetic: "este'areh",
    englishTranslation: "Metaphor",
    exampleFarsi: "استعاره‌های مولانا معانی عمیقی دارند",
    examplePhonetic: "este'arehaye mowlana ma'aniye amighi darand",
    exampleEnglish: "Rumi's metaphors carry deep meanings",
    difficultyLevel: 5,
  },
  {
    farsiWord: "داستان",
    phonetic: "dastan",
    englishTranslation: "Story",
    exampleFarsi: "داستان‌های شاهنامه از حماسه‌های بزرگ ادبیات فارسی هستند",
    examplePhonetic: "dastanhaye shahnameh az hamasehaye bozorge adabiyate farsi hastand",
    exampleEnglish: "The stories of the Shahnameh are among the great epics of Persian literature",
    difficultyLevel: 5,
  },
  {
    farsiWord: "رمان",
    phonetic: "roman",
    englishTranslation: "Novel",
    exampleFarsi: "بوف کور نوشته صادق هدایت مشهورترین رمان فارسی است",
    examplePhonetic: "boofe koor neveshteye sadegh hedayat mashhoortarin romane farsi ast",
    exampleEnglish: "The Blind Owl by Sadegh Hedayat is the most famous Persian novel",
    difficultyLevel: 5,
  },
  {
    farsiWord: "فصل",
    phonetic: "fasl-lit",
    englishTranslation: "Chapter",
    exampleFarsi: "فصل اول کتاب درباره تاریخ ادبیات فارسی است",
    examplePhonetic: "fasle avvale ketab darbare tarikhe adabiyate farsi ast",
    exampleEnglish: "The first chapter of the book is about the history of Persian literature",
    difficultyLevel: 5,
  },
  {
    farsiWord: "شخصیت",
    phonetic: "shakhsiyat",
    englishTranslation: "Character",
    exampleFarsi: "شخصیت اصلی این رمان زنی شجاع و مستقل است",
    examplePhonetic: "shakhsiyate asliye in roman zani shoja' va mostaghel ast",
    exampleEnglish: "The main character of this novel is a brave and independent woman",
    difficultyLevel: 5,
  },
  {
    farsiWord: "معنا",
    phonetic: "ma'na",
    englishTranslation: "Meaning",
    exampleFarsi: "معنای اشعار حافظ لایه‌های مختلفی دارد",
    examplePhonetic: "ma'naye ash'are hafez layehaye mokhtalafi darad",
    exampleEnglish: "The meaning of Hafez's poems has multiple layers",
    difficultyLevel: 5,
  },
  {
    farsiWord: "نماد",
    phonetic: "namad",
    englishTranslation: "Symbol",
    exampleFarsi: "در شعر فارسی، گل سرخ نماد عشق است",
    examplePhonetic: "dar she're farsi, gole sorkh namade eshgh ast",
    exampleEnglish: "In Persian poetry, the red rose is a symbol of love",
    difficultyLevel: 5,
  },
  {
    farsiWord: "سبک",
    phonetic: "sabk",
    englishTranslation: "Style",
    exampleFarsi: "سبک نوشتاری هر نویسنده‌ای منحصر به فرد است",
    examplePhonetic: "sabke neveshtariye har nevisandeyi monhaser be fard ast",
    exampleEnglish: "Every writer's writing style is unique",
    difficultyLevel: 5,
  },
  {
    farsiWord: "ژانر",
    phonetic: "zhanr",
    englishTranslation: "Genre",
    exampleFarsi: "ژانر مورد علاقه من در ادبیات، داستان‌های تاریخی است",
    examplePhonetic: "zhanre morede alagheye man dar adabiyat, dastanhaye tarikhi ast",
    exampleEnglish: "My favorite genre in literature is historical fiction",
    difficultyLevel: 5,
  },
  {
    farsiWord: "شاهکار",
    phonetic: "shahkar",
    englishTranslation: "Masterpiece",
    exampleFarsi: "شاهنامه فردوسی شاهکار ادبیات حماسی فارسی است",
    examplePhonetic: "shahnameye ferdowsi shahkare adabiyate hamasiye farsi ast",
    exampleEnglish: "Ferdowsi's Shahnameh is the masterpiece of Persian epic literature",
    difficultyLevel: 5,
  },
  {
    farsiWord: "غزل",
    phonetic: "ghazal",
    englishTranslation: "Ghazal (poetry form)",
    exampleFarsi: "غزل‌های حافظ سرشار از عشق و عرفان هستند",
    examplePhonetic: "ghazalhaye hafez sarshare az eshgh va erfan hastand",
    exampleEnglish: "Hafez's ghazals are full of love and mysticism",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مثنوی",
    phonetic: "masnavi",
    englishTranslation: "Masnavi (poetry form)",
    exampleFarsi: "مثنوی معنوی مولانا یکی از بزرگ‌ترین آثار ادبی جهان است",
    examplePhonetic: "masnaviye ma'naviye mowlana yeki az bozorgtarin asare adabiye jahan ast",
    exampleEnglish: "Rumi's Masnavi is one of the greatest literary works in the world",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تصوف",
    phonetic: "tasavvof",
    englishTranslation: "Sufism",
    exampleFarsi: "تصوف تأثیر عمیقی بر شعر و ادبیات فارسی گذاشته است",
    examplePhonetic: "tasavvof ta'sire amighi bar she'r va adabiyate farsi gozashte ast",
    exampleEnglish: "Sufism has had a profound influence on Persian poetry and literature",
    difficultyLevel: 5,
  },
];

// ─── 5. Philosophy & Abstract ───────────────────────────────────────────────

const philosophyAbstract: WordData[] = [
  {
    farsiWord: "حقیقت",
    phonetic: "haghighat",
    englishTranslation: "Truth",
    exampleFarsi: "جستجوی حقیقت هدف اصلی فلسفه است",
    examplePhonetic: "jostojooye haghighat hadafe asliye falsafe ast",
    exampleEnglish: "The search for truth is the main goal of philosophy",
    difficultyLevel: 5,
  },
  {
    farsiWord: "عدالت",
    phonetic: "edalat",
    englishTranslation: "Justice",
    exampleFarsi: "عدالت اجتماعی پایه یک جامعه سالم است",
    examplePhonetic: "edalate ejtemai payeye yek jame'eye salem ast",
    exampleEnglish: "Social justice is the foundation of a healthy society",
    difficultyLevel: 5,
  },
  {
    farsiWord: "زیبایی",
    phonetic: "zibayi",
    englishTranslation: "Beauty",
    exampleFarsi: "فیلسوفان همیشه درباره ماهیت زیبایی بحث کرده‌اند",
    examplePhonetic: "filsofan hamishe darbare mahiyate zibayi bahs kardeand",
    exampleEnglish: "Philosophers have always debated the nature of beauty",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دانش",
    phonetic: "danesh",
    englishTranslation: "Knowledge",
    exampleFarsi: "دانش قدرت است و کلید پیشرفت بشریت",
    examplePhonetic: "danesh ghodrat ast va kelide pishrafte bashariyat",
    exampleEnglish: "Knowledge is power and the key to human progress",
    difficultyLevel: 5,
  },
  {
    farsiWord: "حکمت",
    phonetic: "hekmat",
    englishTranslation: "Wisdom",
    exampleFarsi: "حکمت با تجربه و تأمل به دست می‌آید",
    examplePhonetic: "hekmat ba tajrobe va ta'ammol be dast miyayad",
    exampleEnglish: "Wisdom is gained through experience and reflection",
    difficultyLevel: 5,
  },
  {
    farsiWord: "قدرت",
    phonetic: "ghodrat",
    englishTranslation: "Power",
    exampleFarsi: "قدرت بدون مسئولیت می‌تواند خطرناک باشد",
    examplePhonetic: "ghodrat bedoone mas'ooliyat mitavanad khatarnak bashad",
    exampleEnglish: "Power without responsibility can be dangerous",
    difficultyLevel: 5,
  },
  {
    farsiWord: "صلح",
    phonetic: "solh",
    englishTranslation: "Peace",
    exampleFarsi: "صلح جهانی آرزوی همه مردم دنیاست",
    examplePhonetic: "solhe jahani arezooye hame mardome donyast",
    exampleEnglish: "World peace is the wish of all people",
    difficultyLevel: 5,
  },
  {
    farsiWord: "عشق",
    phonetic: "eshgh",
    englishTranslation: "Love",
    exampleFarsi: "عشق در فلسفه مولانا نیروی محرک هستی است",
    examplePhonetic: "eshgh dar falsafeye mowlana niroye mohareke hasti ast",
    exampleEnglish: "Love in Rumi's philosophy is the driving force of existence",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مرگ",
    phonetic: "marg",
    englishTranslation: "Death",
    exampleFarsi: "فیلسوفان از دیرباز درباره مفهوم مرگ اندیشیده‌اند",
    examplePhonetic: "filsofan az dirbaz darbare mafhoome marg andishideand",
    exampleEnglish: "Philosophers have long contemplated the concept of death",
    difficultyLevel: 5,
  },
  {
    farsiWord: "روح",
    phonetic: "rooh",
    englishTranslation: "Soul",
    exampleFarsi: "در عرفان ایرانی، روح در جستجوی بازگشت به اصل خود است",
    examplePhonetic: "dar erfane irani, rooh dar jostojooye bazgasht be asle khod ast",
    exampleEnglish: "In Iranian mysticism, the soul seeks to return to its origin",
    difficultyLevel: 5,
  },
  {
    farsiWord: "ایمان",
    phonetic: "iman",
    englishTranslation: "Faith",
    exampleFarsi: "ایمان به خود اولین قدم برای رسیدن به موفقیت است",
    examplePhonetic: "iman be khod avvalin ghadam baraye residan be movaffaghiyat ast",
    exampleEnglish: "Faith in oneself is the first step to achieving success",
    difficultyLevel: 5,
  },
  {
    farsiWord: "شک",
    phonetic: "shak",
    englishTranslation: "Doubt",
    exampleFarsi: "شک و پرسشگری آغاز تفکر فلسفی است",
    examplePhonetic: "shak va porsesgari aghaze tafakkore falsafi ast",
    exampleEnglish: "Doubt and questioning are the beginning of philosophical thinking",
    difficultyLevel: 5,
  },
  {
    farsiWord: "وجود",
    phonetic: "vojood",
    englishTranslation: "Existence",
    exampleFarsi: "فلسفه وجود یکی از بنیادی‌ترین مباحث فلسفی است",
    examplePhonetic: "falsafeye vojood yeki az bonyadi-tarin mabahese falsafi ast",
    exampleEnglish: "The philosophy of existence is one of the most fundamental philosophical topics",
    difficultyLevel: 5,
  },
  {
    farsiWord: "معنی",
    phonetic: "ma'ni",
    englishTranslation: "Purpose/Meaning",
    exampleFarsi: "هر کسی در جستجوی معنی زندگی خود است",
    examplePhonetic: "har kasi dar jostojooye ma'niye zendegiye khod ast",
    exampleEnglish: "Everyone is searching for the meaning of their life",
    difficultyLevel: 5,
  },
  {
    farsiWord: "هدف",
    phonetic: "hadaf-phil",
    englishTranslation: "Goal",
    exampleFarsi: "داشتن هدف مشخص به زندگی جهت و معنا می‌دهد",
    examplePhonetic: "dashtan hadafe moshakhkhas be zendegi jahat va ma'na midahad",
    exampleEnglish: "Having a clear goal gives life direction and meaning",
    difficultyLevel: 5,
  },
  {
    farsiWord: "سرنوشت",
    phonetic: "sarnevesht",
    englishTranslation: "Destiny",
    exampleFarsi: "آیا سرنوشت ما از پیش تعیین شده یا خودمان آن را می‌سازیم؟",
    examplePhonetic: "aya sarneveshte ma az pish ta'yin shodeh ya khodeman an ra misazim?",
    exampleEnglish: "Is our destiny predetermined, or do we create it ourselves?",
    difficultyLevel: 5,
  },
  {
    farsiWord: "وجدان",
    phonetic: "vojdan",
    englishTranslation: "Conscience",
    exampleFarsi: "وجدان بیدار بهترین راهنمای انسان در تصمیم‌گیری است",
    examplePhonetic: "vojdane bidar behtarin rahnamaye ensan dar tasmimgiri ast",
    exampleEnglish: "An awakened conscience is the best guide for human decision-making",
    difficultyLevel: 5,
  },
  {
    farsiWord: "فلسفه",
    phonetic: "falsafe",
    englishTranslation: "Philosophy",
    exampleFarsi: "فلسفه اسلامی تأثیر عمیقی بر تمدن بشری داشته است",
    examplePhonetic: "falsafeye eslami ta'sire amighi bar tamaddone bashari dashte ast",
    exampleEnglish: "Islamic philosophy has had a profound impact on human civilization",
    difficultyLevel: 5,
  },
];

// ─── 6. Formal & Written Farsi ──────────────────────────────────────────────

const formalWritten: WordData[] = [
  {
    farsiWord: "در حالی که",
    phonetic: "dar hali ke",
    englishTranslation: "Whereas",
    exampleFarsi: "در حالی که بودجه محدود بود، پروژه با موفقیت انجام شد",
    examplePhonetic: "dar hali ke bodjeh mahdood bood, prozheh ba movaffaghiyat anjam shod",
    exampleEnglish: "Whereas the budget was limited, the project was completed successfully",
    difficultyLevel: 5,
  },
  {
    farsiWord: "از این پس",
    phonetic: "az in pas",
    englishTranslation: "Henceforth",
    exampleFarsi: "از این پس تمام گزارش‌ها باید به صورت الکترونیکی ارسال شوند",
    examplePhonetic: "az in pas tamame gozareshha bayad be soorate elektroniki ersal shavand",
    exampleEnglish: "Henceforth, all reports must be submitted electronically",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "با وجود این",
    phonetic: "ba vojood-e in",
    englishTranslation: "Notwithstanding",
    exampleFarsi: "با وجود این مشکلات، تیم ما به کار خود ادامه داد",
    examplePhonetic: "ba vojoode in moshkelat, time ma be kare khod edame dad",
    exampleEnglish: "Notwithstanding these problems, our team continued its work",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "بدین وسیله",
    phonetic: "beddin vasile",
    englishTranslation: "Hereby",
    exampleFarsi: "بدین وسیله به اطلاع می‌رسانیم که جلسه به تعویق افتاده است",
    examplePhonetic: "beddin vasile be ettela' miresanim ke jalase be ta'vigh oftade ast",
    exampleEnglish: "We hereby inform you that the meeting has been postponed",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "مذکور",
    phonetic: "mazkoor",
    englishTranslation: "Aforesaid",
    exampleFarsi: "شرکت مذکور موظف به اجرای تعهدات خود می‌باشد",
    examplePhonetic: "sherkate mazkoor movazzaf be ejraye ta'ahhodate khod mibashad",
    exampleEnglish: "The aforesaid company is obligated to fulfill its commitments",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "بر این اساس",
    phonetic: "bar in asas",
    englishTranslation: "Accordingly",
    exampleFarsi: "نتایج آزمون منتشر شد و بر این اساس پذیرش‌ها اعلام خواهد شد",
    examplePhonetic: "natayeje azmoon montasher shod va bar in asas pazirshha e'lam khahad shod",
    exampleEnglish: "The test results were published and accordingly admissions will be announced",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "متعاقباً",
    phonetic: "mota'agheban",
    englishTranslation: "Subsequently",
    exampleFarsi: "قرارداد امضا شد و متعاقباً کار آغاز خواهد شد",
    examplePhonetic: "gharardad emza shod va mota'agheban kar aghaz khahad shod",
    exampleEnglish: "The contract was signed, and subsequently the work will begin",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "قبل از",
    phonetic: "ghabl az",
    englishTranslation: "Prior to",
    exampleFarsi: "قبل از شروع جلسه، لطفاً مدارک لازم را آماده کنید",
    examplePhonetic: "ghabl az shorooe jalase, lotfan madareke lazem ra amadeh konid",
    exampleEnglish: "Prior to the start of the meeting, please prepare the necessary documents",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "به جای",
    phonetic: "be jaye-formal",
    englishTranslation: "In lieu of",
    exampleFarsi: "به جای پرداخت نقدی، چک بانکی ارائه شد",
    examplePhonetic: "be jaye pardakhte naghdi, cheke banki araye shod",
    exampleEnglish: "In lieu of cash payment, a bank check was provided",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "مطابق با",
    phonetic: "motabeghe ba",
    englishTranslation: "In accordance with",
    exampleFarsi: "مطابق با قوانین جدید، همه باید مالیات خود را به موقع پرداخت کنند",
    examplePhonetic: "motabeghe ba ghavanine jadid, hame bayad maliyate khod ra be moghe pardakht konand",
    exampleEnglish: "In accordance with the new laws, everyone must pay their taxes on time",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "از آنجا که",
    phonetic: "az anja ke",
    englishTranslation: "Inasmuch as",
    exampleFarsi: "از آنجا که بودجه کافی تأمین نشده، پروژه متوقف می‌شود",
    examplePhonetic: "az anja ke bodjeye kafi ta'min nashodeh, prozheh motavaghgef mishavad",
    exampleEnglish: "Inasmuch as sufficient budget has not been secured, the project will be halted",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "به ترتیب",
    phonetic: "be tartib",
    englishTranslation: "Respectively",
    exampleFarsi: "علی و مریم به ترتیب نفر اول و دوم مسابقه شدند",
    examplePhonetic: "ali va maryam be tartib nafare avval va dovvome mosabeghe shodand",
    exampleEnglish: "Ali and Maryam became first and second place respectively in the competition",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "در خصوص",
    phonetic: "dar khosoos",
    englishTranslation: "Regarding",
    exampleFarsi: "در خصوص درخواست شما، بررسی‌های لازم انجام شده است",
    examplePhonetic: "dar khosoose darkhaste shoma, barresihaye lazem anjam shode ast",
    exampleEnglish: "Regarding your request, the necessary reviews have been conducted",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "درباره",
    phonetic: "darbare-ye",
    englishTranslation: "Concerning",
    exampleFarsi: "درباره موضوع مورد بحث، نظر کارشناسان متفاوت است",
    examplePhonetic: "darbareye mowzoo'e morede bahs, nazare karshenasan motefavet ast",
    exampleEnglish: "Concerning the topic under discussion, the experts' opinions differ",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "مربوط به",
    phonetic: "marboot be",
    englishTranslation: "Pertaining to",
    exampleFarsi: "مدارک مربوط به پرونده باید تا پایان هفته تحویل داده شوند",
    examplePhonetic: "madareke marboot be parvandeh bayad ta payane hafteh tahvil dade shavand",
    exampleEnglish: "Documents pertaining to the case must be submitted by the end of the week",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "محصل",
    phonetic: "mohazzal",
    englishTranslation: "Obtained/Achieved",
    exampleFarsi: "نتایج محصل از این تحقیق بسیار ارزشمند هستند",
    examplePhonetic: "natayeje mohazzal az in tahghigh besyar arzeshmand hastand",
    exampleEnglish: "The results obtained from this research are very valuable",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "منحصراً",
    phonetic: "monhasseran",
    englishTranslation: "Exclusively",
    exampleFarsi: "این خدمات منحصراً برای اعضای سازمان ارائه می‌شود",
    examplePhonetic: "in khadamat monhasseran baraye a'zaye sazman araye mishavad",
    exampleEnglish: "These services are provided exclusively for members of the organization",
    difficultyLevel: 5,
    isFormal: true,
  },
  {
    farsiWord: "متوالی",
    phonetic: "motavali",
    englishTranslation: "Consecutive",
    exampleFarsi: "تیم ما سه سال متوالی قهرمان مسابقات شده است",
    examplePhonetic: "time ma se sale motavali ghahreman mosabeghat shode ast",
    exampleEnglish: "Our team has been champion of the competitions for three consecutive years",
    difficultyLevel: 5,
    isFormal: true,
  },
];

// ─── 7. Advanced Phrasal Verbs ──────────────────────────────────────────────

const advancedPhrasalVerbs: WordData[] = [
  {
    farsiWord: "سوء استفاده کردن",
    phonetic: "soo estefade kardan",
    englishTranslation: "To take advantage / To exploit",
    exampleFarsi: "از اعتماد مردم سوء استفاده نکنید",
    examplePhonetic: "az e'temade mardom soo estefade nakonid",
    exampleEnglish: "Don't take advantage of people's trust",
    difficultyLevel: 5,
  },
  {
    farsiWord: "دست کشیدن",
    phonetic: "dast keshidan",
    englishTranslation: "To give up",
    exampleFarsi: "هرگز از رویاهایت دست نکش",
    examplePhonetic: "hargez az royahayat dast nakesh",
    exampleEnglish: "Never give up on your dreams",
    difficultyLevel: 5,
  },
  {
    farsiWord: "حل کردن",
    phonetic: "hal kardan",
    englishTranslation: "To solve",
    exampleFarsi: "دانشمندان سال‌ها تلاش کردند تا این مسئله ریاضی را حل کنند",
    examplePhonetic: "daneshmandan salha talash kardand ta in mas'aleye riazi ra hal konand",
    exampleEnglish: "Scientists worked for years to solve this mathematical problem",
    difficultyLevel: 5,
  },
  {
    farsiWord: "خراب شدن",
    phonetic: "kharab shodan",
    englishTranslation: "To break down",
    exampleFarsi: "ماشینم وسط جاده خراب شد و مجبور شدم کمک بخواهم",
    examplePhonetic: "mashinam vasate jadde kharab shod va majboor shodam komak bekhaaham",
    exampleEnglish: "My car broke down in the middle of the road and I had to ask for help",
    difficultyLevel: 5,
  },
  {
    farsiWord: "راه انداختن",
    phonetic: "rah andakhtan",
    englishTranslation: "To set up / To launch",
    exampleFarsi: "کسب و کار جدیدی را با دوستم راه انداختیم",
    examplePhonetic: "kasb o kare jadidi ra ba doostam rah andakhtim",
    exampleEnglish: "We set up a new business with my friend",
    difficultyLevel: 5,
  },
  {
    farsiWord: "رد کردن",
    phonetic: "rad kardan",
    englishTranslation: "To turn down / To reject",
    exampleFarsi: "پیشنهاد شغلی خوبی بود ولی متأسفانه رد کردم",
    examplePhonetic: "pishnahade shoghli khoobi bood vali mota'assefane rad kardam",
    exampleEnglish: "It was a good job offer but unfortunately I turned it down",
    difficultyLevel: 5,
  },
  {
    farsiWord: "مطرح کردن",
    phonetic: "matrah kardan",
    englishTranslation: "To bring up",
    exampleFarsi: "در جلسه موضوع مهمی را مطرح کرد که همه را شگفت‌زده کرد",
    examplePhonetic: "dar jalase mowzoo'e mohemmi ra matrah kard ke hame ra shegeftzade kard",
    exampleEnglish: "He brought up an important topic in the meeting that surprised everyone",
    difficultyLevel: 5,
  },
  {
    farsiWord: "انجام دادن",
    phonetic: "anjam dadan",
    englishTranslation: "To carry out",
    exampleFarsi: "تیم تحقیقاتی آزمایش‌های متعددی را با موفقیت انجام داد",
    examplePhonetic: "time tahghighati azmayeshhaye mota'addedi ra ba movaffaghiyat anjam dad",
    exampleEnglish: "The research team successfully carried out multiple experiments",
    difficultyLevel: 5,
  },
  {
    farsiWord: "ادامه دادن",
    phonetic: "edame dadan",
    englishTranslation: "To continue",
    exampleFarsi: "با وجود مشکلات، به کارش ادامه داد و موفق شد",
    examplePhonetic: "ba vojoode moshkelat, be karash edame dad va movaffagh shod",
    exampleEnglish: "Despite the difficulties, he continued his work and succeeded",
    difficultyLevel: 5,
  },
  {
    farsiWord: "اشاره کردن",
    phonetic: "eshareh kardan",
    englishTranslation: "To point out",
    exampleFarsi: "استاد به نکته مهمی اشاره کرد که همه از آن غافل بودند",
    examplePhonetic: "ostad be nokteye mohemmi eshareh kard ke hame az an ghafel boodand",
    exampleEnglish: "The professor pointed out an important detail that everyone had overlooked",
    difficultyLevel: 5,
  },
  {
    farsiWord: "تمام شدن",
    phonetic: "tamam shodan",
    englishTranslation: "To run out",
    exampleFarsi: "بنزین ماشین تمام شده بود و نزدیک‌ترین پمپ بنزین دور بود",
    examplePhonetic: "benzine mashin tamam shode bood va naziktarin pompe benzin door bood",
    exampleEnglish: "The car had run out of gas and the nearest gas station was far away",
    difficultyLevel: 5,
  },
  {
    farsiWord: "بررسی کردن",
    phonetic: "barresi kardan",
    englishTranslation: "To look into / To investigate",
    exampleFarsi: "پلیس در حال بررسی پرونده جدیدی است",
    examplePhonetic: "polis dar hale barresiye parvandeye jadidi ast",
    exampleEnglish: "The police are looking into a new case",
    difficultyLevel: 5,
  },
  {
    farsiWord: "پی بردن",
    phonetic: "pey bordan",
    englishTranslation: "To find out / To realize",
    exampleFarsi: "بعد از مدت‌ها به حقیقت ماجرا پی بردم",
    examplePhonetic: "ba'd az moddatha be haghighate majara pey bordam",
    exampleEnglish: "After a long time, I found out the truth of the matter",
    difficultyLevel: 5,
  },
  {
    farsiWord: "برآمدن",
    phonetic: "bar amadan",
    englishTranslation: "To cope with",
    exampleFarsi: "از عهده این مسئولیت سنگین به خوبی برآمد",
    examplePhonetic: "az ohdeye in mas'ooliyate sangin be khoobi bar amad",
    exampleEnglish: "He coped well with this heavy responsibility",
    difficultyLevel: 5,
  },
  {
    farsiWord: "جور درآمدن",
    phonetic: "joor dar amadan",
    englishTranslation: "To get along",
    exampleFarsi: "همکاران جدید خیلی زود با هم جور درآمدند",
    examplePhonetic: "hamkarane jadid kheyli zood ba ham joor dar amadand",
    exampleEnglish: "The new colleagues got along with each other very quickly",
    difficultyLevel: 5,
  },
  {
    farsiWord: "خوب پیش رفتن",
    phonetic: "khoob pish raftan",
    englishTranslation: "To go well",
    exampleFarsi: "مذاکرات تجاری خوب پیش رفت و قرارداد بسته شد",
    examplePhonetic: "mozakeRate tejari khoob pish raft va gharardad baste shod",
    exampleEnglish: "The business negotiations went well and the contract was signed",
    difficultyLevel: 5,
  },
  {
    farsiWord: "برخورد کردن",
    phonetic: "barkhord kardan",
    englishTranslation: "To encounter",
    exampleFarsi: "در سفرم به شیراز با فرهنگ غنی ایرانی برخورد کردم",
    examplePhonetic: "dar safaram be shiraz ba farhange ghaniye irani barkhord kardam",
    exampleEnglish: "During my trip to Shiraz, I encountered the rich Iranian culture",
    difficultyLevel: 5,
  },
  {
    farsiWord: "پر کردن",
    phonetic: "por kardan",
    englishTranslation: "To fill in/out",
    exampleFarsi: "لطفاً این فرم را با دقت پر کنید و امضا بزنید",
    examplePhonetic: "lotfan in form ra ba deghat por konid va emza bezanid",
    exampleEnglish: "Please fill out this form carefully and sign it",
    difficultyLevel: 5,
  },
];

// ─── Seed Function ──────────────────────────────────────────────────────────

export async function seedLevel5() {
  console.log("\n=== Level 5: Advanced ===\n");
  let total = 0;

  const r1 = await seedCategory({
    name: "Academic & Professional",
    slug: "academic",
    description: "Academic, research, and professional vocabulary for formal settings",
    icon: "🏛️",
    level: 5,
    sortOrder: 1,
    words: academicProfessional,
  });
  total += r1.wordsAdded;

  const r2 = await seedCategory({
    name: "Nuanced Emotions",
    slug: "emotions-nuanced",
    description: "Complex emotional states, personality traits, and nuanced feelings",
    icon: "💎",
    level: 5,
    sortOrder: 2,
    words: nuancedEmotions,
  });
  total += r2.wordsAdded;

  const r3 = await seedCategory({
    name: "Proverbs & Idioms",
    slug: "proverbs-idioms",
    description: "Common Persian proverbs, idioms, and expressions of wisdom",
    icon: "📜",
    level: 5,
    sortOrder: 3,
    words: proverbsIdioms,
  });
  total += r3.wordsAdded;

  const r4 = await seedCategory({
    name: "Literature & Poetry",
    slug: "literature-poetry",
    description: "Literary terms, poetry forms, and vocabulary for discussing Persian literature",
    icon: "📖",
    level: 5,
    sortOrder: 4,
    words: literaturePoetry,
  });
  total += r4.wordsAdded;

  const r5 = await seedCategory({
    name: "Philosophy & Abstract",
    slug: "philosophy",
    description: "Philosophical concepts, abstract ideas, and existential vocabulary",
    icon: "🔮",
    level: 5,
    sortOrder: 5,
    words: philosophyAbstract,
  });
  total += r5.wordsAdded;

  const r6 = await seedCategory({
    name: "Formal & Written Farsi",
    slug: "formal-written",
    description: "Formal written expressions used in official documents and correspondence",
    icon: "✒️",
    level: 5,
    sortOrder: 6,
    words: formalWritten,
  });
  total += r6.wordsAdded;

  const r7 = await seedCategory({
    name: "Advanced Phrasal Verbs",
    slug: "advanced-phrasal-verbs",
    description: "Complex compound verbs and phrasal expressions for advanced communication",
    icon: "⚡",
    level: 5,
    sortOrder: 7,
    words: advancedPhrasalVerbs,
  });
  total += r7.wordsAdded;

  console.log(`\nLevel 5 complete: ${total} new words added\n`);
  return total;
}
