import "dotenv/config";
import { seedCategory, type WordData } from "./seed-helpers";

// ---------------------------------------------------------------------------
// 1. Basic Greetings
// ---------------------------------------------------------------------------
const greetings: WordData[] = [
  {
    farsiWord: "سلام",
    phonetic: "salaam",
    englishTranslation: "Hello",
    exampleFarsi: "سلام، حالت خوبه؟",
    examplePhonetic: "salaam, halet khoobe?",
    exampleEnglish: "Hello, how are you?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خداحافظ",
    phonetic: "khodahafez",
    englishTranslation: "Goodbye",
    exampleFarsi: "خداحافظ، به امید دیدار!",
    examplePhonetic: "khodahafez, be omide didar!",
    exampleEnglish: "Goodbye, hope to see you again!",
    difficultyLevel: 1,
  },
  {
    farsiWord: "ممنون",
    phonetic: "mamnoon",
    englishTranslation: "Thank you",
    exampleFarsi: "ممنون از لطف شما.",
    examplePhonetic: "mamnoon az lotfe shoma.",
    exampleEnglish: "Thank you for your kindness.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "لطفاً",
    phonetic: "lotfan",
    englishTranslation: "Please",
    exampleFarsi: "لطفاً بنشینید.",
    examplePhonetic: "lotfan beshinid.",
    exampleEnglish: "Please sit down.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بله",
    phonetic: "baleh",
    englishTranslation: "Yes",
    exampleFarsi: "بله، درسته.",
    examplePhonetic: "baleh, doroste.",
    exampleEnglish: "Yes, that's correct.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نه",
    phonetic: "na",
    englishTranslation: "No",
    exampleFarsi: "نه، ممنون.",
    examplePhonetic: "na, mamnoon.",
    exampleEnglish: "No, thank you.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "صبح بخیر",
    phonetic: "sobh bekheyr",
    englishTranslation: "Good morning",
    exampleFarsi: "صبح بخیر، خوب خوابیدی؟",
    examplePhonetic: "sobh bekheyr, khoob khabidi?",
    exampleEnglish: "Good morning, did you sleep well?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شب بخیر",
    phonetic: "shab bekheyr",
    englishTranslation: "Good night",
    exampleFarsi: "شب بخیر، خواب خوش!",
    examplePhonetic: "shab bekheyr, khabe khosh!",
    exampleEnglish: "Good night, sweet dreams!",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خوبم",
    phonetic: "khoobam",
    englishTranslation: "I'm fine",
    exampleFarsi: "ممنون، خوبم.",
    examplePhonetic: "mamnoon, khoobam.",
    exampleEnglish: "Thanks, I'm fine.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "ببخشید",
    phonetic: "bebakhshid",
    englishTranslation: "Excuse me",
    exampleFarsi: "ببخشید، ساعت چنده؟",
    examplePhonetic: "bebakhshid, saat chande?",
    exampleEnglish: "Excuse me, what time is it?",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 2. Essential Words
// ---------------------------------------------------------------------------
const essential: WordData[] = [
  {
    farsiWord: "آب",
    phonetic: "aab",
    englishTranslation: "Water",
    exampleFarsi: "لطفاً یک لیوان آب بدهید.",
    examplePhonetic: "lotfan yek livan aab bedahid.",
    exampleEnglish: "Please give me a glass of water.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نان",
    phonetic: "nan",
    englishTranslation: "Bread",
    exampleFarsi: "نان تازه خیلی خوشمزه است.",
    examplePhonetic: "nane tazeh kheyli khoshmaze ast.",
    exampleEnglish: "Fresh bread is very delicious.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خانه",
    phonetic: "khaneh",
    englishTranslation: "House",
    exampleFarsi: "خانه ما بزرگ است.",
    examplePhonetic: "khaneh-ye ma bozorg ast.",
    exampleEnglish: "Our house is big.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کتاب",
    phonetic: "ketab",
    englishTranslation: "Book",
    exampleFarsi: "این کتاب خیلی جالب است.",
    examplePhonetic: "in ketab kheyli jaleb ast.",
    exampleEnglish: "This book is very interesting.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "مدرسه",
    phonetic: "madreseh",
    englishTranslation: "School",
    exampleFarsi: "بچه‌ها به مدرسه می‌روند.",
    examplePhonetic: "bacheh-ha be madreseh miravand.",
    exampleEnglish: "The children go to school.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "دوست",
    phonetic: "doost",
    englishTranslation: "Friend",
    exampleFarsi: "او دوست خوب من است.",
    examplePhonetic: "oo dooste khoobe man ast.",
    exampleEnglish: "He/She is my good friend.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "غذا",
    phonetic: "ghaza",
    englishTranslation: "Food",
    exampleFarsi: "غذای ایرانی خوشمزه است.",
    examplePhonetic: "ghazaye irani khoshmaze ast.",
    exampleEnglish: "Iranian food is delicious.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کار",
    phonetic: "kar",
    englishTranslation: "Work",
    exampleFarsi: "من هر روز سر کار می‌روم.",
    examplePhonetic: "man har rooz sare kar miravam.",
    exampleEnglish: "I go to work every day.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "روز",
    phonetic: "rooz",
    englishTranslation: "Day",
    exampleFarsi: "امروز روز خوبی است.",
    examplePhonetic: "emrooz rooze khoobi ast.",
    exampleEnglish: "Today is a good day.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شب",
    phonetic: "shab",
    englishTranslation: "Night",
    exampleFarsi: "شب‌ها هوا سرد می‌شود.",
    examplePhonetic: "shab-ha hava sard mishavad.",
    exampleEnglish: "It gets cold at night.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 3. Numbers 1-10 (plus 100 and 1000)
// ---------------------------------------------------------------------------
const numbers: WordData[] = [
  {
    farsiWord: "یک",
    phonetic: "yek",
    englishTranslation: "One",
    exampleFarsi: "من یک خواهر دارم.",
    examplePhonetic: "man yek khahar daram.",
    exampleEnglish: "I have one sister.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "دو",
    phonetic: "do",
    englishTranslation: "Two",
    exampleFarsi: "دو تا چای لطفاً.",
    examplePhonetic: "do ta chai lotfan.",
    exampleEnglish: "Two teas, please.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سه",
    phonetic: "seh",
    englishTranslation: "Three",
    exampleFarsi: "سه نفر آمدند.",
    examplePhonetic: "seh nafar amadand.",
    exampleEnglish: "Three people came.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "چهار",
    phonetic: "chahar",
    englishTranslation: "Four",
    exampleFarsi: "چهار فصل در سال وجود دارد.",
    examplePhonetic: "chahar fasl dar sal vojood darad.",
    exampleEnglish: "There are four seasons in a year.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پنج",
    phonetic: "panj",
    englishTranslation: "Five",
    exampleFarsi: "پنج انگشت در هر دست داریم.",
    examplePhonetic: "panj angosht dar har dast darim.",
    exampleEnglish: "We have five fingers on each hand.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شش",
    phonetic: "shesh",
    englishTranslation: "Six",
    exampleFarsi: "ساعت شش بیدار شدم.",
    examplePhonetic: "saate shesh bidar shodam.",
    exampleEnglish: "I woke up at six o'clock.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "هفت",
    phonetic: "haft",
    englishTranslation: "Seven",
    exampleFarsi: "هفت روز در هفته است.",
    examplePhonetic: "haft rooz dar hafteh ast.",
    exampleEnglish: "There are seven days in a week.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "هشت",
    phonetic: "hasht",
    englishTranslation: "Eight",
    exampleFarsi: "ساعت هشت صبح کلاس دارم.",
    examplePhonetic: "saate hasht-e sobh kelas daram.",
    exampleEnglish: "I have class at eight in the morning.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نه",
    phonetic: "noh",
    englishTranslation: "Nine",
    exampleFarsi: "نه نفر در کلاس بودند.",
    examplePhonetic: "noh nafar dar kelas boodand.",
    exampleEnglish: "There were nine people in class.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "ده",
    phonetic: "dah",
    englishTranslation: "Ten",
    exampleFarsi: "ده دقیقه صبر کن.",
    examplePhonetic: "dah daghighe sabr kon.",
    exampleEnglish: "Wait ten minutes.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "صد",
    phonetic: "sad",
    englishTranslation: "Hundred",
    exampleFarsi: "صد نفر در جلسه بودند.",
    examplePhonetic: "sad nafar dar jalaseh boodand.",
    exampleEnglish: "A hundred people were at the meeting.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "هزار",
    phonetic: "hezar",
    englishTranslation: "Thousand",
    exampleFarsi: "هزار تومان می‌شود.",
    examplePhonetic: "hezar toman mishavad.",
    exampleEnglish: "It costs a thousand tomans.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 4. Colors
// ---------------------------------------------------------------------------
const colors: WordData[] = [
  {
    farsiWord: "سفید",
    phonetic: "sefid",
    englishTranslation: "White",
    exampleFarsi: "برف سفید است.",
    examplePhonetic: "barf sefid ast.",
    exampleEnglish: "Snow is white.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سیاه",
    phonetic: "siyah",
    englishTranslation: "Black",
    exampleFarsi: "گربه سیاه زیباست.",
    examplePhonetic: "gorbeh-ye siyah zibaast.",
    exampleEnglish: "The black cat is beautiful.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "قرمز",
    phonetic: "ghermez",
    englishTranslation: "Red",
    exampleFarsi: "گل‌های قرمز را دوست دارم.",
    examplePhonetic: "gol-haye ghermez ra doost daram.",
    exampleEnglish: "I like red flowers.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آبی",
    phonetic: "abi",
    englishTranslation: "Blue",
    exampleFarsi: "آسمان آبی است.",
    examplePhonetic: "aseman abi ast.",
    exampleEnglish: "The sky is blue.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سبز",
    phonetic: "sabz",
    englishTranslation: "Green",
    exampleFarsi: "درخت‌ها سبز شدند.",
    examplePhonetic: "derakht-ha sabz shodand.",
    exampleEnglish: "The trees turned green.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "زرد",
    phonetic: "zard",
    englishTranslation: "Yellow",
    exampleFarsi: "خورشید زرد است.",
    examplePhonetic: "khorshid zard ast.",
    exampleEnglish: "The sun is yellow.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نارنجی",
    phonetic: "narenji",
    englishTranslation: "Orange",
    exampleFarsi: "پرتقال نارنجی است.",
    examplePhonetic: "porteghaal narenji ast.",
    exampleEnglish: "The orange is orange.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بنفش",
    phonetic: "banafsh",
    englishTranslation: "Purple",
    exampleFarsi: "لباس بنفش قشنگ است.",
    examplePhonetic: "lebase banafsh ghashang ast.",
    exampleEnglish: "The purple dress is pretty.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "صورتی",
    phonetic: "soorati",
    englishTranslation: "Pink",
    exampleFarsi: "گل‌های صورتی خوشگل هستند.",
    examplePhonetic: "gol-haye soorati khoshgel hastand.",
    exampleEnglish: "Pink flowers are pretty.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "قهوه‌ای",
    phonetic: "ghahve-i",
    englishTranslation: "Brown",
    exampleFarsi: "میز قهوه‌ای رنگ است.",
    examplePhonetic: "miz ghahve-i rang ast.",
    exampleEnglish: "The table is brown.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 5. Prepositions
// ---------------------------------------------------------------------------
const prepositions: WordData[] = [
  {
    farsiWord: "در",
    phonetic: "dar",
    englishTranslation: "In/At",
    exampleFarsi: "او در خانه است.",
    examplePhonetic: "oo dar khaneh ast.",
    exampleEnglish: "He/She is at home.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "به",
    phonetic: "be",
    englishTranslation: "To",
    exampleFarsi: "من به مدرسه می‌روم.",
    examplePhonetic: "man be madreseh miravam.",
    exampleEnglish: "I go to school.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "از",
    phonetic: "az",
    englishTranslation: "From",
    exampleFarsi: "من از ایران هستم.",
    examplePhonetic: "man az iran hastam.",
    exampleEnglish: "I am from Iran.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "با",
    phonetic: "ba",
    englishTranslation: "With",
    exampleFarsi: "با دوستم رفتم.",
    examplePhonetic: "ba doostam raftam.",
    exampleEnglish: "I went with my friend.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "برای",
    phonetic: "baraye",
    englishTranslation: "For",
    exampleFarsi: "این هدیه برای توست.",
    examplePhonetic: "in hedyeh baraye tost.",
    exampleEnglish: "This gift is for you.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بدون",
    phonetic: "bedoone",
    englishTranslation: "Without",
    exampleFarsi: "چای بدون شکر می‌خورم.",
    examplePhonetic: "chai bedoone shekar mikhoram.",
    exampleEnglish: "I drink tea without sugar.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "روی",
    phonetic: "rooye",
    englishTranslation: "On",
    exampleFarsi: "کتاب روی میز است.",
    examplePhonetic: "ketab rooye miz ast.",
    exampleEnglish: "The book is on the table.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "زیر",
    phonetic: "zire",
    englishTranslation: "Under",
    exampleFarsi: "گربه زیر میز است.",
    examplePhonetic: "gorbeh zire miz ast.",
    exampleEnglish: "The cat is under the table.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کنار",
    phonetic: "kenare",
    englishTranslation: "Next to",
    exampleFarsi: "بنشین کنار من.",
    examplePhonetic: "beshin kenare man.",
    exampleEnglish: "Sit next to me.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بین",
    phonetic: "beyne",
    englishTranslation: "Between",
    exampleFarsi: "مدرسه بین خانه و پارک است.",
    examplePhonetic: "madreseh beyne khaneh va park ast.",
    exampleEnglish: "The school is between the house and the park.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 6. Common Phrases
// ---------------------------------------------------------------------------
const commonPhrases: WordData[] = [
  {
    farsiWord: "خوش آمدید",
    phonetic: "khosh amadid",
    englishTranslation: "Welcome",
    exampleFarsi: "به ایران خوش آمدید!",
    examplePhonetic: "be iran khosh amadid!",
    exampleEnglish: "Welcome to Iran!",
    difficultyLevel: 1,
  },
  {
    farsiWord: "متشکرم",
    phonetic: "moteshakeram",
    englishTranslation: "Thank you (formal)",
    exampleFarsi: "خیلی متشکرم از کمکتان.",
    examplePhonetic: "kheyli moteshakeram az komaketan.",
    exampleEnglish: "Thank you very much for your help.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خواهش می‌کنم",
    phonetic: "khahesh mikonam",
    englishTranslation: "You're welcome",
    exampleFarsi: "خواهش می‌کنم، کاری نکردم.",
    examplePhonetic: "khahesh mikonam, kari nakardam.",
    exampleEnglish: "You're welcome, it was nothing.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "چطوری",
    phonetic: "chetori",
    englishTranslation: "How are you",
    exampleFarsi: "سلام، چطوری؟",
    examplePhonetic: "salaam, chetori?",
    exampleEnglish: "Hi, how are you?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "حالت خوبه",
    phonetic: "halet khoobe",
    englishTranslation: "How are you doing",
    exampleFarsi: "حالت خوبه؟ چه خبر؟",
    examplePhonetic: "halet khoobe? che khabar?",
    exampleEnglish: "How are you doing? What's new?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "به امید دیدار",
    phonetic: "be omide didar",
    englishTranslation: "Hope to see you",
    exampleFarsi: "خداحافظ، به امید دیدار!",
    examplePhonetic: "khodahafez, be omide didar!",
    exampleEnglish: "Goodbye, hope to see you again!",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خوشحالم",
    phonetic: "khoshhalam",
    englishTranslation: "I'm happy",
    exampleFarsi: "از دیدنت خوشحالم.",
    examplePhonetic: "az didanet khoshhalam.",
    exampleEnglish: "I'm happy to see you.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "عالی",
    phonetic: "aali",
    englishTranslation: "Great/Excellent",
    exampleFarsi: "غذا عالی بود!",
    examplePhonetic: "ghaza aali bood!",
    exampleEnglish: "The food was excellent!",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بفرمایید",
    phonetic: "befarmayid",
    englishTranslation: "Please go ahead",
    exampleFarsi: "بفرمایید بنشینید.",
    examplePhonetic: "befarmayid beshinid.",
    exampleEnglish: "Please go ahead and sit down.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نوش جان",
    phonetic: "nooshe jan",
    englishTranslation: "Bon appetit",
    exampleFarsi: "نوش جان، غذا آماده است.",
    examplePhonetic: "nooshe jan, ghaza amadeh ast.",
    exampleEnglish: "Bon appetit, the food is ready.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 7. Pronouns
// ---------------------------------------------------------------------------
const pronouns: WordData[] = [
  {
    farsiWord: "من",
    phonetic: "man",
    englishTranslation: "I",
    exampleFarsi: "من دانشجو هستم.",
    examplePhonetic: "man daneshjoo hastam.",
    exampleEnglish: "I am a student.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "تو",
    phonetic: "to",
    englishTranslation: "You (informal)",
    exampleFarsi: "تو خیلی مهربانی.",
    examplePhonetic: "to kheyli mehrabani.",
    exampleEnglish: "You are very kind.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "او",
    phonetic: "oo",
    englishTranslation: "He/She",
    exampleFarsi: "او معلم است.",
    examplePhonetic: "oo moalem ast.",
    exampleEnglish: "He/She is a teacher.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "ما",
    phonetic: "ma",
    englishTranslation: "We",
    exampleFarsi: "ما ایرانی هستیم.",
    examplePhonetic: "ma irani hastim.",
    exampleEnglish: "We are Iranian.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شما",
    phonetic: "shoma",
    englishTranslation: "You (formal)",
    exampleFarsi: "شما از کجا هستید؟",
    examplePhonetic: "shoma az koja hastid?",
    exampleEnglish: "Where are you from?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آنها",
    phonetic: "aanha",
    englishTranslation: "They",
    exampleFarsi: "آنها دوست‌های من هستند.",
    examplePhonetic: "aanha doost-haye man hastand.",
    exampleEnglish: "They are my friends.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "این",
    phonetic: "in",
    englishTranslation: "This",
    exampleFarsi: "این کتاب من است.",
    examplePhonetic: "in ketabe man ast.",
    exampleEnglish: "This is my book.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آن",
    phonetic: "aan",
    englishTranslation: "That",
    exampleFarsi: "آن خانه بزرگ است.",
    examplePhonetic: "aan khaneh bozorg ast.",
    exampleEnglish: "That house is big.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "اینجا",
    phonetic: "inja",
    englishTranslation: "Here",
    exampleFarsi: "بیا اینجا بنشین.",
    examplePhonetic: "bia inja beshin.",
    exampleEnglish: "Come sit here.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آنجا",
    phonetic: "oonja",
    englishTranslation: "There",
    exampleFarsi: "مدرسه آنجاست.",
    examplePhonetic: "madreseh oonjaast.",
    exampleEnglish: "The school is there.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 8. Everyday Objects
// ---------------------------------------------------------------------------
const everydayObjects: WordData[] = [
  {
    farsiWord: "میز",
    phonetic: "miz",
    englishTranslation: "Table",
    exampleFarsi: "غذا روی میز است.",
    examplePhonetic: "ghaza rooye miz ast.",
    exampleEnglish: "The food is on the table.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "صندلی",
    phonetic: "sandali",
    englishTranslation: "Chair",
    exampleFarsi: "لطفاً روی صندلی بنشینید.",
    examplePhonetic: "lotfan rooye sandali beshinid.",
    exampleEnglish: "Please sit on the chair.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "در",
    phonetic: "dar-e otagh",
    englishTranslation: "Door",
    exampleFarsi: "لطفاً در را ببندید.",
    examplePhonetic: "lotfan dar ra bebandid.",
    exampleEnglish: "Please close the door.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پنجره",
    phonetic: "panjereh",
    englishTranslation: "Window",
    exampleFarsi: "پنجره را باز کن.",
    examplePhonetic: "panjereh ra baz kon.",
    exampleEnglish: "Open the window.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کلید",
    phonetic: "kelid",
    englishTranslation: "Key",
    exampleFarsi: "کلید خانه کجاست؟",
    examplePhonetic: "kelide khaneh kojaast?",
    exampleEnglish: "Where is the house key?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "تلفن",
    phonetic: "telefon",
    englishTranslation: "Phone",
    exampleFarsi: "تلفنم زنگ می‌زند.",
    examplePhonetic: "telefonam zang mizanad.",
    exampleEnglish: "My phone is ringing.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خودکار",
    phonetic: "khodkar",
    englishTranslation: "Pen",
    exampleFarsi: "یک خودکار لازم دارم.",
    examplePhonetic: "yek khodkar lazem daram.",
    exampleEnglish: "I need a pen.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کاغذ",
    phonetic: "kaghaz",
    englishTranslation: "Paper",
    exampleFarsi: "روی کاغذ بنویس.",
    examplePhonetic: "rooye kaghaz benevis.",
    exampleEnglish: "Write on the paper.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کیف",
    phonetic: "kif",
    englishTranslation: "Bag",
    exampleFarsi: "کیفم را فراموش کردم.",
    examplePhonetic: "kifam ra faramoosh kardam.",
    exampleEnglish: "I forgot my bag.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آینه",
    phonetic: "ayeneh",
    englishTranslation: "Mirror",
    exampleFarsi: "خودم را در آینه دیدم.",
    examplePhonetic: "khodam ra dar ayeneh didam.",
    exampleEnglish: "I saw myself in the mirror.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 9. Basic Food
// ---------------------------------------------------------------------------
const basicFood: WordData[] = [
  {
    farsiWord: "برنج",
    phonetic: "berenj",
    englishTranslation: "Rice",
    exampleFarsi: "برنج ایرانی خوشمزه است.",
    examplePhonetic: "berenje irani khoshmaze ast.",
    exampleEnglish: "Iranian rice is delicious.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "گوشت",
    phonetic: "goosht",
    englishTranslation: "Meat",
    exampleFarsi: "گوشت را با برنج می‌خورم.",
    examplePhonetic: "goosht ra ba berenj mikhoram.",
    exampleEnglish: "I eat meat with rice.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "میوه",
    phonetic: "mive",
    englishTranslation: "Fruit",
    exampleFarsi: "میوه تازه سالم است.",
    examplePhonetic: "miveh-ye tazeh salem ast.",
    exampleEnglish: "Fresh fruit is healthy.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شیر",
    phonetic: "shir",
    englishTranslation: "Milk",
    exampleFarsi: "هر روز شیر می‌نوشم.",
    examplePhonetic: "har rooz shir minoosham.",
    exampleEnglish: "I drink milk every day.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "چای",
    phonetic: "chai",
    englishTranslation: "Tea",
    exampleFarsi: "یک لیوان چای بدهید.",
    examplePhonetic: "yek livan chai bedahid.",
    exampleEnglish: "Give me a glass of tea.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شکر",
    phonetic: "shekar",
    englishTranslation: "Sugar",
    exampleFarsi: "چای با شکر می‌خورم.",
    examplePhonetic: "chai ba shekar mikhoram.",
    exampleEnglish: "I drink tea with sugar.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نمک",
    phonetic: "namak",
    englishTranslation: "Salt",
    exampleFarsi: "لطفاً نمک را بده.",
    examplePhonetic: "lotfan namak ra bedeh.",
    exampleEnglish: "Please pass the salt.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "تخم مرغ",
    phonetic: "tokhme morgh",
    englishTranslation: "Egg",
    exampleFarsi: "صبحانه تخم مرغ خوردم.",
    examplePhonetic: "sobhaneh tokhme morgh khordam.",
    exampleEnglish: "I had eggs for breakfast.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پنیر",
    phonetic: "panir",
    englishTranslation: "Cheese",
    exampleFarsi: "پنیر با نان خوشمزه است.",
    examplePhonetic: "panir ba nan khoshmaze ast.",
    exampleEnglish: "Cheese with bread is delicious.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "ماست",
    phonetic: "maast",
    englishTranslation: "Yogurt",
    exampleFarsi: "ماست برای سلامتی خوب است.",
    examplePhonetic: "maast baraye salamati khoob ast.",
    exampleEnglish: "Yogurt is good for health.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 10. Family Basics
// ---------------------------------------------------------------------------
const familyBasics: WordData[] = [
  {
    farsiWord: "مادر",
    phonetic: "madar",
    englishTranslation: "Mother",
    exampleFarsi: "مادرم آشپزی می‌کند.",
    examplePhonetic: "madaram ashpazi mikonad.",
    exampleEnglish: "My mother is cooking.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پدر",
    phonetic: "pedar",
    englishTranslation: "Father",
    exampleFarsi: "پدرم سر کار است.",
    examplePhonetic: "pedaram sare kar ast.",
    exampleEnglish: "My father is at work.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "برادر",
    phonetic: "baradar",
    englishTranslation: "Brother",
    exampleFarsi: "برادرم دانشجو است.",
    examplePhonetic: "baradaram daneshjoo ast.",
    exampleEnglish: "My brother is a student.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خواهر",
    phonetic: "khahar",
    englishTranslation: "Sister",
    exampleFarsi: "خواهرم معلم است.",
    examplePhonetic: "khaharam moalem ast.",
    exampleEnglish: "My sister is a teacher.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پسر",
    phonetic: "pesar",
    englishTranslation: "Son/Boy",
    exampleFarsi: "پسرم به مدرسه می‌رود.",
    examplePhonetic: "pesaram be madreseh miravad.",
    exampleEnglish: "My son goes to school.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "دختر",
    phonetic: "dokhtar",
    englishTranslation: "Daughter/Girl",
    exampleFarsi: "دخترم کتاب می‌خواند.",
    examplePhonetic: "dokhtaram ketab mikhanad.",
    exampleEnglish: "My daughter is reading a book.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بچه",
    phonetic: "bacheh",
    englishTranslation: "Child",
    exampleFarsi: "بچه‌ها در پارک بازی می‌کنند.",
    examplePhonetic: "bacheh-ha dar park bazi mikonand.",
    exampleEnglish: "The children are playing in the park.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نوزاد",
    phonetic: "nozad",
    englishTranslation: "Baby",
    exampleFarsi: "نوزاد خوابیده است.",
    examplePhonetic: "nozad khabideh ast.",
    exampleEnglish: "The baby is sleeping.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 11. Numbers 11-20
// ---------------------------------------------------------------------------
const numbersExtended: WordData[] = [
  {
    farsiWord: "یازده",
    phonetic: "yazdah",
    englishTranslation: "Eleven",
    exampleFarsi: "ساعت یازده است.",
    examplePhonetic: "saate yazdah ast.",
    exampleEnglish: "It's eleven o'clock.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "دوازده",
    phonetic: "davazdah",
    englishTranslation: "Twelve",
    exampleFarsi: "دوازده ماه در سال است.",
    examplePhonetic: "davazdah mah dar sal ast.",
    exampleEnglish: "There are twelve months in a year.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سیزده",
    phonetic: "sizdah",
    englishTranslation: "Thirteen",
    exampleFarsi: "سیزده بدر روز طبیعت است.",
    examplePhonetic: "sizdah bedar rooze tabiat ast.",
    exampleEnglish: "Sizdah Bedar is nature day.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "چهارده",
    phonetic: "chahardah",
    englishTranslation: "Fourteen",
    exampleFarsi: "چهارده نفر در کلاس هستند.",
    examplePhonetic: "chahardah nafar dar kelas hastand.",
    exampleEnglish: "There are fourteen people in class.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "پانزده",
    phonetic: "panzdah",
    englishTranslation: "Fifteen",
    exampleFarsi: "پانزده دقیقه صبر کن.",
    examplePhonetic: "panzdah daghighe sabr kon.",
    exampleEnglish: "Wait fifteen minutes.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "شانزده",
    phonetic: "shanzdah",
    englishTranslation: "Sixteen",
    exampleFarsi: "او شانزده ساله است.",
    examplePhonetic: "oo shanzdah saleh ast.",
    exampleEnglish: "He/She is sixteen years old.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "هفده",
    phonetic: "hevdah",
    englishTranslation: "Seventeen",
    exampleFarsi: "هفده نفر آمدند.",
    examplePhonetic: "hevdah nafar amadand.",
    exampleEnglish: "Seventeen people came.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "هجده",
    phonetic: "hejdah",
    englishTranslation: "Eighteen",
    exampleFarsi: "هجده سال دارم.",
    examplePhonetic: "hejdah sal daram.",
    exampleEnglish: "I am eighteen years old.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نوزده",
    phonetic: "noozdah",
    englishTranslation: "Nineteen",
    exampleFarsi: "نوزده روز مانده است.",
    examplePhonetic: "noozdah rooz mandeh ast.",
    exampleEnglish: "Nineteen days are remaining.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بیست",
    phonetic: "bist",
    englishTranslation: "Twenty",
    exampleFarsi: "بیست نفر دعوت شدند.",
    examplePhonetic: "bist nafar davat shodand.",
    exampleEnglish: "Twenty people were invited.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 12. Basic Adjectives
// ---------------------------------------------------------------------------
const basicAdjectives: WordData[] = [
  {
    farsiWord: "بزرگ",
    phonetic: "bozorg",
    englishTranslation: "Big",
    exampleFarsi: "این خانه خیلی بزرگ است.",
    examplePhonetic: "in khaneh kheyli bozorg ast.",
    exampleEnglish: "This house is very big.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کوچک",
    phonetic: "koochak",
    englishTranslation: "Small",
    exampleFarsi: "اتاقم کوچک است.",
    examplePhonetic: "otagham koochak ast.",
    exampleEnglish: "My room is small.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خوب",
    phonetic: "khoob",
    englishTranslation: "Good",
    exampleFarsi: "این غذا خیلی خوب است.",
    examplePhonetic: "in ghaza kheyli khoob ast.",
    exampleEnglish: "This food is very good.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بد",
    phonetic: "bad",
    englishTranslation: "Bad",
    exampleFarsi: "هوا بد شده است.",
    examplePhonetic: "hava bad shodeh ast.",
    exampleEnglish: "The weather has gotten bad.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "گرم",
    phonetic: "garm",
    englishTranslation: "Hot",
    exampleFarsi: "تابستان هوا خیلی گرم است.",
    examplePhonetic: "tabestaan hava kheyli garm ast.",
    exampleEnglish: "In summer the weather is very hot.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سرد",
    phonetic: "sard",
    englishTranslation: "Cold",
    exampleFarsi: "زمستان هوا سرد است.",
    examplePhonetic: "zemestaan hava sard ast.",
    exampleEnglish: "In winter the weather is cold.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "جدید",
    phonetic: "jadid",
    englishTranslation: "New",
    exampleFarsi: "ماشین جدید خریدم.",
    examplePhonetic: "mashine jadid kharidam.",
    exampleEnglish: "I bought a new car.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "قدیمی",
    phonetic: "ghadimi",
    englishTranslation: "Old",
    exampleFarsi: "این ساختمان خیلی قدیمی است.",
    examplePhonetic: "in sakhteman kheyli ghadimi ast.",
    exampleEnglish: "This building is very old.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "زیبا",
    phonetic: "ziba",
    englishTranslation: "Beautiful",
    exampleFarsi: "این شهر خیلی زیباست.",
    examplePhonetic: "in shahr kheyli zibaast.",
    exampleEnglish: "This city is very beautiful.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "سریع",
    phonetic: "saree",
    englishTranslation: "Fast",
    exampleFarsi: "او خیلی سریع می‌دود.",
    examplePhonetic: "oo kheyli saree midavad.",
    exampleEnglish: "He/She runs very fast.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// 13. Simple Verbs
// ---------------------------------------------------------------------------
const simpleVerbs: WordData[] = [
  {
    farsiWord: "رفتن",
    phonetic: "raftan",
    englishTranslation: "To go",
    exampleFarsi: "فردا به مدرسه می‌روم.",
    examplePhonetic: "farda be madreseh miravam.",
    exampleEnglish: "Tomorrow I go to school.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "آمدن",
    phonetic: "amadan",
    englishTranslation: "To come",
    exampleFarsi: "دوستم به خانه‌ام آمد.",
    examplePhonetic: "doostam be khaneh-am amad.",
    exampleEnglish: "My friend came to my house.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خوردن",
    phonetic: "khordan",
    englishTranslation: "To eat",
    exampleFarsi: "صبحانه نان و پنیر می‌خورم.",
    examplePhonetic: "sobhaneh nan va panir mikhoram.",
    exampleEnglish: "I eat bread and cheese for breakfast.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "نوشیدن",
    phonetic: "nooshidan",
    englishTranslation: "To drink",
    exampleFarsi: "هر روز آب زیاد می‌نوشم.",
    examplePhonetic: "har rooz aab-e ziad minoosham.",
    exampleEnglish: "I drink a lot of water every day.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "خوابیدن",
    phonetic: "khabidan",
    englishTranslation: "To sleep",
    exampleFarsi: "ساعت ده می‌خوابم.",
    examplePhonetic: "saate dah mikhabam.",
    exampleEnglish: "I sleep at ten o'clock.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "دیدن",
    phonetic: "didan",
    englishTranslation: "To see",
    exampleFarsi: "دیروز دوستم را دیدم.",
    examplePhonetic: "dirooz doostam ra didam.",
    exampleEnglish: "I saw my friend yesterday.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "گفتن",
    phonetic: "goftan",
    englishTranslation: "To say",
    exampleFarsi: "او حقیقت را گفت.",
    examplePhonetic: "oo haghighat ra goft.",
    exampleEnglish: "He/She told the truth.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "کردن",
    phonetic: "kardan",
    englishTranslation: "To do",
    exampleFarsi: "امروز چه کار کردی؟",
    examplePhonetic: "emrooz che kar kardi?",
    exampleEnglish: "What did you do today?",
    difficultyLevel: 1,
  },
  {
    farsiWord: "داشتن",
    phonetic: "dashtan",
    englishTranslation: "To have",
    exampleFarsi: "من دو تا برادر دارم.",
    examplePhonetic: "man do ta baradar daram.",
    exampleEnglish: "I have two brothers.",
    difficultyLevel: 1,
  },
  {
    farsiWord: "بودن",
    phonetic: "boodan",
    englishTranslation: "To be",
    exampleFarsi: "خوشحال بودن مهم است.",
    examplePhonetic: "khoshhal boodan mohem ast.",
    exampleEnglish: "Being happy is important.",
    difficultyLevel: 1,
  },
];

// ---------------------------------------------------------------------------
// Main seed function
// ---------------------------------------------------------------------------
export async function seedLevel1() {
  console.log("\n=== Level 1: Beginner ===\n");
  let total = 0;

  const r1 = await seedCategory({
    name: "Basic Greetings",
    slug: "greetings",
    description: "Essential greetings and polite expressions",
    icon: "👋",
    level: 1,
    sortOrder: 1,
    words: greetings,
  });
  total += r1.wordsAdded;

  const r2 = await seedCategory({
    name: "Essential Words",
    slug: "essential",
    description: "Core everyday vocabulary for basic communication",
    icon: "⭐",
    level: 1,
    sortOrder: 2,
    words: essential,
  });
  total += r2.wordsAdded;

  const r3 = await seedCategory({
    name: "Numbers 1-10",
    slug: "numbers",
    description: "Basic numbers from one to ten, hundred, and thousand",
    icon: "🔢",
    level: 1,
    sortOrder: 3,
    words: numbers,
  });
  total += r3.wordsAdded;

  const r4 = await seedCategory({
    name: "Colors",
    slug: "colors",
    description: "Common colors used in daily conversation",
    icon: "🎨",
    level: 1,
    sortOrder: 4,
    words: colors,
  });
  total += r4.wordsAdded;

  const r5 = await seedCategory({
    name: "Prepositions",
    slug: "prepositions",
    description: "Essential prepositions for describing position and direction",
    icon: "📍",
    level: 1,
    sortOrder: 5,
    words: prepositions,
  });
  total += r5.wordsAdded;

  const r6 = await seedCategory({
    name: "Common Phrases",
    slug: "common-phrases",
    description: "Frequently used phrases in everyday Farsi",
    icon: "💬",
    level: 1,
    sortOrder: 6,
    words: commonPhrases,
  });
  total += r6.wordsAdded;

  const r7 = await seedCategory({
    name: "Pronouns",
    slug: "pronouns",
    description: "Personal pronouns and demonstratives",
    icon: "👆",
    level: 1,
    sortOrder: 7,
    words: pronouns,
  });
  total += r7.wordsAdded;

  const r8 = await seedCategory({
    name: "Everyday Objects",
    slug: "everyday-objects",
    description: "Common household and everyday items",
    icon: "🏷️",
    level: 1,
    sortOrder: 8,
    words: everydayObjects,
  });
  total += r8.wordsAdded;

  const r9 = await seedCategory({
    name: "Basic Food",
    slug: "basic-food",
    description: "Essential food and drink vocabulary",
    icon: "🍞",
    level: 1,
    sortOrder: 9,
    words: basicFood,
  });
  total += r9.wordsAdded;

  const r10 = await seedCategory({
    name: "Family Basics",
    slug: "family-basics",
    description: "Core family member vocabulary",
    icon: "👨‍👩‍👧",
    level: 1,
    sortOrder: 10,
    words: familyBasics,
  });
  total += r10.wordsAdded;

  const r11 = await seedCategory({
    name: "Numbers 11-20",
    slug: "numbers-extended",
    description: "Numbers from eleven to twenty",
    icon: "🔢",
    level: 1,
    sortOrder: 11,
    words: numbersExtended,
  });
  total += r11.wordsAdded;

  const r12 = await seedCategory({
    name: "Basic Adjectives",
    slug: "basic-adjectives",
    description: "Common adjectives for describing things",
    icon: "📝",
    level: 1,
    sortOrder: 12,
    words: basicAdjectives,
  });
  total += r12.wordsAdded;

  const r13 = await seedCategory({
    name: "Simple Verbs",
    slug: "simple-verbs",
    description: "Essential verbs for basic sentence construction",
    icon: "🏃",
    level: 1,
    sortOrder: 13,
    words: simpleVerbs,
  });
  total += r13.wordsAdded;

  console.log(`\nLevel 1 complete: ${total} new words added\n`);
  return total;
}
